### PR TITLE
jenv: install fish function symlinks

### LINKED ISSUE #315: jenv doctor incorrect fix for "jenv not loaded in fish"
Using jenv doctor in fish gives this message:
[ERROR]	Jenv is not loaded in your fish
[ERROR]	To fix : 	echo eval "$(jenv init -)" >> your profile

however, fish doesnt use the `$` style, and the 'correct' styled command gives this output:
```
> eval (jenv init -)
jenv: no such command `sh-'
```

the sequence for loading fish described in the README worked for me, though.

should the doctor output be improved?

### PR DESCRIPTION
**Pull request by davidxia**
The caveat isn't compatible with fish shell.
This PR changes the caveat for fish shell to show the
commands specified in the upstream's README here \[1\].

This PR does not change the caveat for other shells.

fixes https://github.com/jenv/jenv/issues/315

I have tested this PR and get the output below.

With bash set as default shell (`chsh -s $(which bash)`):

```
brew info jenv

jenv: stable 0.5.4, HEAD
Manage your Java environment
https://www.jenv.be/
/opt/homebrew/Cellar/jenv/0.5.4 (82 files, 72.3KB) *
  Built from source on 2021-05-07 at 17:19:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/jenv.rb
License: MIT
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate jenv, add the following to your /Users/dxia/.bash_profile:

  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
==> Analytics
install: 9,672 (30 days), 30,663 (90 days), 129,619 (365 days)
install-on-request: 9,670 (30 days), 30,635 (90 days), 128,558 (365 days)
build-error: 0 (30 days)
```

With fish set as default shell:

```
brew info jenv

jenv: stable 0.5.4, HEAD
Manage your Java environment
https://www.jenv.be/
/opt/homebrew/Cellar/jenv/0.5.4 (82 files, 72.3KB) *
  Built from source on 2021-05-07 at 17:19:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/jenv.rb
License: MIT
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate jenv, run the following commands:

  echo 'set -g fish_user_paths "/opt/homebrew/opt/jenv/bin" $fish_user_paths' >> ~/.config/fish/config.fish
  echo 'status --is-interactive; and source (jenv init -|psub)' >> ~/.config/fish/config.fish
  cp /opt/homebrew/opt/jenv/libexec/fish/jenv.fish ~/.config/fish/functions/jenv.fish
  cp /opt/homebrew/opt/jenv/libexec/fish/export.fish ~/.config/fish/functions/export.fish
==> Analytics
install: 9,672 (30 days), 30,663 (90 days), 129,619 (365 days)
install-on-request: 9,670 (30 days), 30,635 (90 days), 128,558 (365 days)
build-error: 0 (30 days)
```

1: https://github.com/jenv/jenv/blob/9bbc5ebfe6f38252a1a0f28897c7ae52e6a483a0/README.md

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

File: Formula/jenv.rb [hunk 1]
```diff
@@ -15,12 +15,24 @@ def install
...
-      To activate jenv, add the following to your #{shell_profile}:
+    if preferred == :fish
+      s = <<~EOS
+        To activate jenv, run the following commands:
 
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+      EOS
+      s << "  fish_add_path #{bin}\n" if bin.directory?
```
Comment (davidxia) [inline Formula/jenv.rb:23]: I originally had

```
      s << "  #{Utils::Shell.prepend_path_in_profile(bin)}\n" if bin.directory?
```

which outputs

```
echo 'set -g fish_user_paths "/opt/homebrew/opt/jenv/bin" $fish_user_paths' >> ~/.config/fish/config.fish
```

But current fish docs here \[2\] say

> A faster way is to use the `fish_add_path function`...
> The advantage is that you don't have to go mucking around in files:
> just run this once at the command line, and it will affect the current session and all future instances too.
>
> Or you can modify `$fish_user_paths` yourself, but you should be careful not to append to it
> unconditionally in config.fish, or it will grow longer and longer.

`set -g fish_user_paths "/opt/homebrew/opt/jenv/bin" $fish_user_paths` seems to be doing just that: appending unconditionally. But I haven't observed my `$PATH` growing longer and longer either.

In any case, that's why I put the line above. Related issue https://github.com/Homebrew/brew/issues/8965.
I'll submit a PR for that issue. If that gets merged, I'll open another PR here to update this line to use the utility function.

2: https://fishshell.com/docs/current/tutorial.html#path

Comment (carlocab) [inline Formula/jenv.rb:23]: Why is this needed? `jenv` is not keg-only, so it should already be in a user's path.

File: Formula/jenv.rb [hunk 2]
```diff
@@ -15,12 +15,24 @@ def install
...
+      s << "  echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}\n"
+      s << "  cp #{libexec}/fish/jenv.fish ~/.config/fish/functions/jenv.fish\n"
+      s << "  cp #{libexec}/fish/export.fish ~/.config/fish/functions/export.fish\n\n"
```
Comment (carlocab) [inline Formula/jenv.rb:26]: Why `cp`, and not create symlinks? Copying requires updating every time `jenv.fish` and `export.fish` changes, and verifying whether it has can become quite involved.

Will the right place to create these copies/symlinks still be `~/.config/fish` if I've set `XDG_CONFIG_HOME` to something else?

Comment (carlocab) [inline Formula/jenv.rb:26]: Why append all of these to `s` instead of just including them when `s` is first defined?

File: Formula/jenv.rb (hunk 1 above)
Comment (davidxia) [reply Formula/jenv.rb:23]: ah thanks, removed

File: Formula/jenv.rb (hunk 2 above)
Comment (davidxia) [reply Formula/jenv.rb:26]: thanks, updated

> Will the right place to create these copies/symlinks still be ~/.config/fish if I've set XDG_CONFIG_HOME to something else?

I'm not sure. What's the best way here?

Comment (davidxia) [reply Formula/jenv.rb:26]: removed

Comment (davidxia) [reply Formula/jenv.rb]: I didn't realize I didn't need them. Not very familiar with Ruby :)

File: Formula/jenv.rb [hunk 3]
```diff
@@ -15,12 +15,23 @@ def install
...
+    if preferred == :fish
+      <<~EOS
+        To activate jenv, run the following commands:
 
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+          echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}
+          ln -sf #{libexec}/fish/jenv.fish ~/.config/fish/functions/jenv.fish
+          ln -sf #{libexec}/fish/export.fish ~/.config/fish/functions/export.fish
```
Comment (carlocab) [inline Formula/jenv.rb:24]:
```suggestion
          ln -sf #{opt_libexec}/fish/*.fish ~/.config/fish/functions
```
I think this should work. We should use `opt_libexec` to avoid referencing full Cellar paths in the caveats (which you'll sometimes see with just `libexec`).

Re `XDG_CONFIG_HOME`, I don't know how variable substitution works in fish, but with bash/zsh:
```suggestion
          ln -sf #{opt_libexec}/fish/*.fish ${XDG_CONFIG_HOME:-$HOME/.config}/fish/functions
```

Comment (davidxia) [reply Formula/jenv.rb]: I don't think fish shell has this type of variable defaulting. I've updated with a workaround.

```
ln -sf /opt/homebrew/opt/jenv/libexec/fish/*.fish ${XDG_CONFIG_HOME:-$HOME/.config}/fish/functions

fish: ${ is not a valid variable in fish.
ln -sf /opt/homebrew/opt/jenv/libexec/fish/*.fish ${XDG_CONFIG_HOME:-$HOME/.config}/fish/functions
```

**Comment by davidxia** [comment]
@carlocab Thanks for reviewing. Let me know any next steps required from me.

File: Formula/jenv.rb [hunk 4]
```diff
@@ -15,12 +15,23 @@ def install
...
-      To activate jenv, add the following to your #{shell_profile}:
+    if preferred == :fish
+      <<~EOS
+        To activate jenv, run the following commands:
 
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+          echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}
+          set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME $HOME
```
Comment (carlocab) [inline Formula/jenv.rb:23]: I'm not sure this means the same thing as what I suggested. I'm also unsure about these changes in general since I don't use `fish`, so I'm hoping someone who does can weigh in here 🙂

Comment (davidxia) [reply Formula/jenv.rb:23]: Is there someone else we can ask for a review?

Comment (SMillerDev) [reply Formula/jenv.rb:23]: Why do we need to check for that variable only in fish?

Comment (carlocab) [reply Formula/jenv.rb:23]: Because the other shells don't seem to require doing anything with `~/.config`

**Comment by davidxia** [comment]
Bumping to see what else I can do to move this forward. It seems like this thread is the only unresolved one? https://github.com/Homebrew/homebrew-core/pull/76864#discussion_r629693442

**Review by cap10morgan — DISMISSED** [review]
I started to create a PR with more or less these same changes and then found this. This all works for me and is a big improvement over the current (broken) instructions. Thanks @davidxia!

File: Formula/jenv.rb [hunk 5]
```diff
@@ -15,12 +15,23 @@ def install
...
+          ln -sf #{opt_libexec}/fish/*.fish $XDG_CONFIG_HOME/.config/fish/functions
```
Comment (carlocab) [inline Formula/jenv.rb:24]:
```suggestion
          set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME $HOME/.config
          ln -sf #{opt_libexec}/fish/*.fish $XDG_CONFIG_HOME/fish/functions
```
The default value of `XDG_CONFIG_HOME` is `~/.config`.

Comment (carlocab) [inline Formula/jenv.rb:24]: If we need to symlink the `.fish` files into `~/.config/fish/functions`, wouldn't it be better to install them into the right location instead? i.e. using the variable [`fish_function`](https://rubydoc.brew.sh/Formula.html#fish_function-instance_method). For example, with something like:
```ruby
fish_function.install Dir[libexec/"fish/*.fish"]
```
in the `install` method.

**Review by carlocab — COMMENTED** [review]
I don't mind merging this, subject to one suggestion, and pending the answer to one question.

File: Formula/jenv.rb (hunk 5 above)
Comment (davidxia) [reply Formula/jenv.rb]: SGTM, feel free to update this branch with that change or suggest one here I can commit. I'm just not sure the exact code you had in mind here.

File: Formula/jenv.rb [hunk 6]
```diff
@@ -15,12 +15,23 @@ def install
...
+    if preferred == :fish
+      <<~EOS
+        To activate jenv, run the following commands:
 
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+          echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}
+          set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME $HOME/.config
+          ln -sf #{opt_libexec}/fish/*.fish $XDG_CONFIG_HOME/fish/functions
```
Comment (cap10morgan) [inline Formula/jenv.rb:24]:
```suggestion
```

File: Formula/jenv.rb [hunk 7]
```diff
@@ -15,12 +15,23 @@ def install
   end
```
Comment (cap10morgan) [inline Formula/jenv.rb:15]:
```suggestion
    fish_function.install Dir[libexec/"fish/*.fish"]
  end
```

**Review by cap10morgan — COMMENTED** [review]
Hopefully have the last part in here as adoptable suggestions (in case that's helpful; feel free to ignore if not).

File: Formula/jenv.rb (hunk 5 above)
Comment (carlocab) [reply Formula/jenv.rb]: Something like this:
```diff
diff --git a/Formula/jenv.rb b/Formula/jenv.rb
index a1f3a7e649..7874997525 100644
--- a/Formula/jenv.rb
+++ b/Formula/jenv.rb
@@ -12,6 +12,7 @@ class Jenv < Formula
   def install
     libexec.install Dir["*"]
     bin.write_exec_script libexec/"bin/jenv"
+    fish_function.install Dir[libexec/"fish/*.fish"]
   end
 
   def caveats
```
I'd want to test this doesn't break anything first, since `#install` will move the files from `libexec/"fish"` into the `fish_function` directory (`share/"fish/vendor_functions.d"`).

If it turns out moving those files breaks things, we can try `#install_symlink` instead of `#install`.

Also, assuming that one of these is the right thing to do, presumably the caveats need to be adjusted (as presumably, we would no longer need symlinks into `~/.config`).

File: Formula/jenv.rb (hunk 6 above)
Comment (carlocab) [reply Formula/jenv.rb:24]: I think we wouldn't need to set `XDG_CONFIG_HOME` anymore as well.

File: Formula/jenv.rb [hunk 8]
```diff
@@ -15,12 +15,23 @@ def install
...
-      To activate jenv, add the following to your #{shell_profile}:
+    if preferred == :fish
+      <<~EOS
+        To activate jenv, run the following commands:
 
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+          echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}
+          set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME $HOME/.config
```
Comment (cap10morgan) [inline Formula/jenv.rb:23]:
```suggestion
```

File: Formula/jenv.rb (hunk 5 above)
Comment (cap10morgan) [reply Formula/jenv.rb]: `#install_symlink` would make homebrew installs more like non-homebrew fish installs, which might be desirable. But it seems like either _should_ work.

Comment (carlocab) [reply Formula/jenv.rb]: Maybe `#install_symlink` is better then. `#install` could work now, but I don't think we can rule out it causing problems later on.

File: Formula/jenv.rb (hunk 7 above)
Comment (davidxia) [reply Formula/jenv.rb:15]:
```suggestion
    fish_function.install_symlink Dir[libexec/"fish/*.fish"]
  end
```

File: Formula/jenv.rb (hunk 5 above)
Comment (davidxia) [reply Formula/jenv.rb]: Neither `#install_symlink` nor `#install` seem to work. Any ideas?

```
brew uninstall --force jenv                                                                                                                            ⮂ 13:37:33 ⮂ 2021-06-02
Uninstalling jenv... (84 files, 73.1KB)
 dxia@dxia-mbp ⮀ /o/h/L/T/h/homebrew-core ⮀ ⭠ jenv-caveat-fish  ⮀
 ⮀ la ~/.config/fish/functions/                                                                                                                           ⮂ 13:37:44 ⮂ 2021-06-02
total 32
drwxr-xr-x   8 dxia  staff   256B May 12 07:01 .
drwx------  16 dxia  staff   512B May 12 07:01 ..
-rw-r--r--   1 dxia  staff   816B Feb 17  2019 burk.fish
lrwxr-xr-x   1 dxia  staff    47B May  8 13:47 export.fish -> /opt/homebrew/opt/jenv/libexec/fish/export.fish
-rw-r--r--   1 dxia  staff   5.2K Sep  9  2014 fish_prompt.fish
-rw-r--r--   1 dxia  staff    55B Feb 13  2019 fish_user_key_bindings.fish
lrwxr-xr-x   1 dxia  staff    45B Apr  8 15:11 fzf_key_bindings.fish -> /opt/homebrew/opt/fzf/shell/key-bindings.fish
lrwxr-xr-x   1 dxia  staff    45B May  8 13:47 jenv.fish -> /opt/homebrew/opt/jenv/libexec/fish/jenv.fish
 dxia@dxia-mbp ⮀ /o/h/L/T/h/homebrew-core ⮀ ⭠ jenv-caveat-fish  ⮀
 ⮀ rm ~/.config/fish/functions/jenv.fish ~/.config/fish/functions/export.fish                                                                             ⮂ 13:37:46 ⮂ 2021-06-02
 dxia@dxia-mbp ⮀ /o/h/L/T/h/homebrew-core ⮀ ⭠ jenv-caveat-fish  ⮀
 ⮀ la ~/.config/fish/functions/                                                                                                                           ⮂ 13:38:05 ⮂ 2021-06-02
total 32
drwxr-xr-x   6 dxia  staff   192B Jun  2 13:38 .
drwx------  16 dxia  staff   512B May 12 07:01 ..
-rw-r--r--   1 dxia  staff   816B Feb 17  2019 burk.fish
-rw-r--r--   1 dxia  staff   5.2K Sep  9  2014 fish_prompt.fish
-rw-r--r--   1 dxia  staff    55B Feb 13  2019 fish_user_key_bindings.fish
lrwxr-xr-x   1 dxia  staff    45B Apr  8 15:11 fzf_key_bindings.fish -> /opt/homebrew/opt/fzf/shell/key-bindings.fish
 dxia@dxia-mbp ⮀ /o/h/L/T/h/homebrew-core ⮀ ⭠ jenv-caveat-fish  ⮀
 ⮀ brew install --build-from-source jenv                                                                                                                  ⮂ 13:38:06 ⮂ 2021-06-02
==> Downloading https://github.com/jenv/jenv/archive/0.5.4.tar.gz
Already downloaded: /Users/dxia/Library/Caches/Homebrew/downloads/f9afe32d5657c7d7caf6d54af2c81e10659e0f46696133296bbc3cb6cc20cead--jenv-0.5.4.tar.gz
==> Caveats
To activate jenv, run the following commands:

  echo 'status --is-interactive; and source (jenv init -|psub)' >> ~/.config/fish/config.fish


fish functions have been installed to:
  /opt/homebrew/share/fish/vendor_functions.d
==> Summary
🍺  /opt/homebrew/Cellar/jenv/0.5.4: 84 files, 73KB, built in 2 seconds
 dxia@dxia-mbp ⮀ /o/h/L/T/h/homebrew-core ⮀ ⭠ jenv-caveat-fish  ⮀
 ⮀ la ~/.config/fish/functions/                                                                                                                           ⮂ 13:38:13 ⮂ 2021-06-02
total 32
drwxr-xr-x   6 dxia  staff   192B Jun  2 13:38 .
drwx------  16 dxia  staff   512B May 12 07:01 ..
-rw-r--r--   1 dxia  staff   816B Feb 17  2019 burk.fish
-rw-r--r--   1 dxia  staff   5.2K Sep  9  2014 fish_prompt.fish
-rw-r--r--   1 dxia  staff    55B Feb 13  2019 fish_user_key_bindings.fish
lrwxr-xr-x   1 dxia  staff    45B Apr  8 15:11 fzf_key_bindings.fish -> /opt/homebrew/opt/fzf/shell/key-bindings.fish
```

Comment (cap10morgan) [reply Formula/jenv.rb]: @davidxia I think they're being installed elsewhere, according to the output:

```
fish functions have been installed to:
  /opt/homebrew/share/fish/vendor_functions.d
```

Fish should still find them there. Can you test that?

Comment (davidxia) [reply Formula/jenv.rb]: Thanks. Didn't notice that. Is the below enough? No need for symlinks in `~/.config/fish`?

```
la /opt/homebrew/share/fish/vendor_functions.d                                                                                                         ⮂ 13:48:41 ⮂ 2021-06-02
total 0
drwxr-xr-x   4 dxia  admin   128B Jun  2 13:40 .
drwxr-xr-x  12 dxia  admin   384B Jun  2 13:40 ..
lrwxr-xr-x   1 dxia  admin    68B Jun  2 13:40 export.fish -> ../../../Cellar/jenv/0.5.4/share/fish/vendor_functions.d/export.fish
lrwxr-xr-x   1 dxia  admin    66B Jun  2 13:40 jenv.fish -> ../../../Cellar/jenv/0.5.4/share/fish/vendor_functions.d/jenv.fish
```

Comment (davidxia) [reply Formula/jenv.rb]: jenv still works. It seems to be enough?

```
rm ~/.config/fish/functions/jenv.fish ~/.config/fish/functions/export.fish

[new terminal]

java -version                                                                                                                                          ⮂ 13:49:32 ⮂ 2021-06-02
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
 dxia@dxia-mbp ⮀ ~ ⮀
 ⮀ jenv versions                                                                                                                                          ⮂ 13:49:40 ⮂ 2021-06-02
  system
* 11 (set by /Users/dxia/.java-version)
  11.0.10
  16
  corretto64-11.0.10
  openjdk64-16
 dxia@dxia-mbp ⮀ ~ ⮀
 ⮀ jenv shell 16                                                                                                                                          ⮂ 13:49:42 ⮂ 2021-06-02
 dxia@dxia-mbp ⮀ ~ ⮀
 ⮀ java -version                                                                                                                                          ⮂ 13:50:12 ⮂ 2021-06-02
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)
```

Comment (cap10morgan) [reply Formula/jenv.rb]: I think so. I don't have a strong sense of what those functions do for jenv as it seems to work without them too 🤷🏻.

Comment (carlocab) [reply Formula/jenv.rb]: Yes, the idea is that the symlinks into `~/.config/fish` should no longer be needed. Please try using `jenv` and see if it's working normally.

Comment (davidxia) [reply Formula/jenv.rb]: Seems to be working normally for me!

File: Formula/jenv.rb [hunk 9]
```diff
@@ -12,15 +12,25 @@ class Jenv < Formula
...
-      To activate jenv, add the following to your #{shell_profile}:
+    if preferred == :fish
+      <<~EOS
+        To activate jenv, run the following commands:
 
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+          echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}
+
```
Comment (carlocab) [inline Formula/jenv.rb:24]:
```suggestion
```

File: Formula/jenv.rb [hunk 10]
```diff
@@ -12,15 +12,25 @@ class Jenv < Formula
...
     bin.write_exec_script libexec/"bin/jenv"
+    fish_function.install_symlink Dir[libexec/"fish/*.fish"]
   end
 
   def caveats
-    <<~EOS
-      To activate jenv, add the following to your #{shell_profile}:
+    if preferred == :fish
+      <<~EOS
+        To activate jenv, run the following commands:
```
Comment (carlocab) [inline Formula/jenv.rb:22]:
```suggestion
```

File: Formula/jenv.rb [hunk 11]
```diff
@@ -12,15 +12,25 @@ class Jenv < Formula
...
-        export PATH="$HOME/.jenv/bin:$PATH"
-        eval "$(jenv init -)"
-    EOS
+          echo 'status --is-interactive; and source (jenv init -|psub)' >> #{shell_profile}
+
+      EOS
+    else
+      <<~EOS
+        To activate jenv, add the following to your #{shell_profile}:
+
```
Comment (carlocab) [inline Formula/jenv.rb:29]:
```suggestion
```

**Review by carlocab — COMMENTED** [review]
Great, I think we can merge this soon. Let's just try to clean up the whitespace a bit; I don't think we need this much.

File: Formula/jenv.rb (hunk 5 above)
Comment (carlocab) [reply Formula/jenv.rb]: Awesome. One last thing and this should be good to go.

Comment (davidxia) [reply Formula/jenv.rb]: Thanks. Committed your suggestions!

**Comment by cap10morgan** [comment]
FWIW the old title of this PR is still appropriate for it. Or at least both effects are pretty important here (i.e. fixing the fish caveat instructions and installing the functions in the appropriate place).

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks, @davidxia, @cap10morgan.
