### PR TITLE
mujs: fix pkg-config prefix path

### LINKED ISSUE #126846: Mujs 1.3.3 seems broken on Apple Silicon machines
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config 

HOMEBREW_VERSION: 4.0.10-11-gdb7c74d
ORIGIN: https://github.com/Homebrew/brew
HEAD: db7c74d0988c087c3405864480bc08ef7368a962
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bdf52e4896818e57839a8110779b8dad97fe505c
Core tap last commit: 89 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1678558616
Xcode: N/A
Rosetta 2: false```
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

use `mujs`

### What happened (include all command output)?

fatal error: 'mujs.h' file not found

### What did you expect to happen?

mujs works

### Step-by-step reproduction instructions (by running `brew` commands)

I am trying to build the osxbundle of mpv and I notice the error during build as

fatal error: 'mujs.h' file not found

In order to triage the issue, I take a look at  `/opt/homebrew/Cellar/mujs/1.3.3/lib/pkgconfig/mujs.pc`
. The contains is

```shell
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.3
Cflags: -I/usr/local/include
Libs: -L/usr/local/lib -lmujs
Libs.private: -lm
```

then I compare the content from previous version, which does not have the issue

``` 
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.2
Cflags: -I/opt/homebrew/Cellar/mujs/1.3.2/include
Libs: -L/opt/homebrew/Cellar/mujs/1.3.2/lib -lmujs
Libs.private: -lm
```

I feel the 1.3.3 version contains the incorrect Cflags and Libs values obviously. it should always point to the homebrew folder, right?

So I did an experiment by modifying the mujs.pc into
```
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.3
Cflags: -I/opt/homebrew/Cellar/mujs/1.3.3/include
Libs: -L/opt/homebrew/Cellar/mujs/1.3.3/lib -lmujs
Libs.private: -lm
```
and then I no longer saw the 'mujs.h' file not found error.

I notice that, inside the PR when homebrew bumps the `mujs` version https://github.com/Homebrew/homebrew-core/pull/126240. A patch was removed. I am not sure whether it is related or not, I can not find the upstream link of the path. maybe we still need the patch?

Thanks

### PR DESCRIPTION
**Pull request by kiracus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

fix https://github.com/Homebrew/homebrew-core/issues/126846

### CODE REVIEW

File: Formula/mpv.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ class Mpv < Formula
   url "https://github.com/mpv-player/mpv/archive/refs/tags/v0.35.1.tar.gz"
   sha256 "41df981b7b84e33a2ef4478aaf81d6f4f5c8b9cd2c0d337ac142fc20b387d1a9"
   license :cannot_represent
-  revision 1
+  revision 2
```
Comment (carlocab) [inline Formula/mpv.rb:7]: I don't think this is necessary.

File: Formula/mujs.rb
Comment (carlocab) [inline Formula/mujs.rb:1]: We can switch the Git clone to a tarball at https://mujs.com/downloads/mujs-1.3.3.tar.gz. It will need a `livecheck` block, though.

File: Formula/mpv.rb (hunk 1 above)
Comment (kiracus) [reply Formula/mpv.rb]: copy from last PR for mujs. remove for now. let's see

File: Formula/mujs.rb [hunk 2]
```diff
@@ -6,6 +6,7 @@ class Mujs < Formula
       tag:      "1.3.3",
       revision: "57e3f01d5f29c5823be725d96284488edf5f8ae1"
   license "ISC"
+  revision 1
```
Comment (carlocab) [inline Formula/mujs.rb:9]:
```suggestion
```
Actually, I don't think we really need this either. It doesn't look like most users really care about the broken `.pc` file -- we can always bump the `revision` later if there are more complaints.

File: Formula/mujs.rb [hunk 3]
```diff
@@ -18,12 +19,14 @@ class Mujs < Formula
...
 
+  depends_on "pkg-config" => :test
+
   on_linux do
     depends_on "readline"
   end
 
   def install
-    system "make", "release"
+    system "make", "prefix=#{prefix}", "release"
```
Comment (carlocab) [inline Formula/mujs.rb:29]:
```suggestion
    system "make", "prefix=#{opt_prefix}", "release"
```
Let's use `opt_prefix` here to use `opt_prefix` references in the `.pc` file. The new `test` will need adjusting.

Comment (kiracus) [reply Formula/mujs.rb]: updated, thanks

File: Formula/mujs.rb (hunk 2 above)
Comment (kiracus) [reply Formula/mujs.rb:9]: I care, also, without a revision here, the solution for this issue is reinstall from source, which is not enabled by default any more.
I rather to fix it now than wait for another mujs, which may happen a fews months later

File: Formula/mujs.rb
Comment (kiracus) [reply Formula/mujs.rb:1]: there is a comment mentioning there are some issue with the `tar.gz` file, which I do not have the fully context.
Also, I prefer to handle only one thing in one PR

**Comment by kiracus** [comment]
hmm, why `pkg-config --cflags mujs` on linux returns `\n` only?

File: Formula/mujs.rb (hunk 2 above)
Comment (carlocab) [reply Formula/mujs.rb:9]: You don't need to reinstall from source if there is no `revision`. You just need to do `brew reinstall mujs`.

**Comment by kiracus** [comment]
ok, in my latest commit, I rollback the `prefix=opt_prefix` to the original change as `prefix=prefix` and it works.
I guess there could be some improvement for this formula, but it is enough to address https://github.com/Homebrew/homebrew-core/issues/126846

please feel free to review. thanks

**Review by carlocab — COMMENTED** [review]
Ok to merge this once we dropped the `revision` bump. You can pull in the changes after merge with `brew update && brew reinstall mujs` (perhaps with a lag time of ~15 minutes to wait for the API to be updated).

**Comment by kiracus** [comment]
I see. thanks. updated

**Review by carlocab — APPROVED** [review]
