### PR TITLE
gammaray: switch to qt layout

### LINKED ISSUE #276948: GammaRay 3.4.0 fails to install to to signature issue
### `brew config` AND `brew doctor` output OR `brew gist-logs <formula>` link

```shell
rknall@M3Work build % brew config
HOMEBREW_VERSION: 5.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac782bcd32ff3fb93fbac38ee5785dd2ccd95bad
Last commit: 3 days ago
Branch: stable
Core tap JSON: 10 Apr 09:19 UTC
Core cask tap JSON: 10 Apr 09:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DOWNLOAD_CONCURRENCY: 22
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 11
Homebrew Ruby: 4.0.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/4.0.2_1/bin/ruby
CPU: 11-core 64-bit arm_lobos
Clang: 21.0.0 build 2100
Git: 2.53.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.3.1-arm64
CLT: 26.3.0.0.1.1771626560
Xcode: 26.4
Metal Toolchain: N/A
Rosetta 2: false



rknall@M3Work build % brew doctor
Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

I am trying to install GammaRay in version 3.4.0 

### What happened (include all command output)?

It fails with a code-signing issue:

```
rknall@M3Work build % brew reinstall GammaRay
==> Fetching downloads for: gammaray
✔︎ Bottle Manifest gammaray (3.4.0)                     Downloaded   95.6KB/ 95.6KB
✔︎ Bottle gammaray (3.4.0)                              Downloaded    5.3MB/  5.3MB
==> Reinstalling gammaray
==> Pouring gammaray--3.4.0.arm64_tahoe.bottle.tar.gz
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/gammaray/3.4.0/GammaRay.app/Contents/MacOS/GammaRayUI:
/opt/homebrew/Cellar/gammaray/3.4.0/GammaRay.app/Contents/MacOS/GammaRayUI: replacing existing signature
/opt/homebrew/Cellar/gammaray/3.4.0/GammaRay.app/Contents/MacOS/GammaRayUI: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /opt/homebrew/Cellar/gammaray/3.4.0/GammaRay.app/Contents/PlugIns/gammaray/3.4
```

### What did you expect to happen?

Gammaray installing without any issues

### Step-by-step reproduction instructions (by running `brew` commands)

run  
```shell
brew install gammaray
```
on a fully update MacOS system

### PR DESCRIPTION
**Pull request by GunniBusch**
-----

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`?
- [x] Is your test running fine `brew test <formula>`?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- [ ] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

-----

## Planned commits
- `gammaray: switch to qt layout`
## Validation summary
- `gammaray`: style: pass, test: pass, audit: pass

This should technically fix #276948

I switched from the .app to qt layout. I tested if everything worked, by debugging some random qt app.
Also I added actual testing.

### CODE REVIEW

**Comment by GunniBusch** [comment]
```

  gammaray
    * Stable: The source URL https://github.com/KDAB/GammaRay/releases/download/v3.4.0/gammaray-3.4.0.tar.gz is not reachable (HTTP status code 502)
  Error: 1 problem in 1 formula detected.
```
  
  Github😩

File: Formula/g/gammaray.rb [hunk 1]
```diff
@@ -46,22 +47,46 @@ class Gammaray < Formula
     end
   end
 
+  # Make rootPath follow symlink to support linked keg.
+  patch :DATA
```
Comment (botantony) [inline Formula/g/gammaray.rb]: Is there an upstream issue? Have you tried to submit the patch first?

Comment (GunniBusch) [reply Formula/g/gammaray.rb]: No, because I thought it is homebrew specific. but I can try and see if they accept.

Comment (GunniBusch) [reply Formula/g/gammaray.rb]: I submitted it https://github.com/KDAB/GammaRay/pull/1126

Should I leave the end patch or should I switch to patch block and rerun ci?

**Review by chenrui333 — APPROVED** [review]
