### PR TITLE
wireshark: install missing headers

### LINKED ISSUE #142184: Wireshark headers are not fully installed (ws_version.h)
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0985dabec8517ab5afda7cfee7d59f1da4ed6ce
Last commit: 8 days ago
Core tap JSON: 13 Sep 08:18 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I want to install the `wireshark` dependency on macOS so my wireshark dissector (https://github.com/apache/pulsar-client-cpp/tree/main/wireshark) can find the necessary headers.

Before the recent updates, the CI workflow ran well. Here is a successful workflow: https://github.com/apache/pulsar-client-cpp/actions/runs/5640216722/job/15276502722

```
==> Pouring wireshark--4.0.6.monterey.bottle.tar.gz
```

```
-- Use WIRESHARK_INCLUDE_PATH: /usr/local/include
```

From the output above, you can see Wireshark 4.0.6 works well.

### What happened (include all command output)?

https://github.com/apache/pulsar-client-cpp/actions/runs/6148375620/job/16681944089

```
-- Cannot find ws_version.h, fallback to find config.h
```

The root cause is the CMakeLists.txt tries to find `ws_version.h` for the `WIRESHARK_VERSION_MAJOR` and `WIRESHARK_VERSION_MINOR` macros. However, the latest wireshark package does not install this header. I just ran `brew install wireshark` locally on my macOS. It installed wireshark 4.1.0 and the headers are:

```
$ ls /opt/homebrew/Cellar/wireshark/4.1.0/include/         
wireshark
$ ls /opt/homebrew/Cellar/wireshark/4.1.0/include/wireshark
capture_opts.h  cli_main.h      extcap.h        file.h          frame_tvbuff.h  ringbuffer.h    sync_pipe.h     wiretap
cfile.h         epan            extcap_parser.h fileset.h       globals.h       sharkd.h        text2pcap.h     wsutil
```

With 4.0.6, the `ws_version.h` should be installed under the `wireshark` 

### What did you expect to happen?

The `ws_version.h` should be installed. In wireshark, it's a `ws_version.h.in` file and will be generated into `ws_version.h` under the CMake build directory.

```cmake
configure_file(${CMAKE_SOURCE_DIR}/ws_version.h.in ${CMAKE_BINARY_DIR}/ws_version.h)
```

https://github.com/wireshark/wireshark/blob/35916f6531aa0f89e0d1c90dc2ce76e44bde3148/CMakeLists.txt#L1819

It seems that this `ws_version.h` is not installed by the Homebrew. I just checked the `wireshark.rb` and found it only installs the headers in the subdirectories of `include/` directory. However, some headers under the `build/` directory should also be installed. But I'm not sure why 4.0.6 works.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See the workflow here: https://github.com/apache/pulsar-client-cpp/blob/787bfd0e450427ff753f6a54b63f7fe18a684529/.github/workflows/ci-pr-validation.yaml#L50-L57
```

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes https://github.com/Homebrew/homebrew-core/issues/142184

The `config.h` and `ws_version.h` are generated in the CMake build directory but they are not added. The `include/` and `wsutil/wmem` directories are also ignored. It would make the wireshark dissector failed to build without these headers.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

In addition to the tests above, I installed the modified `wireshark.rb` locally and it works well with my wireshark dissector now.

### CODE REVIEW

**Comment by Bo98** [comment]
Hmm this header stuff is a mess.

Does adding `cmake --install build --component Development` instead of all this manual stuff work?

**Comment by BewareMyPower** [comment]
```
An exception occurred within a child process:
  BuildError: Failed executing: /opt/homebrew/Cellar/wireshark/4.1.0_1/bin/randpkt -b 100 -c 2 capture.pcap
/opt/homebrew/Library/Homebrew/formula.rb:2733:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2669:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2669:in `system'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/w/wireshark.rb:87:in `block in <class:Wireshark>'
/opt/homebrew/Library/Homebrew/formula.rb:2493:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2492:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:1054:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2491:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2784:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2485:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

Though it works with my dissector, `brew test wireshark` failed. Not sure if it's caused by my local env.

```bash
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
   M Formula/w/wireshark.rb
```

The `brew doctor` command shows no error except the uncommitted file.

**Comment by Bo98** [comment]
I think `--component Development` only installs the develpoment stuff perhaps? So might need to be have that in addition to the existing `cmake --install` without the `--component`, rather than replacing the original `cmake --install` like you've done here.

**Comment by BewareMyPower** [comment]
Yes, I also realized it just now and the test passed locally. Thanks for your help!

**Comment by gromgit** [comment]
Since the whole point of this PR is to fix user builds, I think building a simple program in the `test` block would be quite appropriate.

**Comment by BewareMyPower** [comment]
Building a wireshark dissector is not very trivial.

As you can see in https://github.com/Homebrew/homebrew-core/issues/142184#issuecomment-1717326567, it requires
- The installation of a C++ compiler, e.g. we need to find `clang++` or `g++` in a binary path
- The include and library paths of `glib`
- `pkg-config`, it's not necessary, but it would be hard to find the `glib` libraries without `pkg-config`

**Comment by BewareMyPower** [comment]
Okay, I will try it.

**Comment by BewareMyPower** [comment]
@SMillerDev Test is added, PTAL again.

File: Formula/w/wireshark.rb [hunk 1]
```diff
@@ -94,6 +85,19 @@ def caveats
...
+
+      int main() {
+        printf("%d.%d.%d", WIRESHARK_VERSION_MAJOR, WIRESHARK_VERSION_MINOR,
+               WIRESHARK_VERSION_MICRO);
+        return 0;
+      }
+    EOS
+    system ENV.cxx, "-std=c++11", "test.cpp", "-I#{include}/wireshark", "-o", "test"
+    output = shell_output("./test")
+    assert_equal version.to_s, output
```
Comment (SMillerDev) [inline Formula/w/wireshark.rb:100]: Let's give it some space
```suggestion
    system ENV.cxx, "-std=c++11", "test.cpp", "-I#{include}/wireshark", "-o", "test"
    assert_equal version.to_s, shell_output("./test")

```

**Comment by SMillerDev** [comment]
@BewareMyPower can you squash all your commits into a single `wireshark: install missing headers`?

**Comment by BewareMyPower** [comment]
I've squashed all commits and rebased to the latest master branch. PTAL.

**Review by SMillerDev — APPROVED** [review]
Thanks @BewareMyPower  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉
