### PR TITLE
watchman: fix broken shebangs

### LINKED ISSUE #210978: Scripts provided by `watchman` have broken shebangs
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.4.24-181-g7521207
ORIGIN: https://github.com/Homebrew/brew
HEAD: 752120772c8376936232b3efa7b7d566d1579942
Last commit: 3 hours ago
Branch: master
Core tap JSON: 14 Mar 22:43 UTC
Core cask tap HEAD: 6f808ae6dceb81decae4ae8debf87ed577d1ed6b
Core cask tap last commit: 3 hours ago
Core cask tap JSON: 14 Mar 22:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.48.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.3.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false

Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to use scripts with the `watchman` formula, such as `watchman-make`.

### What happened (include all command output)?

```
❯ watchman-make --help
exec: Failed to execute process '/opt/homebrew/bin/watchman-make': The file specified the interpreter 'python', which is not an executable command.
```

```
❯ head -n 5 /opt/homebrew/bin/watchman-make
#!python
import argparse
import os
import subprocess
import sys
```

I've tested this on two computers.

### What did you expect to happen?

The `watchman-make` help text to appear.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install watchman
watchman-make --help
```

### PR DESCRIPTION
**Pull request by botantony**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Closes #210978

### CODE REVIEW

File: Formula/w/watchman.rb [hunk 1]
```diff
@@ -66,6 +68,10 @@ def install
     bin.install (path/"bin").children
     lib.install (path/"lib").children
     rm_r(path)
+
+    %w[make replicate-subscription wait].each do |file|
+      rewrite_shebang detected_python_shebang, "#{bin}/watchman-#{file}"
+    end
```
Comment (carlocab) [inline Formula/w/watchman.rb:74]: We can make this simpler:
```suggestion
    rewrite_shebang detected_python_shebang, *bin.children
```

**Review by carlocab — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
