### PR TITLE
hdf5: use CMake

### LINKED ISSUE #157078: HDF5 incomplete without building with CMake
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs hdf5
Error: No logs.

# but should be irrelevant since the installation is successful but incomplete (please read further)
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

In CMake: 
`find_package(HDF5 CONFIG ... )`

To find HDF5 in my tool/lib.

### What happened (include all command output)?

Fail.

```
[cmake] CMake Error at cmake/cmake_findExternalLibs.cmake:172 (find_package):
[cmake]   Could not find a package configuration file provided by "HDF5" with any of
[cmake]   the following names:
[cmake] 
[cmake]     HDF5Config.cmake
[cmake]     hdf5-config.cmake
```

### What did you expect to happen?

Find HDF5 successfully.

Requirement would be the config files that hdf5 comes with if you built it with CMake.

https://forum.hdfgroup.org/t/can-we-retire-the-autotools/10362
Looks like many people are in favour of retiring autotools.

Also ".pc" files were requested before, which are only available with CMake:
https://github.com/Homebrew/homebrew-core/issues/61490
And one can IMHO not say anymore that autotools is "the recommended" way (rather the other way round).
(Especially since the then-opened issue was one of the first ever and has not been addressed in their autotools build in almost 4 years https://github.com/HDFGroup/hdf5/issues/8 )

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Something like this (but the problem should obvious by just inspecting what you are installing during the hdf5 build which uses autotools).

brew install hdf5

echo "find_package(HDF5 CONFIG)" >> script.cmake

cmake -P script.cmake
```

### PR DESCRIPTION
**Pull request by jpfeuffer**
closes #157329 (supersedes it)
closes #157078 

tagging @SMillerDev 

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

File: Formula/h/hdf5.rb [hunk 1]
```diff
@@ -43,32 +42,43 @@ def install
...
+        build/src/libhdf5.settings
+        build/CMakeFiles/h5c++
+        build/CMakeFiles/h5hlc++
+      ]
+    else
+      %w[
+        build/CMakeFiles/h5c++
+        build/CMakeFiles/h5hlc++
+      ]
+    end
```
Comment (SMillerDev) [inline Formula/h/hdf5.rb:75]:
```suggestion
    inreplace_cxx_files = %w[
      build/CMakeFiles/h5c++
      build/CMakeFiles/h5hlc++
    ]
    inreplace_cxx_files << "build/src/libhdf5.settings" if OS.linux?
```

File: Formula/h/hdf5.rb [hunk 2]
```diff
@@ -43,32 +42,43 @@ def install
...
-      src/Makefile
+    ENV["libaec_DIR"] = Formula["libaec"].opt_prefix.to_s
+
+    system "cmake",
+      "-S", ".",
+      "-B", "build",
+      "-DHDF5_BUILD_FORTRAN:BOOL=ON",
+      "-DHDF5_BUILD_CPP_LIB:BOOL=ON",
+      "-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON",
+      *std_cmake_args
```
Comment (SMillerDev) [inline Formula/h/hdf5.rb:53]:
```suggestion
    args = %w[
      -DHDF5_BUILD_FORTRAN:BOOL=ON
      -DHDF5_BUILD_CPP_LIB:BOOL=ON
      -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON
    ]
    system "cmake", "-S", ".", "-B", "build", *args, *std_cmake_args
```

File: Formula/h/hdf5.rb [hunk 3]
```diff
@@ -113,5 +123,8 @@ def install
     EOS
     system "#{bin}/h5fc", "test.f90"
     assert_equal version.to_s, shell_output("./a.out").chomp
+
+    # Make sure that it was built with SZIP/libaec
+    system("#{bin}/h5cc -showconfig | grep -q -e 'I/O filters' -e 'DECODE'")
```
Comment (SMillerDev) [inline Formula/h/hdf5.rb:128]:
```suggestion
    config = shell_output("#{bin}/h5cc -showconfig")
    assert_match  "I/O filters", config
    assert_match  "DECODE", config
```

File: Formula/h/hdf5.rb [hunk 4]
```diff
@@ -113,5 +123,8 @@ def install
     EOS
     system "#{bin}/h5fc", "test.f90"
```
Comment (SMillerDev) [inline Formula/h/hdf5.rb:124]:
```suggestion
    system bin/"h5fc", "test.f90"
```

File: Formula/h/hdf5.rb (hunk 3 above)
Comment (jpfeuffer) [reply Formula/h/hdf5.rb:128]: Regarding this: DECODE needs to be in the same line as I/O filters, therefore my initial approach of double grep. It feels like this would achieve sth different.
I'm happy to incorporate another suggestion though!

Comment (SMillerDev) [reply Formula/h/hdf5.rb:120]: how about using the regex option of `assert_match` then?

Comment (SMillerDev) [reply Formula/h/hdf5.rb:120]: Looks good!

File: Formula/h/hdf5.rb [hunk 5]
```diff
@@ -111,7 +113,11 @@ def install
       write (*,"(I0,'.',I0,'.',I0)") major, minor, rel
       end
     EOS
-    system "#{bin}/h5fc", "test.f90"
+    system bin/"h5fc", "test.f90"
     assert_equal version.to_s, shell_output("./a.out").chomp
+
+    # Make sure that it was built with SZIP/libaec
+    config = shell_output("#{bin}/h5cc -showconfig")
+    assert_match /I\/O filters.*DECODE/, config
```
Comment (SMillerDev) [inline Formula/h/hdf5.rb:121]:
```suggestion
    assert_match %r{I\/O filters.*DECODE}, config
```

**Comment by jpfeuffer** [comment]
I'm not an expert but the dep failures seem unrelated.

**Comment by ZhongRuoyu** [comment]
Yes, failures seem unrelated; see also: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+shmget

**Comment by ZhongRuoyu** [comment]
> Does it really need linux self-hosted runners? Slightly more than 1H15 on it seems pretty short and could probably fit within 6H of GitHub runners, right?

I think it did time out while testing dependents in #140211.

**Comment by jpfeuffer** [comment]
Speaking of which: we could add the changes for the hdf5-mpi formula as well. Could benefit from the Cmake- and pkg-config files for easier discoverability as well.
I didn't know about that formula and I'm personally not using it, so I'm not sure if it needs special treatment.

**Comment by SMillerDev** [comment]
Let's merge this, and then please make a new PR for `hdf5-mpi` @jpfeuffer

**Review by SMillerDev — APPROVED** [review]

**Comment by eli-schwartz** [comment]
This is causing universal CI failures for attempting to detect and compile against hdf5 in the Meson CI.

hdf5 cannot and must not *ever* be built with cmake. Using broken build files that upstream doesn't seriously support, just to make cmake's find_package() detect hdf5, is not a real solution. There's a reason that every linux distro I'm aware of builds hdf5 with autotools -- sometimes with comments about how the cmake support is utterly broken, sometimes without comment.

**Comment by jpfeuffer** [comment]
Can't you just search in MODULE mode then? No one forces someone to use those config files.
And how about raising the problems at the HDF5 repository (potentially repeatedly) until they are fixed. IMHO ignoring the problem is also not a solution.
The config files work great for us and without config files you will never have easy access to compile flags and some more modern CMake features that depend on more detailed descriptions of the targets.

**Comment by jpfeuffer** [comment]
Ok it looks like you're saying the build itself is broken with CMake. That is hard for me to judge and I would be interested in some of the bug reports of the distros.
Your specific linked case "just" seems to have problems with the c++ standard version.
But I think most importantly this should be posted on a HDF5 issue tracker. Ignoring it won't make it go away.
There is already a forum thread on HDF5 where people are discussing dropping Autotools support.
https://forum.hdfgroup.org/t/can-we-retire-the-autotools/10362/31

**Comment by blawrence-ont** [comment]
It appears that this change has broken cmake's `FindHDF5` module: https://github.com/Kitware/CMake/blob/master/Modules/FindHDF5.cmake

The module works by calling `h5cc` with `-show` to extract the libraries it needs to link to. Previous versions of `h5cc` handle `-show` correctly:
```
% h5cc -show 
clang -I/opt/homebrew/opt/libaec/include -L/opt/homebrew/Cellar/hdf5/1.14.3/lib /opt/homebrew/Cellar/hdf5/1.14.3/lib/libhdf5_hl.a /opt/homebrew/Cellar/hdf5/1.14.3/lib/libhdf5.a -L/opt/homebrew/opt/libaec/lib -lsz -lz -ldl -lm
```

However with these changes `h5cc` now returns:
```
% h5cc -show 
/opt/homebrew/h5cc
dir is /opt/homebrew
clang: error: unknown argument: '-show'
```
This appears to be because the script is now a very thin wrapper missing a lot of functionality: compare the arg handling in the version that used to be provided https://github.com/HDFGroup/hdf5/blob/develop/bin/h5cc.in with the version now provided https://github.com/HDFGroup/hdf5/blob/develop/config/cmake/libh5cc.in.

Also it surprises me that this change has more than tripled the size of the package from 21.4MB to 77.7MB according to `brew info hdf5`.

**Comment by jpfeuffer** [comment]
Ok sorry, let's revert. Unfortunately I do not have the resources to debug this.
The idea was actually not to rely on the hand-written, externally updated FindHDF5 module that also lacks information about compiler options, runtime dependencies and shared vs static targets distinction.
But I think this is out of reach.

**Comment by jpfeuffer** [comment]
I will forward this to the HDF forum though.

**Comment by eli-schwartz** [comment]
> Can't you just search in "MODULE" mode then? No one forces someone to use those config files.

Sure.

Just tell me how to do that from an autotools Makefile and I will get right on that immediately.

Considering that hdf5 has been pretty apathetic about delivering pkg-config files even after delivering them for cmake, there's lots of code out in the wild that uses h5cc -show.

> Your specific linked case "just" seems to have problems with the c++ standard version and a (probably) missing -lhdf5 in your linker command line.

And at minimum, the missing -lhdf5 is because of the well known problem that cmake's version of h5cc heard about the idea of "compatibility" and said "what's that, some kind of boring Linux thing?" and implemented the absolute minimum scaffolding needed to be invoked internally by their cmake config file, and absolutely nothing for existing users.

If for no other reason, distributors have to ship an autotools build because they need to support existing software that relies on h5cc working. That software cannot use pkg-config because distributors ship an autotools build. This recursive logic will be fixed exactly no sooner than whenever upstream hdf5 accepts that the request to ship a pkg-config file for autotools isn't a request that should be ignored and closed every time someone offers one, then left to rot forever.

Admittedly it was some time ago that I was aware of the general brokenness of the cmake build. It is possible that at the time the cmake build was still windows-only despite advertising itself for Linux use, but I don't remember. Maybe it's gotten better. Given the overall disaster that is hdf5 and build systems, I'm not hopeful. They responded to the issue of h5cc being broken with "we have documented in the release.txt that h5cc has changed. Closing this bug report as solved".

**Comment by eli-schwartz** [comment]
> Also it surprises me that this change has more than tripled the size of the package from 21.4MB to 77.7MB according to `brew info hdf5`.

This is because, even for a project notable for lacking expertise at build systems, they have orders of magnitude less expertise in cmake than they have in autotools.

But some of it is just cmake's fault, because CMake Is That Way™.
