### PR TITLE
pgpool-ii: add memcached support and service block

### LINKED ISSUE #133692: Add memcached support to pgpool-ii
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.0.22
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9d01e1deafca35f30b709b5f6a031faaff9642ec
Last commit: 2 days ago
Core tap JSON: 14 Jun 16:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install and run pgpool-ii 

### What happened (include all command output)?

The installation succeeded, but without memcached support.   By default, pgpool will use Mac OS's shared memory, but the default shared memory size much lower than pgpool requires, giving the error 'Shared memory creation failed with error "Invalid argument"'.  Apple is making it increasingly difficult to modify shared memory.  pgpool can use memcached instead, but this must be compiled in when it is built.

The formula has:
```ruby
  def install
    system "./configure", "--disable-dependency-tracking", "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}"
    system "make", "install"
  end
```

### What did you expect to happen?

The formula should have:
```
  def install
    system "./configure", "--disable-dependency-tracking", "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}", "--with-memcached=path"
    system "make", "install"
  end
  ```
  Where "path" is wherever the libmemcached cask installs its files.  See https://www.pgpool.net/docs/pgpool-II-3.3.3/doc/pgpool-en.html#install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install pgpool-ii
$ (pgpool default setup)
$ pgpool -n
Error: Shared memory creation failed with error "Invalid argument"
$ (pgpool setup to use memcached)
$ pgpool -n 
Error: WARNING:  failed to connect to memcached, memcached support is not enabled
```

### PR DESCRIPTION
**Pull request by branchv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

---

Fixes #133692

### CODE REVIEW

File: Formula/pgpool-ii.rb [hunk 1]
```diff
@@ -32,13 +33,35 @@ class PgpoolIi < Formula
...
-    system "./configure", "--disable-dependency-tracking", "--prefix=#{prefix}",
-                          "--sysconfdir=#{etc}"
+    system "./configure", *std_configure_args,
+                          "--sysconfdir=#{etc}",
+                          "--with-memcached=#{Formula["libmemcached"].opt_include}"
     system "make", "install"
+
+    # Install conf file with low enough memory limits for default `memqcache_method = 'shmem'`
+    etc.install etc/"pgpool.conf.sample" => "pgpool.conf"
+    inreplace etc/"pgpool.conf" do |s|
```
Comment (carlocab) [inline Formula/pgpool-ii.rb:43]: Let's `inreplace` the sample first before installing it to avoid tampering with the user's `pgpool.conf`.

Comment (branchvincent) [reply Formula/pgpool-ii.rb]: good idea, done

**Review by carlocab — APPROVED** [review]
