### PR TITLE
ruby: update openssl gem for OpenSSL 3.6+

### LINKED ISSUE #247043: Ruby cannot connect via SSL
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config ; echo ; brew doctor
HOMEBREW_VERSION: 4.6.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 999134536e623073ea9b2a8954eeea5898137239
Last commit: 3 days ago
Branch: stable
Core tap JSON: 06 Oct 12:37 UTC
Core cask tap JSON: 06 Oct 12:37 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BUNDLE_USER_CACHE: /Users/brian/.cache/bundle
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Applications/MacVim.app/Contents/bin/vim
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.4.5 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 17.0.0 build 1700
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.6.1-x86_64
CLT: 16.4.0.0.1.1747106510
Xcode: N/A

Your system is ready to brew.


Also:


$ brew config ; echo ; brew doctor
HOMEBREW_VERSION: 4.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 700d67a85e0129ab8a893ff69246943479e33df1
Last commit: 3 months ago
Branch: stable
Core tap JSON: 06 Oct 15:15 UTC
Core cask tap JSON: 06 Oct 15:15 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BUNDLE_USER_CACHE: /Users/bcg65/.cache/bundle
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/bcg65/Applications/MacVim.app/Contents/bin/vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.4.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.4/bin/ruby
CPU: deca-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.7.1-arm64
CLT: 26.0.0.0.1.1757719676
Xcode: 26.0.1
Rosetta 2: false

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  nomad
  consul
  vault
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

I have some ruby scripts that check web sites, and I started getting the following error:

```
/usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/protocol.rb:46:in 'OpenSSL::SSL::SSLSocket#connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=[2600:1408:ec00:36::1736:7f31]:443 state=error: certificate verify failed (unable to get certificate CRL) (OpenSSL::SSL::SSLError)
```

I've tried all of the following (along with some personal/work domains):

* example.org
* google.com
* ruby-lang.org
* brew.sh
* cloudflare.com

I noticed this on my Intel MacBook first.  It stopped working on my M1 MacBook after a `brew upgrade` that changed the following packages:  (I am unsure when it stopped on my Intel, as there was notable time between running any brew commands and using my script.)

```
yq 4.45.4 -> 4.47.2
pinentry 1.3.1_1 -> 1.3.2
pycparser 2.22_1 -> 2.23
cryptography 45.0.5 -> 46.0.2
python@3.13 3.13.5 -> 3.13.7
libunistring 1.3 -> 1.4
cffi 1.17.1_1 -> 2.0.0
readline 8.3 -> 8.3.1
utf8proc 2.10.0 -> 2.11.0
awscli 2.27.49 -> 2.31.8
sqlite 3.50.2 -> 3.50.4
libnghttp2 1.66.0 -> 1.67.1
bash 5.3 -> 5.3.3
libgcrypt 1.11.1 -> 1.11.2
openssl@3 3.5.1 -> 3.6.0
ca-certificates 2025-05-20 -> 2025-09-09
gettext 0.25.1 -> 0.26
pcre2 10.45 -> 10.46
direnv 2.37.0 -> 2.37.1
lesspipe 2.18 -> 2.20
unbound 1.23.0 -> 1.24.0
p11-kit 0.25.5 -> 0.25.10
ruby 3.4.4 -> 3.4.6
gnutls 3.8.9 -> 3.8.10
```

### What happened (include all command output)?

Comparing using `Net::HTTP` to connect to example.com with macOS Ruby and Homebrew ruby:

```
$ /usr/bin/ruby -r net/http -e 'Net::HTTP.get URI "https://example.com"'
$ /usr/local/bin/ruby -r net/http -e 'Net::HTTP.get URI "https://example.com"' 
/usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/protocol.rb:46:in 'OpenSSL::SSL::SSLSocket#connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=[2600:1408:ec00:36::1736:7f31]:443 state=error: certificate verify failed (unable to get certificate CRL) (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/protocol.rb:46:in 'Net::Protocol#ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1736:in 'Net::HTTP#connect'
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1636:in 'Net::HTTP#do_start'
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1625:in 'Net::HTTP#start'
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1064:in 'Net::HTTP.start'
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:824:in 'Net::HTTP.get_response'
	from /usr/local/Cellar/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:805:in 'Net::HTTP.get'
	from -e:1:in '<main>'
$
```

However, Homebrew openssl still seems to connect fine:

```
$ /usr/local/bin/openssl s_client -connect example.com:443 < /dev/null
Connecting to 2600:1406:bc00:53::b81e:94ce
CONNECTED(00000005)
depth=2 C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G3
verify return:1
depth=1 C=US, O=DigiCert Inc, CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1
verify return:1
depth=0 C=US, ST=California, L=Los Angeles, O=Internet Corporation for Assigned Names and Numbers, CN=*.example.com
verify return:1
---
Certificate chain
 0 s:C=US, ST=California, L=Los Angeles, O=Internet Corporation for Assigned Names and Numbers, CN=*.example.com
   i:C=US, O=DigiCert Inc, CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1
   a:PKEY: EC, (prime256v1); sigalg: ecdsa-with-SHA384
   v:NotBefore: Jan 15 00:00:00 2025 GMT; NotAfter: Jan 15 23:59:59 2026 GMT
 1 s:C=US, O=DigiCert Inc, CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1
   i:C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G3
   a:PKEY: EC, (secp384r1); sigalg: ecdsa-with-SHA384
   v:NotBefore: Apr 14 00:00:00 2021 GMT; NotAfter: Apr 13 23:59:59 2031 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFmzCCBSGgAwIBAgIQCtiTuvposLf7ekBPBuyvmjAKBggqhkjOPQQDAzBZMQsw
CQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypEaWdp
Q2VydCBHbG9iYWwgRzMgVExTIEVDQyBTSEEzODQgMjAyMCBDQTEwHhcNMjUwMTE1
MDAwMDAwWhcNMjYwMTE1MjM1OTU5WjCBjjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
CkNhbGlmb3JuaWExFDASBgNVBAcTC0xvcyBBbmdlbGVzMTwwOgYDVQQKEzNJbnRl
cm5ldCBDb3Jwb3JhdGlvbiBmb3IgQXNzaWduZWQgTmFtZXMgYW5kIE51bWJlcnMx
FjAUBgNVBAMMDSouZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AASaSJeELWFsCMlqFKDIOIDmAMCH+plXDhsA4tiHklfnCPs8XrDThCg3wSQRjtMg
cXS9k49OCQPOAjuw5GZzz6/uo4IDkzCCA48wHwYDVR0jBBgwFoAUiiPrnmvX+Tdd
+W0hOXaaoWfeEKgwHQYDVR0OBBYEFPDBajIN7NrH6o/NDW0ZElnRvnLtMCUGA1Ud
EQQeMByCDSouZXhhbXBsZS5jb22CC2V4YW1wbGUuY29tMD4GA1UdIAQ3MDUwMwYG
Z4EMAQICMCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQ
UzAOBgNVHQ8BAf8EBAMCA4gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MIGfBgNVHR8EgZcwgZQwSKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9E
aWdpQ2VydEdsb2JhbEczVExTRUNDU0hBMzg0MjAyMENBMS0yLmNybDBIoEagRIZC
aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzNUTFNFQ0NT
SEEzODQyMDIwQ0ExLTIuY3JsMIGHBggrBgEFBQcBAQR7MHkwJAYIKwYBBQUHMAGG
GGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBRBggrBgEFBQcwAoZFaHR0cDovL2Nh
Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzNUTFNFQ0NTSEEzODQy
MDIwQ0ExLTIuY3J0MAwGA1UdEwEB/wQCMAAwggF7BgorBgEEAdZ5AgQCBIIBawSC
AWcBZQB0AA5XlLzzrqk+MxssmQez95Dfm8I9cTIl3SGpJaxhxU4hAAABlGd6v8cA
AAQDAEUwQwIfJBcPWkx80ik7uLYW6OGvNYvJ4NmOR2RXc9uviFPH6QIgUtuuUenH
IT5UNWJffBBRq31tUGi7ZDTSrrM0f4z1Va4AdQBkEcRspBLsp4kcogIuALyrTygH
1B41J6vq/tUDyX3N8AAAAZRnesAFAAAEAwBGMEQCIHCu6NgHhV1Qvif/G7BHq7ci
MGH8jdch/xy4LzrYlesXAiByMFMvDhGg4sYm1MsrDGVedcwpE4eN0RuZcFGmWxwJ
cgB2AEmcm2neHXzs/DbezYdkprhbrwqHgBnRVVL76esp3fjDAAABlGd6wBkAAAQD
AEcwRQIgaFh67yEQ2lwgm3X16n2iWjEQFII2b2fpONtBVibZVWwCIQD5psqjXDYs
IEb1hyh0S8bBN3O4u2sA9zisKIlYjZg8wjAKBggqhkjOPQQDAwNoADBlAjEA+aaC
RlPbb+VY+u4avPyaG7fvUDJqN8KwlrXD4XptT7QL+D03+BA/FUEo3dD1iz37AjBk
Y3jhsuLAW7pWsDbtX/Qwxp6kNsK4jh1/RjvV/260sxQwM/GM7t0+T0uP2L+Y12U=
-----END CERTIFICATE-----
subject=C=US, ST=California, L=Los Angeles, O=Internet Corporation for Assigned Names and Numbers, CN=*.example.com
issuer=C=US, O=DigiCert Inc, CN=DigiCert Global G3 TLS ECC SHA384 2020 CA1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ecdsa_secp256r1_sha256
Peer Temp Key: X25519, 253 bits
---
SSL handshake has read 2721 bytes and written 1622 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Protocol: TLSv1.3
Server public key is 256 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
DONE
```

### What did you expect to happen?

Expected to be able to connect via SSL with no errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Update to latest ruby, ca-certificates, and openssl (among others) via `brew upgrade`
2. Run `ruby -r net/http -e 'Net::HTTP.get URI "https://example.com"' ; echo $?`
3. Expect output to simply be `0` (successful exit)
4. Actually get exit code 1 and "certificate verify failed (unable to get certificate CRL) (OpenSSL::SSL::SSLError)" error.
```

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Mostly copying logic from `ruby@3.0`. Likely need similar workarounds for other Ruby 

Fixes #247043

### CODE REVIEW

**Review by daeho-ro — APPROVED** [review]

File: Formula/r/ruby.rb [hunk 1]
```diff
@@ -22,6 +23,12 @@ class Ruby < Formula
         regex(/href=.*?rubygems[._-]v?(\d+(?:\.\d+)+)\.t/i)
       end
     end
+
+    # Update the bundled openssl gem for compatibility with OpenSSL 3.6+
+    resource "openssl" do
+      url "https://github.com/ruby/openssl/archive/refs/tags/v3.3.1.tar.gz"
+      sha256 "ca9b8f5940153e67b0d5e7e075ecd64b9d28b9f9b2f2c9f0748c1538734dfe10"
+    end
```
Comment (carlocab) [inline Formula/r/ruby.rb:31]: Might be worth adding a an SSL test so we catch this on future OpenSSL bumps.
