### PR TITLE
onnxruntime: apply Fedora workaround to fix using `onnx` formula

### LINKED ISSUE #245956: ONNX emits lots of warnings like "Schema error: Trying to register schema with name ... from file ..., but it is already registered from file ..."
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs onnx
Error: No logs.
$ brew gist-logs onnxruntime
Error: No logs.
$ brew config
HOMEBREW_VERSION: 4.6.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 21c60eb773618f039434d923d2522120c4df56ea
Last commit: 5 days ago
Branch: stable
Core tap JSON: 25 Sep 12:01 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.4.6 => /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.6/bin/ruby
CPU: octa-core 64-bit tigerlake
Clang: 21.1.1
Git: 2.51.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 8.5.0 => /bin/curl
Kernel: Linux 6.8.0-79-generic x86_64 GNU/Linux
OS: Ubuntu 24.04.3 LTS (noble)
Host glibc: 2.39
Host libstdc++: 6.0.33
/usr/bin/gcc: 13.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@12: N/A
gcc: 15.1.0
xorg: N/A
$ brew doctor
Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

Trying to use ONNX via ONNX Runtime in C++.

## Install `onnxruntime` from Homebrew

```sh
brew install onnxruntime
```

This also installs `onnx` since `onnxruntime` depends on `onnx`.

## Export an ONNX model using PyTorch

```python
import torch
from torch import nn

model = nn.Linear(2, 1, bias=False)

with torch.no_grad():
    model.weight.copy_(torch.tensor([1., 1.]))

torch.onnx.export(
    model,
    (torch.randn(1, 2),),
    'model.onnx',
    input_names=['input'],
    output_names=['output'],
    dynamo=True,
)
```

`model.onnx` will be saved under the current directory.

## Perform inference on the exported model using ONNX Runtime in C++

Create `CMakeLists.txt` with the following content:

```cmake
cmake_minimum_required(VERSION 3.16.0)

project(example LANGUAGES CXX)

find_package(onnxruntime CONFIG REQUIRED)

add_executable(example main.cpp)
target_compile_features(example PRIVATE cxx_std_17)
target_link_libraries(example PRIVATE onnxruntime::onnxruntime)
```

Create `main.cpp` with the following content:

```cpp
#include <cstdio>
#include <cstdint>
#include <vector>

#include <onnxruntime_cxx_api.h>

int main() {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "example");

    const char *modelPath = "/path/to/model.onnx"; // Replace with the actual path to model.onnx exported in the previous step

    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

    Ort::Session session(env, modelPath, sessionOptions);

    const char *inputNames[] = {"input"};
    const char *outputNames[] = {"output"};

    std::vector<float> inputData{1.f, 2.f};

    std::vector<int64_t> inputShape{1, 2};

    Ort::MemoryInfo memInfo = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

    Ort::Value inputTensor = Ort::Value::CreateTensor<float>(
        memInfo,
        inputData.data(),
        inputData.size(),
        inputShape.data(),
        inputShape.size()
    );

    Ort::RunOptions runOptions;

    std::vector<Ort::Value> outputTensors = session.Run(
        runOptions,
        inputNames,
        &inputTensor,
        1,
        outputNames,
        1
    );

    float *outputData = outputTensors[0].GetTensorMutableData<float>();

    printf("%f\n", outputData[0]);

    return 0;
}
```

Remember to replace `/path/to/model.onnx` with the actual path to `model.onnx` exported in the previous step.

Build the project with CMake:

```sh
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```

Run the executable:

```sh
./example
```

## Expected behavior

The executable should cleanly output the inference result `3.000000`.

## Actual Behavior

A lot of warnings are emitted:

```plaintext
Schema error: Trying to register schema with name Abs (domain:  version: 1) from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/math/old.cc line 2729, but it is already registered from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/math/old.cc line 2729

Schema error: Trying to register schema with name Add (domain:  version: 1) from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/math/old.cc line 2627, but it is already registered from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/math/old.cc line 2627

Schema error: Trying to register schema with name And (domain:  version: 1) from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/logical/old.cc line 132, but it is already registered from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/logical/old.cc line 132

Schema error: Trying to register schema with name ArgMax (domain:  version: 1) from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/reduction/old.cc line 357, but it is already registered from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/reduction/old.cc line 357

Schema error: Trying to register schema with name ArgMin (domain:  version: 1) from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/reduction/old.cc line 359, but it is already registered from file /var/tmp/onnx-20250914-34576-wgsi1h/onnx-1.17.0/onnx/defs/reduction/old.cc line 359

[...]

3.000000
```

I confirmed that manually building onnxruntime from source does not emit these warnings.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# See above
```

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #245956

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

File: Formula/o/onnxruntime.rb [hunk 1]
```diff
@@ -58,9 +58,20 @@ class Onnxruntime < Formula
     end
   end
 
-  # Workaround for Abseil >= 20250814.0 which removed absl::low_level_hash[^1].
-  # Upstream only supports using vendored deps which we bypass.
-  # [^1]: https://github.com/abseil/abseil-cpp/commit/2ea5334068f11664a71d1d9dfb9a475482fa05f5
+  # Workaround for Abseil >= 20250814.0 which removed absl::low_level_hash.
+  # Issue ref: https://github.com/microsoft/onnxruntime/issues/25815
```
Comment (chenrui333) [inline Formula/o/onnxruntime.rb:62]: - https://github.com/microsoft/onnxruntime/issues/25815
