### PR TITLE
picotool: fix HEAD build

### LINKED ISSUE #226759: picotool version 2.1.1 does not provide the expected features (inconsistency of homebrew vs GitHub release)
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Nothing suspicious related to this issue — all good.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am trying to use the `picotool` installed from homebrew to build all [pico-examples](https://github.com/raspberrypi/pico-examples) for the RP2350 chip used in Raspberry Pico 2 boards (`export PICO_PLATFORM="rp2350"`).

Homebrew `picotool` claims to be version 2.1.1:

```
picotool v2.1.1 (Darwin, AppleClang-16.0.0.16000026, Release)
```
(output of `picotool version` installed from homebrew)

Note that the RP2350 chip takes advantage of a couple more recent features integrated into the `picotool`.

### What happened (include all command output)?

The homebrew installation of `picotool`, despite claiming to be version 2.1.1, does not support the **full feature set** of that version as it is available on the respective `picotool` GitHub release page: https://github.com/raspberrypi/picotool/releases

In particular, the feature `picotool seal ...` is not supported (there may be others). Try and run `picotool help seal` with the homebrew installation, which produces an error that the `seal` subcommand is not known. This means that `pico-examples` cannot be (fully) compiled for the new RP2350 chip, unless one does a manual build and install of `picotool` which has some pitfalls in its own right due to cmake quirkiness.

The homebrew formula seems to obtain its 2.1.1 release via the link: https://github.com/raspberrypi/picotool/archive/refs/tags/2.1.1.tar.gz

(See respective formula at time of writing: https://github.com/Homebrew/homebrew-core/blob/2caa6d1734f371ccc56f3f8724878db49b9dabe2/Formula/p/picotool.rb)

I suspect that the link points to something that is currently not quite up to date, per current 2.1.1 release of `picotool` on https://github.com/raspberrypi/picotool/releases.

Thanks very much for the formula author(s) to look into this and bump the `.tar.gz` to the actualy 2.1.1 release.

### What did you expect to happen?

That `picotool` from homebrew will support all features of the 2.1.1 release per GitHub release: https://github.com/raspberrypi/picotool/releases. E.g., if I do a custom build of 2.1.1 from the [picotool release page](https://github.com/raspberrypi/picotool/releases), we ought not see any different to the homebrew installation of `picotool`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install picotool
picotool help seal

# This ought produce the abovementioned error.
```

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Fix HEAD build, which includes vendored mbedtls for signing support. Fixes #226759.

### CODE REVIEW

File: Formula/p/picotool.rb [hunk 1]
```diff
@@ -15,6 +16,10 @@ class Picotool < Formula
         formula :parent
       end
     end
+    resource "mbedtls-v2" do
+      url "https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-2.28.10/mbedtls-2.28.10.tar.bz2"
+      sha256 "19e5b81fdac0fe22009b9e2bdcd52d7dcafbf62bc67fc59cf0a76b5b5540d149"
+    end
```
Comment (carlocab) [inline Formula/p/picotool.rb]: Not sure how I feel about this, given https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-vendored-versions-of-homebrew-formulae and `mbedtls@2` is deprecated.

I would consider just documenting the lack of these features for now and then think about adding them later if more users complain.

Comment (EricFromCanada) [reply Formula/p/picotool.rb]: Alternatively, I have the HEAD version building which includes the requested feature.

Comment (Frank-Zeyda) [reply Formula/p/picotool.rb]: Note that a lack of signing features means that users cannot fully build [pico-examples](https://github.com/raspberrypi/pico-examples) for the new version of the Pico board on MacOS (Pico 2 with RP2350 chip). I do believe it is essential to support them, bearing in mind that there is little point in buying an RP2040-based board now with the superior RP2350 chip available.

**Comment by daeho-ro** [comment]
If this is a problem of submodules, why not just use the source url
```
https://github.com/raspberrypi/pico-sdk/releases/download/2.1.1/pico-sdk-2.1.1.tar.gz
```

**Comment by EricFromCanada** [comment]
> If this is a problem of submodules, why not just use the source url https://github.com/raspberrypi/pico-sdk/releases/download/2.1.1/pico-sdk-2.1.1.tar.gz

Because the archive from that URL just has empty directories in `lib/`.

**Review by SMillerDev — APPROVED** [review]
