### PR TITLE
keep-sorted: set version in build info

### LINKED ISSUE #209113: keep-sorted: version is not properly reported
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs keep-sorted
Error: No logs.



% brew config
HOMEBREW_VERSION: 4.4.22-71-g9dc1e61
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9dc1e614432833dfa9ed405eceffe82e5a063ba5
Last commit: 2 hours ago
Branch: master
Core tap JSON: 27 Feb 10:23 UTC
Core cask tap JSON: 27 Feb 10:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.48.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.4-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false



% brew doctor
<nothing relevant>


No prior issues: https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue%20keep-sorted%20version
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

```
% brew install keep-sorted
% keep-sorted --version
```

Needed the project version to report an upstream bug.

### What happened (include all command output)?

```
% keep-sorted --version
unknown
```

### What did you expect to happen?

It should have printed `v0.6.0` (or similar).

c.f. https://github.com/google/keep-sorted/blob/799ca64fc7d4c09d96d7a68f8ee70a2473465cbd/main.go#L86

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew install keep-sorted
% keep-sorted --version
```

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This should fix #209113. In the case of `keep-sorted`, when Git history is available, `go` will automatically embed the tag/revision info in the resulting binary.

### CODE REVIEW

File: Formula/k/keep-sorted.rb [hunk 1]
```diff
@@ -1,7 +1,9 @@
 class KeepSorted < Formula
   desc "Language-agnostic formatter that sorts selected lines"
   homepage "https://github.com/google/keep-sorted"
-  url "https://github.com/google/keep-sorted/archive/refs/tags/v0.6.0.tar.gz"
+  url "https://github.com/google/keep-sorted.git",
+      tag:      "v0.6.0",
+      revision: "df93c2722b6126556183749880f16a9beb664bb4"
   sha256 "28a8290da4908999712896ed0a94a0e26f290f22b565f290a0782220379a033c"
```
Comment (p-linnane) [inline Formula/k/keep-sorted.rb:7]:
```suggestion

```

File: Formula/k/keep-sorted.rb [hunk 2]
```diff
@@ -21,6 +23,7 @@ def install
   end
 
   test do
+    assert_match "v#{version}", shell_output("#{bin}/keep-sorted --version")
```
Comment (p-linnane) [inline Formula/k/keep-sorted.rb:26]:
```suggestion
    assert_match "v#{version}", shell_output("#{bin}/keep-sorted --version")

```

**Review by p-linnane — APPROVED** [review]
Minor nits, but otherwise makes sense.
