### PR TITLE
git-cola: Depend on qtwayland on Linux

### LINKED ISSUE #231275: git-cola wont start due to missing qt platform plugins
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.5.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 50fa89e96bccedeca21287427eb7db12289f57ea
Last commit: 2 days ago
Branch: stable
Core tap JSON: 26 Jul 06:28 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 22
SUDO_ASKPASS: /usr/libexec/openssh/gnome-ssh-askpass
Homebrew Ruby: 3.4.5 => /var/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: 22-core 64-bit alderlake
Clang: 20.1.8
Git: 2.50.1 => /bin/git
Curl: 8.11.1 => /bin/curl
Kernel: Linux 6.14.11-300.fc42.x86_64 x86_64 GNU/Linux
OS: Bluefin (Version: 42.20250720.2 / FROM Fedora Silverblue 42) (Deinonychus)
Host glibc: 2.41
/usr/bin/gcc: 15.1.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 15.1.0
xorg: N/A
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

start git cola on a wayland based linux system

### What happened (include all command output)?

```
 LC_ALL=C.UTF-8 git-cola
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abgebrochen (Speicherabzug geschrieben)
```

### What did you expect to happen?

the app actually starting

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- `brew install git-cola`

- `git-cola`
```

### PR DESCRIPTION
**Pull request by colindean**
This enables `git-cola`to start for me on Bluefin gts-41.20251019.

Fixes #231275

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

~~WIP: I made this edit in GitHub and expect CI to yell at me.~~ It got past the lints I thought would fail, so I'll take it out of draft.

### CODE REVIEW

File: Formula/g/git-cola.rb [hunk 1]
```diff
@@ -16,6 +16,10 @@ class GitCola < Formula
   depends_on "pyqt"
   depends_on "python@3.14"
 
+  on_linux do
+    depends_on "qtwayland"
```
Comment (chenrui333) [inline Formula/g/git-cola.rb]: this is something we do these days :) 

```suggestion
    depends_on "qtwayland" => :no_linkage
```

**Review by daeho-ro — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]
Thanks!
