### PR TITLE
slimerjs: fix to use GitHub tarballs

### LINKED ISSUE #6809: slimerjs formula has mismatched hashes
Installing the `slimerjs` formula, I consistently get the following error about a SHA256 mismatch.

The downloaded file matches the published signatures at `https://download.slimerjs.org/releases/0.10.1/slimerjs-0.10.1.zip.asc`, which is why I'm reporting this as an issue with the formula. The download is not incomplete or corrupt.

```
$ brew install slimerjs
==> Using the sandbox
==> Downloading https://download.slimerjs.org/releases/0.10.1/slimerjs-0.10.1.zip
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a2b796c677e9a1faab97b365e70bb3f5e1733728c70ce5e0a9c4d6b19385ae93
Actual: d470c0a33db7c8c19a9a75b0e6216736c94d157b2a3da82b797c22188afa4496
Archive: /Users/kristopf/Library/Caches/Homebrew/slimerjs-0.10.1.zip
To retry an incomplete download, remove the file above.
```

### PR DESCRIPTION
**Pull request by umireon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes #6809.

### CODE REVIEW

**Comment by umireon** [comment]
The dependencies is also outdated.

**Comment by umireon** [comment]
The probrematic XulRunner-based implementation is removed from 0.10.0.
https://docs.slimerjs.org/master/release-notes-0.10.html

File: Formula/slimerjs.rb [hunk 1]
```diff
@@ -1,75 +1,39 @@
...
 
-  devel do
-    url "https://download.slimerjs.org/nightlies/latest-slimerjs-master/slimerjs-1.0.0-pre.zip"
-    sha256 "4fa35f42267b8a4c5f84301e20b18603c5a71e723d4838fd9a5756cc824c0355"
-  end
-
   bottle :unneeded
 
-  # Min supported OS X version by Firefox is 10.6.
-  depends_on :macos => :leopard
```
Comment (umireon) [inline Formula/slimerjs.rb]: Requiring 10.6+ is related to XulRunner and no longer necessary because XulRunner is excluded from SlimerJS.

File: Formula/slimerjs.rb [hunk 2]
```diff
@@ -1,75 +1,39 @@
...
 
-  def caveats
-    s = ""
-
-    if (firefox_installation = FirefoxRequirement.firefox_installation)
-      s += <<-EOS.undent
-        You MUST provide an installation of Mozilla Firefox and set
-        the environment variable SLIMERJSLAUNCHER pointing to it, e.g.:
-
-        export SLIMERJSLAUNCHER=#{firefox_installation}/Contents/MacOS/firefox
```
Comment (umireon) [inline Formula/slimerjs.rb]: Now SlimerJS automatically detects /Applications/Firefox.app.

File: Formula/slimerjs.rb [hunk 3]
```diff
@@ -1,75 +1,39 @@
...
-        EOS
-    end
-    s += <<-EOS.undent
+  def caveats; <<-EOS.undent
+    SlimerJS may need some configurations before using:
+      https://docs.slimerjs.org/current/installation.html
 
-      Note: If you use SlimerJS with an unstable version of Mozilla Firefox (>38.*)
```
Comment (umireon) [inline Formula/slimerjs.rb]: This part is not Homebrew-specific. A clear explanation is on the official document.

File: Formula/slimerjs.rb [hunk 4]
```diff
@@ -1,75 +1,39 @@
...
-        You MUST provide an installation of Mozilla Firefox and set
-        the environment variable SLIMERJSLAUNCHER pointing to it, e.g.:
-
-        export SLIMERJSLAUNCHER=#{firefox_installation}/Contents/MacOS/firefox
-        EOS
-    end
-    s += <<-EOS.undent
+  def caveats; <<-EOS.undent
+    SlimerJS may need some configurations before using:
+      https://docs.slimerjs.org/current/installation.html
```
Comment (MikeMcQuaid) [inline Formula/slimerjs.rb]: This part isn't Homebrew-specific either so let's remove it.

File: Formula/slimerjs.rb [hunk 5]
```diff
@@ -1,75 +1,39 @@
...
 
-      Note: If you use SlimerJS with an unstable version of Mozilla Firefox (>38.*)
-      you may have to change the [Gecko]MaxVersion in #{libexec}/application.ini
+    The configuration file is placed in:
```
Comment (MikeMcQuaid) [inline Formula/slimerjs.rb]: `was installed in`

File: Formula/slimerjs.rb [hunk 6]
```diff
@@ -1,75 +1,39 @@
...
+      #{libexec}/application.ini
     EOS
-
-    s
   end
 
   test do
-    ENV.delete "SLIMERJSLAUNCHER"
-    assert_match "Set it with the path to Firefox", shell_output("#{bin}/slimerjs", 1)
+    if File.exist? "/Applications/Firefox.app/Contents/MacOS/firefox"
```
Comment (MikeMcQuaid) [inline Formula/slimerjs.rb]: Can skip this `if`; this block primarily exists for our CI and it'll never be present there.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]

**Comment by umireon** [comment]
Thank you for reviewing, @MikeMcQuaid 
I removed unnecessary things from this Formula.
`ENV["SLIMERJSLAUNCHER"]` was changed to be set explicitly to success both on CI and machines.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!
