### PR TITLE
github-keygen: add dependency for linux

### LINKED ISSUE #219910: `github-keygen` missing some dependency, cannot run after installation
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.4.29
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2eb614a4653421ab6e0cea27c42bbfadcad1a582
Last commit: 6 days ago
Branch: stable
Core tap JSON: 13 Apr 15:15 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 8
SUDO_ASKPASS: /usr/bin/ksshaskpass
Homebrew Ruby: 3.3.7 => /var/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.49.0 => /bin/git
Curl: 8.9.1 => /bin/curl
Kernel: Linux 6.13.7-108.bazzite.fc41.x86_64 x86_64 GNU/Linux
OS: Bazzite 41 (FROM Fedora Kinoite) (Holographic)
Host glibc: 2.40
/usr/bin/gcc: 14.2.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A



$ brew doctor
brew doctor
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I installed github-keygen and wanted to run it.

```
$ brew install github-keygen
==> Downloading https://ghcr.io/v2/homebrew/core/github-keygen/manifests/1.400
######################################################################################################## 100.0%
==> Fetching github-keygen
==> Downloading https://ghcr.io/v2/homebrew/core/github-keygen/blobs/sha256:ce4d2d363e88f82852998fb401ac8bdbcff
######################################################################################################## 100.0%
==> Pouring github-keygen--1.400.all.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/github-keygen/1.400: 6 files, 416.8KB
```

### What happened (include all command output)?

After installing the bottled github-keygen, I wanted to run it, but it then reports it is missing a module.

```
$ github-keygen 
Can't locate filetest.pm in @INC (you may need to install the filetest module) (@INC entries checked: FatPacked::94528330646200=HASH(0x55f91791c2b8) /usr/local/lib64/perl5/5.40 /usr/local/share/perl5/5.40 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/linuxbrew/.linuxbrew/bin/github-keygen line 10357.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/github-keygen line 10357.
```

### What did you expect to happen?

Expected all required modules to be on my system after the brew install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install github-keygen
github-keygen
```

### PR DESCRIPTION
**Pull request by Zegnat**
Adds `perl` as a dependency for Linux systems. Perl might be available on distros (such as Bazzite) without having all the modules bundled. The github-keygen tool has expectations about available modules. By making Homebrew’s Perl a dependency, this is addressed.

Fixes #219910.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

File: Formula/g/github-keygen.rb [hunk 1]
```diff
@@ -6,6 +6,8 @@ class GithubKeygen < Formula
   license "GPL-3.0-or-later"
   head "https://github.com/dolmen/github-keygen.git", branch: "release"
 
+  uses_from_macos "perl"
+
```
Comment (chenrui333) [inline Formula/g/github-keygen.rb:10]: can you run `brew style --fix github-keychain` to fix the syntax issue?

Comment (Zegnat) [reply Formula/g/github-keygen.rb]: Not sure how I missed that. Apologies. Fixed now 👍

**Review by daeho-ro — APPROVED** [review]
