### PR TITLE
duckdb: fix library usage with cmake

### LINKED ISSUE #231450: duckdb is broken without static libraries
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

Use DuckDB from cmake

### What happened (include all command output)?

This PR broke duckdb from cmake: https://github.com/Homebrew/homebrew-core/pull/219286

When I install DuckDB (1.3.2) from Homebrew and try to use it from CMake I get:
```
CMake Error at /opt/homebrew/lib/cmake/DuckDB/DuckDBExports.cmake:163 (message):
  The imported target "duckdb_static" references the file

     "/opt/homebrew/lib/libduckdb_static.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/opt/homebrew/lib/cmake/DuckDB/DuckDBExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /opt/homebrew/lib/cmake/DuckDB/DuckDBConfig.cmake:18 (include)
  CMakeLists.txt:527 (find_package)
```

### What did you expect to happen?

Being able to find duckdb from cmake.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install duckdb

find_package(DuckDB QUIET)  # from cmake
```

### PR DESCRIPTION
**Pull request by Dahlgren**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The DuckDB CMake config (`/opt/homebrew/lib/cmake/DuckDB/DuckDBExports.cmake`) has references to the static library files and fails with error if they are not present.

Added a test to ensure CMake `find_package(DuckDB)` works.

Fixes #231450

### CODE REVIEW

**Review by daeho-ro — APPROVED** [review]
Looks fine, and wait another response.

**Comment by PetterS** [comment]
Thanks for fixing and adding a cmake test!

File: Formula/d/duckdb.rb [hunk 1]
```diff
@@ -54,5 +52,32 @@ def install
...
+      project(test_duckdb)
+      set(CMAKE_CXX_STANDARD 11)
+      find_package(DuckDB REQUIRED)
+      add_executable(test test.cpp)
+      target_link_libraries(test duckdb)
+    CMAKE
+
+    system "cmake", testpath
+    system "cmake", "--build", "."
+    assert_equal "45.0", shell_output(testpath/"test")
```
Comment (daeho-ro) [inline Formula/d/duckdb.rb]: We have standard form of `cmake` usage,
```suggestion
    system "cmake", "-S", ".", "-B", "build"
    system "cmake", "--build", "build"
    assert_equal "45.0", shell_output(testpath/"build/test")
```

Comment (Dahlgren) [reply Formula/d/duckdb.rb]: Updated the test paths

**Review by daeho-ro — APPROVED** [review]
