### PR TITLE
hyfetch: build rust implementation

### LINKED ISSUE #234514: hyfetch: The rust executable is not found, falling back to python...
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
chatplm@macen37362 ~> brew config
HOMEBREW_VERSION: 4.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed0011f40fef7efe311b5526beff7626755e89cd
Last commit: 3 hours ago
Branch: stable
Core tap JSON: 22 Aug 12:59 UTC
Core cask tap JSON: 22 Aug 12:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 3.4.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: 24-core 64-bit arm_blizzard_avalanche
Clang: 17.0.0 build 1700
Git: 2.51.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.6-arm64
CLT: 16.4.0.0.1.1747106510
Xcode: N/A
Rosetta 2: false


chatplm@macen37362 ~> brew doctor
Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

Updated hyfetch to 2.0.1 (rust rewrite), tried to run hyfetch

### What happened (include all command output)?

```
chatplm@macen37362 ~> hyfetch
The rust executable is not found, falling back to python...
                                  chatplm@macen37362
                    c.'           ------------------
                 ,xNMM.           OS: macOS Sequoia 15.6 arm64
               .OMMMMo            Kernel: Darwin 24.6.0
               lMM"               Host: Mac Studio (M2 Ultra, 2023, Two Thunderbolt 4 front ports)
     .;loddo:.  .olloddol;.   
   cKMMMMMMMMMMNWMMMMMMMMMM0:     Uptime: 17 days, 1 hour, 55 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.     Packages: 78 (brew), 9 (brew-cask)
 XMMMMMMMMMMMMMMMMMMMMMMMX.       Shell: fish 4.0.2
;MMMMMMMMMMMMMMMMMMMMMMMM:        Terminal: Apple Terminal 455.1
:MMMMMMMMMMMMMMMMMMMMMMMM:    
.MMMMMMMMMMMMMMMMMMMMMMMMX.       Memory: 79.57 GiB / 192.00 GiB (41%)
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.     Display (P27h-20): 2560x1440 @ 60 Hz in 27" [External]
 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Disk (/): 692.96 GiB / 926.35 GiB (75%) - apfs [Read-only]
  'XMMMMMMMMMMMMMMMMMMMMMMMMK.    Disk (/Volumes/Phoenix Slides): 3.36 MiB / 16.65 MiB (20%) - hfs [External, Read-only]
    kMMMMMMMMMMMMMMMMMMMMMMd      Local IP (en0): 128.141.95.160/25
     ;KMMMMMMMWXXWMMMMMMMk.   
       "cooc*"    "*coo'"                                 
                                                          
```

### What did you expect to happen?

No error to be logged (none is with the version installed from pip)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install hyfetch`
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixes #234514.

### CODE REVIEW

File: Formula/h/hyfetch.rb [hunk 1]
```diff
@@ -12,10 +12,15 @@ class Hyfetch < Formula
...
 
+  depends_on "rust" => :build
   depends_on "python@3.13"
 
   def install
+    # Install to `buildpath` first or else `virtualenv_install_with_resources` will overwrite it.
+    system "cargo", "install", *std_cargo_args(path: "crates/hyfetch", root: buildpath)
     virtualenv_install_with_resources
+    # Install the rust executable where the Python package expects it.
+    (libexec/Language::Python.site_packages("python3")/"hyfetch/rust").install "bin/hyfetch"
```
Comment (cho-m) [inline Formula/h/hyfetch.rb:30]: Can we just drop the Python code/dependency given it seems to be a fallback for new rust implementation? If so, should also use GitHub source rather than PyPI.

Will need to handle undoing `all` bottle too.

---

EDIT: I guess it depends if we want the old implementation still available during transition period (`hyfetch.v1`).

Comment (carlocab) [reply Formula/h/hyfetch.rb:30]: Yea, I looked at dropping the Python implementation but it requires additional manual work too (installing `neowofetch`, etc). It ended up being easier to just match what upstream installs with `pip install hyfetch`.

**Review by chenrui333 — APPROVED** [review]
