### PR TITLE
forgit 23.04.0 (new formula)

### LINKED ISSUE #194: Add formula to homebrew
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
- Shell: All

## Problem / Steps to reproduce

There is no homebrew formula for forgit, this is my default package manager.

### PR DESCRIPTION
**Pull request by carlfriedrich**
Fixes https://github.com/wfxr/forgit/issues/194

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

File: Formula/forgit.rb [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+  license "MIT"
+
+  depends_on "fzf"
+
+  def install
+    bin.install "bin/git-forgit" => "git-forgit"
+  end
+
+  test do
+    system "which", "git-forgit"
```
Comment (chenrui333) [inline Formula/forgit.rb:15]: Can you propose a more substantial test than checking the version or calling for help? These tests rarely ever fail even for broken installations.

>We want tests that don’t require any user input and test the basic functionality of the application. For example `foo build-foo input.foo` is a good test and (despite their widespread use) `foo --version` and `foo --help` are bad tests.

Ref. https://docs.brew.sh/Formula-Cookbook#add-a-test-to-the-formula

File: Formula/forgit.rb [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+  desc "Interactive git commands in the terminal"
+  homepage "https://github.com/wfxr/forgit"
+  url "https://github.com/wfxr/forgit/releases/download/23.04.0/forgit-23.04.0.tar.gz"
+  sha256 "89826d12b551829c4bce396551b1505c0604ba29130f4b8e2f842c2ca0b4c9e3"
+  license "MIT"
+
+  depends_on "fzf"
+
+  def install
+    bin.install "bin/git-forgit" => "git-forgit"
```
Comment (carlocab) [inline Formula/forgit.rb:11]: This should probably be enough:
```suggestion
    bin.install "bin/git-forgit"
```

Comment (carlocab) [reply Formula/forgit.rb:11]: Or, better:
```suggestion
    prefix.install "bin"
    bash_completion.install "completions/git-forgit.bash"
    pkgshare.install "forgit.plugin.zsh"
```

File: Formula/forgit.rb (hunk 1 above)
Comment (carlfriedrich) [reply Formula/forgit.rb:15]: Hi @chenrui333, thanks for your feedback. `forgit` is a fully interactive tool, so I actually don't know how to test any functionality of it without user input. Do you have an idea?

Comment (carlfriedrich) [reply Formula/forgit.rb:15]: To explain it even further: `forgit` is an interactive frontend for `git`. So the actual *functionality* that coud be tested is just functionality of `git`. Everything `forgit` does is just user presentation. How could we test this?

Comment (carlfriedrich) [reply Formula/forgit.rb]: Nevermind, I think I found a useful testcase. `git forgit add <file>` bypasses the interactive selector while still checking if forgit is correctly installed, because otherwise `git` would complain:

`git: 'forgit' is not a git command. See 'git --help'.`

So this should be a valid test IMO. Let me know if that works for you.

**Comment by carlfriedrich** [comment]
@carlocab @chenrui333 I updated the forumla according to your reviews. I also added a message to the user about how to use the forgit installation. I assume that adding a line to the user's `.zshrc` automatically is not a task homebrew should do?

File: Formula/forgit.rb (hunk 2 above)
Comment (carlfriedrich) [reply Formula/forgit.rb]: @carlocab I also had to adjust `pkgshare.install "forgit.plugin.zsh"` to `prefix.install "forgit.plugin.zsh"` because the shell plugin assumes that the forgit script is located in a subdir `bin` relative to the plugin location.

File: Formula/forgit.rb [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+  url "https://github.com/wfxr/forgit/releases/download/23.04.0/forgit-23.04.0.tar.gz"
+  sha256 "89826d12b551829c4bce396551b1505c0604ba29130f4b8e2f842c2ca0b4c9e3"
+  license "MIT"
+
+  depends_on "fzf"
+
+  def install
+    bin.install "bin/git-forgit"
+    bash_completion.install "completions/git-forgit.bash"
+    prefix.install "forgit.plugin.zsh"
```
Comment (carlocab) [inline Formula/forgit.rb:13]: Let's use `pkgshare` since that's where other formulae install Zsh plugins.
```suggestion
    inreplace "forgit.plugin.zsh", 'FORGIT="$INSTALL_DIR', "FORGIT=\"#{opt_prefix}"
    pkgshare.install "forgit.plugin.zsh"
    pkgshare.install_symlink "forgit.plugin.zsh" => "forgit.plugin.sh"
```

File: Formula/forgit.rb [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+  end
+
+  def post_install
+    ohai "NOTE: forgit can be used as subcommand of git (e.g. 'git forgit log')."
+    ohai "If you like to have zsh/bash shell aliases (e.g. 'glo'), source the shell plugin:"
+    ohai "  source #{prefix}/forgit.plugin.zsh"
+    ohai "Add the line to your .zshrc/.bashrc to make this permanent."
+  end
```
Comment (carlocab) [inline Formula/forgit.rb:21]:
```suggestion
  def caveats
    <<~EOS
      A shell plugin has been installed at
        #{opt_pkgshare}/forgit.plugin.zsh
        #{opt_pkgshare}/forgit.plugin.sh
    EOS
  end
```

File: Formula/forgit.rb (hunk 3 above)
Comment (carlfriedrich) [reply Formula/forgit.rb]: @carlocab Great, thanks a lot for the feedback. I updated the branch with your sugesstions.

File: Formula/forgit.rb (hunk 4 above)
Comment (carlfriedrich) [reply Formula/forgit.rb]: @carlocab Good idea, thanks a lot. I updated the branch accordingly.

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by SMillerDev — APPROVED** [review]
