### PR TITLE
scala-cli 1.12.4 (new formula) & scala: use native scala-cli

### LINKED ISSUE #4139: Homebrew installation doesn't use native launchers?
**Version(s)**
Scala code runner version: 1.11.0
Scala version (default): 3.8.1

(but I think it's long, perhaps always, been this way)

**Describe the bug**
The `scala` command installed by Homebrew prints `sun.misc.Unsafe` warnings on launch. According to @Gedochao on Discord (https://discord.com/channels/632150470000902164/901153021638082660/1464372766244470977), this is evidence that the JAR is being launched, rather than a native binary.

**To Reproduce**
`brew install scala`

and then, on JDK 25,

```
% java -version
openjdk version "25.0.2" 2026-01-20 LTS
OpenJDK Runtime Environment Temurin-25.0.2+10 (build 25.0.2+10-LTS)
OpenJDK 64-Bit Server VM Temurin-25.0.2+10 (build 25.0.2+10-LTS, mixed mode, sharing)
% which scala
/opt/homebrew/bin/scala
% scala
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by scala.runtime.LazyVals$ (file:/opt/homebrew/Cellar/scala/3.8.1/libexec/libexec/scala-cli.jar)
WARNING: Please consider reporting this to the maintainers of class scala.runtime.LazyVals$
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by com.sun.jna.Native in an unnamed module (file:/opt/homebrew/Cellar/scala/3.8.1/libexec/libexec/scala-cli.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

Welcome to Scala 3.8.1 (25.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                    
scala> 
```

**Expected behaviour**
No `sun.Misc.unsafe` or other "WARNING:" messages.

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes https://github.com/VirtusLab/scala-cli/issues/4139

Changes the `scala` (Scala 3 language installation) formula as follows (or the what and why of this PR)
- switch from the generic JVM-launcher tarball (`scala3-3.8.2.tar.gz`) to platform-specific tarballs that bundle a native image of `scala-cli` (`scala3-3.8.2-{arch}-{os}.tar.gz`)
- this is considerably better, as the native launchers for individual platforms are generally faster than their JVM equivalents, and also don't require a JVM to be installed in the first place; they're also the recommended and default way to use Scala CLI
  - this perhaps matters more, as Scala 3 requires JDK17 since Scala 3.8.0
  - what's more, while Scala CLI is built with Scala 3.3 LTS (will likely switch to 3.9 LTS when that's out), it uses an old implementation of lazy vals which warns on JDK 25 (and will outright error on JDK26+), as per  JEP-471
      - this has been mitigated in Scala 3.8 with https://github.com/scala/scala3/issues/9013 (the price being the required JVM is higher)
- I added sanity checks for all of the commands installed here (`scala`, `scalac`, `scaladoc`, `scala-cli`)
  - `scala-cli` gets installed under-the-hood anyway, so why not give it a symlink 🤷  
  - ~the tests involve various JVMs (8, 17, 25), which are managed by Coursier, Coursier's formula being a dependency for the tests (and only the tests)~

cc @tgodzik @WojciechMazur @SolalPirelli @hamzaremmal

### Checks

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
### AI/LLM stuff

(as one can see below, Claude was rather helpful here; big thanks for providing `AGENTS.md` in the repo, this sped me up considerably)

- [x] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

Cursor (Claude) was used interactively to:
- Download and inspect the platform-specific tarball layout to understand the bin/, libexec/, lib/, maven2/, VERSION structure
- Compute SHA256 checksums for all 4 platform-specific tarballs
- Write the formula: platform-specific on_macos/on_linux + on_arm/on_intel URL blocks, the install method with libexec + symlink approach, and the test block
- Identify that conflicts_with "pwntools" could be removed (common moved from bin/ to libexec/)
- Debug the PROG_HOME resolution issue (scripts reference ../libexec/, ../VERSION, ../maven2/ relative to bin/)
- Fix component ordering (livecheck before on_macos, depends_on before on_macos) and livecheck style (url :stable)
- Add scala to not_a_binary_url_prefix_allowlist.json for the binary URL audit
- Expose scala-cli as a bin/ command via symlink from libexec/libexec/scala-cli

### Manual checks
```bash
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source scala # installed successfully
scala version # works with empty JAVA_HOME
JAVA_HOME=<jdk8> scala version # native launcher starts with JDK 8
JAVA_HOME=<jdk8> scala --server=false --jvm 17 -e 'println(42)' # compiles and runs
JAVA_HOME=<jdk25> scala --server=false -e 'println(42)' # no sun.misc.Unsafe warnings (see https://github.com/VirtusLab/scala-cli/issues/4139 and https://github.com/scala/scala3/issues/9013)
scalac -version # 3.8.2, as it should be
scaladoc -version # likewise
scala-cli version # tested the launcher with JDK 8, 17, and 25
brew test scala # all assertions pass
brew audit scala # passes
brew audit --strict scala # 2 binary URL warnings (expected? allowlist added)
brew style Formula/s/scala.rb # no offenses
```
-----

### CODE REVIEW

**Comment by Gedochao** [comment]
https://www.scala-lang.org/download/
Note how we currently advise MacOS users to use `brew` to install [coursier](https://github.com/coursier/coursier) and then use `cs` to install Scala, as that will get you the binaries, rather than JVM launchers 😅

File: Formula/s/scala.rb [hunk 1]
```diff
@@ -47,9 +73,45 @@ def main(args: Array[String]): Unit = {
...
       }
     SCALA
+    stderr_file = testpath/"stderr"
+
+    jdk8_home = shell_output("cs java-home --jvm 8").strip
+    jdk17_home = shell_output("cs java-home --jvm 17").strip
+    jdk25_home = shell_output("cs java-home --jvm 25").strip
+
+    # scalac: verify version and compilation with JDK 17
+    ENV["JAVA_HOME"] = jdk17_home
```
Comment (SMillerDev) [inline Formula/s/scala.rb]: What part of the brew install would affect scala's ability to respect `JAVA_HOME`?

Comment (Gedochao) [reply Formula/s/scala.rb]: Scala 3.8+ requires JDK 17, so I assumed I should set it for these tests.
For the `scala` and `scala-cli` commands specifically, it's more of a sanity check that the script indeed uses the native binary (built with GraalVM) and behaves correctly with JDKs 8/17/25 on the install.
If you find any of this unnecessary, I can remove those (I may have gone overboard)

Comment (Gedochao) [reply Formula/s/scala.rb]: also, only `scala`/`scala-cli` use native binaries underneath.
`scalac` & `scaladoc` use JARs.

File: Formula/s/scala.rb [hunk 2]
```diff
@@ -1,30 +1,58 @@
 class Scala < Formula
   desc "JVM-based programming language"
   homepage "https://dotty.epfl.ch/"
```
Comment (WojciechMazur) [inline Formula/s/scala.rb]: Nit: If we're updating the formula, then maybe let's give it also the proper homepage
```suggestion
  homepage "https://scala-lang.org/"
```

File: Formula/s/scala.rb (hunk 1 above)
Comment (SMillerDev) [reply Formula/s/scala.rb]: The original formula did not require JAVA_HOME to be set, so this is a regression IYAM.

Comment (Gedochao) [reply Formula/s/scala.rb]: I believe I misunderstood what was meant here. I do not think setting `JAVA_HOME` is necessary for the installation here, I initially put it in for the sake of tests/validation.
And anyway, it is no longer there.

**Comment by Gedochao** [comment]
Added dependencies on `patchelf` and `zlib-ng-compat` in an attempt to make the CI happy with `libz.so.1`.

File: Formula/s/scala.rb [hunk 3]
```diff
@@ -1,8 +1,10 @@
 class Scala < Formula
   desc "JVM-based programming language"
-  homepage "https://dotty.epfl.ch/"
-  url "https://github.com/scala/scala3/releases/download/3.8.2/scala3-3.8.2.tar.gz"
-  sha256 "827356a78a70d3d792f1a77e109cc3fa3ea946b8d26848bb245f275be52fd78e"
+  homepage "https://www.scala-lang.org"
+  # IllegalArgumentException: One of setGitDir or setWorkTree must be called.
```
Comment (SMillerDev) [inline Formula/s/scala.rb]: This seems unrelated
```suggestion
```

File: Formula/s/scala.rb [hunk 4]
```diff
@@ -14,17 +15,32 @@ class Scala < Formula
...
+
+    system "sbt", "dist-#{os}-#{arch}/Universal/stage"
+
+    cd "dist/#{os}-#{arch}/target/universal/stage" do
+      rm Dir["**/*.bat"]
+
+      libexec.install "lib", "maven2", "VERSION", "libexec"
+      prefix.install "bin"
+    end
+    system "patchelf", "--set-rpath", Formula["zlib-ng-compat"].opt_lib, libexec/"libexec/scala-cli" if OS.linux?
```
Comment (SMillerDev) [inline Formula/s/scala.rb]: @Homebrew/maintainers do we have a DSL we can use for this instead? Or does that only work for machos?

Comment (ZhongRuoyu) [reply Formula/s/scala.rb]: It's possible but not with a DSL, see:

https://github.com/Homebrew/homebrew-core/blob/84a752174aa638f7a08cfbe052d0e77e5e13af91/Formula/r/rustfmt.rb#L49-L52

Comment (MikeMcQuaid) [reply Formula/s/scala.rb]: If we're using this in multiple places a DSL for this would be nice. Not blocking for this PR though!

Comment (cho-m) [reply Formula/s/scala.rb]: Would recommend against adding a DSL that is specific to prebuilt binaries as that will increase unwanted submissions of prebuilts.

Shipping prebuilt binaries should remain an exception in Homebrew/core and in most cases those should be moved to Cask, built from source, or rejected.

The main exceptions for now include `node` formulae due to how we can't avoid prebuilts via npm (and even there we try to delete prebuilts where possible). Other exceptions will be reviewed case-by-case.

Comment (SMillerDev) [reply Formula/s/scala.rb]: Is sbt not building the binaries here?

Comment (cho-m) [reply Formula/s/scala.rb]: sbt downloads a prebuilt scala-cli:
- https://github.com/scala/scala3/blob/3.8.2/project/Build.scala#L2663-L2681

Can also see 01.sbt.log output
> [republish] Downloading https://github.com/VirtusLab/scala-cli/releases/download/v1.12.2/scala-cli-aarch64-apple-darwin.gz to /private/tmp/scala-20260309-13431-qsqez1/dist/mac-aarch64/target/streams/_global/republishFetchLaunchers/_global/streams/republish-launchers/scala-cli.gz...

Comment (MikeMcQuaid) [reply Formula/s/scala.rb]: > Would recommend against adding a DSL that is specific to prebuilt binaries as that will increase unwanted submissions of prebuilts.

Fair and agreed.

Comment (SMillerDev) [reply Formula/s/scala.rb]: > sbt downloads a prebuilt scala-cli

I would say that makes the PR a regression on the current situation.

File: Formula/s/scala-cli.rb [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+    ENV["USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM"] = "false"
+    ENV["COURSIER_CACHE"] = "#{HOMEBREW_CACHE}/coursier/v1"
+    ENV["COURSIER_ARCHIVE_CACHE"] = "#{HOMEBREW_CACHE}/coursier/arc"
+    ENV["COURSIER_JVM_CACHE"] = "#{HOMEBREW_CACHE}/coursier/jvm"
+
+    system "./mill", "-i", "cli[].base-image.writeDefaultNativeImageScript",
+           "--scriptDest", "generate-native-image.sh"
+
+    # GraalVM native-image needs the real C compiler, not the superenv shim
+    ENV.remove "PATH", Superenv.shims_path
```
Comment (MikeMcQuaid) [inline Formula/s/scala-cli.rb]: Why? What happens without it? 

We want to avoid bypassing the shim here and instead fix the underlying issue.

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good so far! Once 🟢 and we've figured out superenv issue should be mergeable.

File: Formula/s/scala-cli.rb (hunk 5 above)
Comment (Gedochao) [reply Formula/s/scala-cli.rb]: > Why? What happens without it?

```
Error: Unable to detect supported DARWIN native software development toolchain.
Querying with command '/opt/homebrew/Library/Homebrew/shims/mac/super/cc -v' prints:
  cc: The build tool has reset ENV; --env=std required.
```

> We want to avoid bypassing the shim here and instead fix the underlying issue.

So I am by no means familiar with the internals here, but here's what I got.

It seems to crash at line 4 of `/opt/homebrew/Library/Homebrew/shims/super/cc`
```bash
if [[ -z "${HOMEBREW_RUBY_PATH}" ]]
then
  echo "${0##*/}: The build tool has reset ENV; --env=std required." >&2
  exit 1
fi
```
The GraalVM `native-image` binary is itself a Substrate VM native executable (Mach-O, not a JVM launcher). When it spawns `cc -v` to detect the C toolchain, `HOMEBREW_RUBY_PATH` seems not to be propagated to the child process (and quits, as it's empty)

I verified `HOMEBREW_RUBY_PATH` is set in the bash environment that invokes generate-native-image.sh, and `cc -v` works fine from that bash context. The variable is only missing in the subprocess spawned by the `native-image` binary itself.

Other ways I tried:
- `env :std` is deprecated and flagged by `brew audit --strict`
- Setting `ENV["CC"]` doesn't help because `native-image` ignores it for toolchain detection — it hardcodes running `cc -v`

I'm open to suggestions on what else to try.

Comment (MikeMcQuaid) [reply Formula/s/scala-cli.rb]: @Gedochao Thanks for explaining and investigating! Could you include the `Error: Unable to detect supported DARWIN native software development toolchain.` error message and a 1-2 line summary of the above as an additional few lines of the Ruby comment and then I think this is fine as-is.

**Review by MikeMcQuaid — APPROVED** [review]
Looks good, thanks for all the hard work here and patience @Gedochao! Much appreciated, you rock!
