### PR TITLE
signal-cli: build ARM macOS bottles

### LINKED ISSUE #228536: No signal-cli bottle for version 0.13.17
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: c19f08b3e8ea46ba94bd9315c46c0dda10ead31c
Last commit: 6 days ago
Branch: stable
Core tap JSON: 29 Jun 22:20 UTC
Core cask tap JSON: 29 Jun 22:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.4.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 17.0.0 build 1700
Git: 2.50.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.5-arm64
CLT: 16.4.0.0.1.1747106510
Xcode: 16.4
Rosetta 2: false
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

`brew upgrade`

### What happened (include all command output)?

I'm getting the following message:

```
==> Upgrading 1 outdated package:
signal-cli 0.13.16 -> 0.13.17
Error: signal-cli: no bottle available!
```

This also happened when upgrading to version 0.13.16, which was resolved(see [228055](https://github.com/Homebrew/homebrew-core/issues/228055)), so it looks like a recurring issue with the build process?

### What did you expect to happen?

Package should upgrade without throwing an error.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew upgrade` with `signal-cli` installed.
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Adding `depends_on arch: :x86_64` inside an `on_linux` block means that
ARM macOS runners are not deployed when building here.

Fixes #228536.

### CODE REVIEW

File: Formula/s/signal-cli.rb [hunk 1]
```diff
@@ -21,9 +21,10 @@ class SignalCli < Formula
   uses_from_macos "llvm" => :build # For `libclang`, used by `boring-sys` crate
   uses_from_macos "zip" => :build
 
-  on_linux do
-    depends_on arch: :x86_64 # `:libsignal-cli:test` failure, https://github.com/AsamK/signal-cli/issues/1787
-  end
+  # FIXME: Uncomment below when https://github.com/Homebrew/brew/issues/19838 is resolved
+  # FIXME: on_linux do
+  # FIXME:  depends_on arch: :x86_64 # `:libsignal-cli:test` failure, https://github.com/AsamK/signal-cli/issues/1787
+  # FIXME: end
```
Comment (Bo98) [inline Formula/s/signal-cli.rb:31]: Or just build `libsignal-client` first and pass `gradle build -Plibsignal_client_path="path/to/libsignal-client.jar"` and arm64 Linux will work fine.

**Review by Bo98 — APPROVED** [review]

File: Formula/s/signal-cli.rb (hunk 1 above)
Comment (carlocab) [reply Formula/s/signal-cli.rb:31]: Will try in a follow-up!
