### PR TITLE
scarb: fix binary missing issue

### LINKED ISSUE #647: error: no such command: `cairo-run`
Trying hello world [example from the book](https://book.cairo-lang.org/ch01-02-hello-world.html#building-a-scarb-project), I got:

```sh
❯ scarb cairo-run
error: no such command: `cairo-run`
```

current version

```sh
❯ scarb --version
scarb 2.5.4
cairo: 2.5.4 (https://crates.io/crates/cairo-lang-compiler/2.5.4)
sierra: 1.4.0
```

Did I miss some steps on install?

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

fixes https://github.com/cairo-book/cairo-book/issues/647

cc @jney

### CODE REVIEW

File: Formula/s/scarb.rb [hunk 1]
```diff
@@ -24,7 +25,15 @@ class Scarb < Formula
...
 
   def install
-    system "cargo", "install", *std_cargo_args(path: "scarb")
+    %w[
+      scarb
+      extensions/scarb-cairo-language-server
+      extensions/scarb-cairo-run
+      extensions/scarb-cairo-test
+      extensions/scarb-snforge-test-collector
+    ].each do |f|
```
Comment (maciektr) [inline Formula/s/scarb.rb:34]: Is it possible to find them dynamically, or should we just keep this in sync if the list changes in future Scarb releases? Would removing one extension cause an error or just a warning?

Comment (chenrui333) [reply Formula/s/scarb.rb:34]: it would cause error, treat this as kind of binary spec

**Review by fxcoudert — APPROVED** [review]
