### PR TITLE
ffmpeg: remove --enable-vda and --with-schroedinger

### LINKED ISSUE #18381: ffmpeg --HEAD fails due to --enable-vda
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`?
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs ffmpeg` [gist](https://gist.github.com/10974cd52c447ad56b47e169c61ad530)

## What you were trying to do (and why):
install ffmpeg HEAD so I could submit a bug report to them
## What happened (include command output): 
```console
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-6f15f1c --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-a
Last 15 lines from /Users/damon/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-libmp3lame
--enable-libx264
--enable-libxvid
--enable-opencl
--enable-videotoolbox
--disable-lzma
--enable-vda

ERROR: vda requested, but not all dependencies are satisfied: vda_framework pthreads

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```
## What you expected to happen
ffmpeg to compile
## Step-by-step reproduction instructions (by running `brew install` commands)
```console
$ brew install ffmpeg --with-fdk-aac --with-tools --with-freetype --with-libass --with-libvorbis --with-libvpx --with-x265 --HEAD
```
The above is what I used in this instance but the same error happens without any `--with` options. As long as you specify `--HEAD`. 
# Workaround
I then re-installed with `-vd`: `brew install -vd ffmpeg --with-fdk-aac --with-tools --with-freetype --with-libass --with-libvorbis --with-libvpx --with-x265 --HEAD`

It failed at the same point:
```console
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-6f15f1c --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-nonfree --enable-vda
```
Went into shell and re-ran `configure` without the `--enable-vda` option:
```console
$ ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-6f15f1c --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-nonfree
```
That worked. Exited shell, chose ignore, brew carried on and installed ffmpeg:
```console
$ ffmpeg -version
ffmpeg version git-2017-09-21-6f15f1c Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 9.0.0 (clang-900.0.37)
configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-6f15f1c --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-nonfree
libavutil      55. 76.100 / 55. 76.100
libavcodec     57.106.101 / 57.106.101
libavformat    57. 82.101 / 57. 82.101
libavdevice    57.  8.101 / 57.  8.101
libavfilter     6.105.100 /  6.105.100
libavresample   3.  6.  0 /  3.  6.  0
libswscale      4.  7.103 /  4.  7.103
libswresample   2.  8.100 /  2.  8.100
libpostproc    54.  6.100 / 54.  6.100
```

### PR DESCRIPTION
**Pull request by selsta**
VDA does not even exist on recent macOS versions anymore and will be removed from ffmpeg soon.

libschroedinger is removed from FFmpeg git and will be removed with FFmpeg 3.4

### Sources

libschroedinger: https://github.com/FFmpeg/FFmpeg/blob/1ef7752d64cbe9af2f27cc65aba3a2ca3831c128/Changelog#L18

vda: http://ffmpeg.org/pipermail/ffmpeg-devel/2017-September/215888.html

Fixes #18381

---- 

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Passing on this as these changes do not affect the current stable version but thanks for the PR nonetheless!

**Comment by selsta** [comment]
This fixes `brew install --HEAD ffmpeg` that is currently broken because VDA does not exist anymore.

**Comment by ilovezfs** [comment]
@selsta happy to merge if you scope the changes to head.

**Comment by selsta** [comment]
@ilovezfs updated

**Comment by ilovezfs** [comment]
if you just move the option into a stable do block then it will automatically be false for head

**Comment by ilovezfs** [comment]
i.e. just move it from line 44 to line 10 and the rest of the changes are unneeded

**Comment by selsta** [comment]
done (sorry i’m not familiar with homebrew)

File: Formula/ffmpeg.rb [hunk 1]
```diff
@@ -181,7 +181,7 @@ def install
     # A bug in a dispatch header on 10.10, included via CoreFoundation,
     # prevents GCC from building VDA support.
     # See: https://github.com/Homebrew/homebrew/issues/33741
-    if MacOS.version != :yosemite || ENV.compiler == :clang
+    if build.head? == false and (MacOS.version != :yosemite || ENV.compiler == :clang)
```
Comment (ilovezfs) [inline Formula/ffmpeg.rb]: if !build.head &&

File: Formula/ffmpeg.rb [hunk 2]
```diff
@@ -7,6 +7,7 @@ class Ffmpeg < Formula
     sha256 "5ef5e9276c311c74ab2e9d301c2d7ee10e1f2cbd758c6f13d6cb9514dffbac7e"
 
     depends_on "yasm" => :build
+    option "with-schroedinger", "Enable Dirac video format"
```
Comment (ilovezfs) [inline Formula/ffmpeg.rb]: and actually, sorry my mistake, this should be above `depends_on "yasm" => :build`, with a blank line beneath it, and the `depends_on "schroedinger" => :optional` needs to move up here below `depends_on "yasm" => :build`.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Need to delete line 47 too :)

**Comment by selsta** [comment]
lol I’m sorry

**Comment by ilovezfs** [comment]
No worries :)

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @selsta! Without people like you submitting PRs we couldn't run this project. You rock!
