### PR TITLE
libeatmydata: apply upstream fix

### LINKED ISSUE #136873: eatmydata error: unable to find 'eatmydata' in PATH
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

# brew config

```shell
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 12 days ago
Core tap JSON: 18 Jul 05:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 3-core 64-bit ivybridge
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode_14.2.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.7-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2 => /Applications/Xcode_14.2.app/Contents/Developer
```

# brew doctor
```
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to install the libeatmydata package in a GHA CI job in the hope of speeding up a testsuite run by eliminating time spent committing changes to disk.

### What happened (include all command output)?

I get an error when I try to run seemingly any command under eatmydata - e.g. `eatmydata ls /` gives:

```
eatmydata error: unable to find 'eatmydata' in PATH
```

### What did you expect to happen?

I'd expect it to successfully run `ls /` - that's what happens on platforms with a working eatmydata (for example, I tested on a Debian Linux machine using the Debian `eatmydata` package).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libeatmydata
eatmydata ls /
```

I created a repo to test this via GHA since I don't own a mac.  The workflow file I used is:

https://github.com/ojwb/homebrew-eatmydata-test/actions/runs/5583835375/workflow

Result of a run is:

https://github.com/ojwb/homebrew-eatmydata-test/actions/runs/5583835375/jobs/10204559309
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Resolves #136873.

### CODE REVIEW

File: Formula/libeatmydata.rb [hunk 1]
```diff
@@ -27,6 +27,13 @@ class Libeatmydata < Formula
     depends_on "strace" => :test
   end
 
+  # Fix for https://github.com/Homebrew/homebrew-core/issues/136873.
+  # Remove on next release.
+  patch do
+    url "https://github.com/stewartsmith/libeatmydata/commit/ae89d0916c0ddd06f4ce7f2b37eaccf8dd543591.patch?full_index=1"
+    sha256 "8bf4249f3df141fa321c8c64af4f4442bc23bdfb108e2cf73c22e68a3a71ae15"
+  end
```
Comment (carlocab) [inline Formula/libeatmydata.rb:35]: Maybe do this inside a `stable` block?

**Review by carlocab — APPROVED** [review]
