### PR TITLE
gitleaks: set version properly

### LINKED ISSUE #434: How to check gitleaks version on macos(fetched with Homebrew)
**Describe the bug**
By using `gitleaks --help` command, I found we can use `gitleaks --version` to check its version.
Since the gitleaks is fetched by homebrew, the output is 
```
$ gitleaks --version
Gitleaks uses LDFLAGS to pull most recent version. Build with 'make build' for version
```

Though the version can be fetched by `brew info gitleaks`, it's can be better if the result can be directly shown by the `gitleaks --version`.

**To Reproduce**

**Expected behavior**
Show gitleaks version which is widely supported.
**Screenshots**

**Basic Info (please complete the following information):**
 - OS: macos 10.15
 - Gitleaks Version: 6.0.0

**Additional context**

cc @zricethezav

### PR DESCRIPTION
**Pull request by zricethezav**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/zricethezav/gitleaks/issues/434

### CODE REVIEW

File: Formula/gitleaks.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ class Gitleaks < Formula
   depends_on "go" => :build
 
   def install
-    system "go", "build", "-ldflags", "-X github.com/zricethezav/gitleaks/version.Version=#{version}",
+    system "go", "build", "-ldflags", "-X github.com/zricethezav/gitleaks/v6/version.Version=#{version}",
```
Comment (bayandin) [inline Formula/gitleaks.rb:18]:
```suggestion
    system "go", "build", "-ldflags", "-X github.com/zricethezav/gitleaks/v#{version.major}/version.Version=#{version}",
```

**Review by bayandin — CHANGES_REQUESTED** [review]
- Could you also please add a check for this case to test block, should be something like this:
```ruby
    assert_equal version, shell_output("#{bin}/gitleaks --version")
```

- Bump a revision for the formula
- And squash all the commit into single one with a message like `gitleaks: fix version setting`
