### PR TITLE
tfenv: move default config dir to XDG_CONFIG_HOME

### LINKED ISSUE #230324: `tfenv` installs managed terraform versions into `HOMEBREW_CELLAR`
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
WORKBREW_VERSION: 1.3.3
HOMEBREW_VERSION: 4.5.10-43-g7ef389a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7ef389a4289e6d5c4980988fa666cd103beec9b9
Last commit: 11 minutes ago
Branch: main
Core tap HEAD: f22287a8b1b194b510f6a6f5bfc16d985202da5a
Core tap last commit: 29 minutes ago
Core tap JSON: 14 Jul 00:35 UTC
Core cask tap HEAD: 6b327aeb43a4c79c9b33824e7a98a26507ddedd9
Core cask tap last commit: 32 minutes ago
Core cask tap JSON: 14 Jul 00:35 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 43200
HOMEBREW_BAT: set
HOMEBREW_BREW_WRAPPER: /opt/workbrew/bin/brew
HOMEBREW_CASK_OPTS: ["--colorpickerdir=/Library/ColorPickers", "--prefpanedir=/Library/PreferencePanes", "--qlplugindir=/Library/QuickLook", "--mdimporterdir=/Library/Spotlight", "--dictionarydir=/Library/Dictionaries", "--fontdir=/Library/Fonts", "--servicedir=/Library/Services", "--input-methoddir=/Library/Input Methods", "--internet-plugindir=/Library/Internet Plug-Ins", "--audio-unit-plugindir=/Library/Audio/Plug-Ins/Components", "--vst-plugindir=/Library/Audio/Plug-Ins/VST", "--vst3-plugindir=/Library/Audio/Plug-Ins/VST3", "--screen-saverdir=/Library/Screen Savers"]
HOMEBREW_CURLRC: /opt/homebrew/etc/curlrc
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: nvim
HOMEBREW_FORBIDDEN_CASKS: zulu
HOMEBREW_FORBIDDEN_FORMULAE: pwgen
HOMEBREW_FORBIDDEN_OWNER: your Workbrew administrator
HOMEBREW_FORBIDDEN_OWNER_CONTACT: Contact us on Slack in #security with questions
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_FORCE_BREW_WRAPPER: /opt/workbrew/bin/brew
HOMEBREW_GIT_EMAIL: 30379873+carlocab@users.noreply.github.com
HOMEBREW_GIT_NAME: Carlo Cabrera
HOMEBREW_INSTALL_BADGE: ☕️
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_CLEANUP_FORMULAE: zsh
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_SYSTEM_ENV_TAKES_PRIORITY: set
HOMEBREW_TEMP: /var/folders/by/r3kqb74j2zn0010s9mcbsvv00000gp/T/
Homebrew Ruby: 3.4.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 17.0.0 build 1700
Git: 2.50.1 => /opt/homebrew/opt/git/bin/git
Curl: 8.15.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 15.5-arm64
CLT: 16.4.0.0.1.1747106510
Xcode: 16.4
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use `tfenv` to install `terraform`. (I don't really know why either.)

### What happened (include all command output)?

```
❯ tfenv install 1.10.5
Installing Terraform v1.10.5
Downloading release tarball from https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_darwin_arm64.zip
############################################################################################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_SHA256SUMS
Not instructed to use Local PGP (/opt/homebrew/Cellar/tfenv/3.0.0/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification
Archive:  /var/folders/nj/9vfk4f0n377605jhxxmngd8h0000gn/T/tfenv_download.sevgne/terraform_1.10.5_darwin_arm64.zip
  inflating: /opt/homebrew/Cellar/tfenv/3.0.0/versions/1.10.5/LICENSE.txt
  inflating: /opt/homebrew/Cellar/tfenv/3.0.0/versions/1.10.5/terraform
Installation of terraform v1.10.5 successful. To make this your default version, run 'tfenv use 1.10.5'
```

It's using `HOMEBREW_CELLAR` as the location to install `terraform` to.

### What did you expect to happen?

It should use a persistent location, perhaps inside `HOME`. See also #16077.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install tfenv
tfenv install 1.10.5
```

### PR DESCRIPTION
**Pull request by gromgit**
Closes #230324.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

File: Formula/t/tfenv.rb [hunk 1]
```diff
@@ -29,6 +29,7 @@ class Tfenv < Formula
 
   def install
     prefix.install %w[bin lib libexec share]
+    bin.env_script_all_files prefix/"rbin", TFENV_CONFIG_DIR: etc/"tfenv"
```
Comment (carlocab) [inline Formula/t/tfenv.rb]: `rbin` seems like an odd choice here.

Let's use `HOME` to be nicer for multi-user environments, and avoid clobbering existing `TFENV_CONFIG_DIR` configuration:

```suggestion
    bin.env_script_all_files prefix/"rbin", TFENV_CONFIG_DIR: "${TFENV_CONFIG_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/tfenv}"
```
May need extra quoting, I forget how `env_script_all_files` handles this.

Comment (gromgit) [reply Formula/t/tfenv.rb]: > `rbin` seems like an odd choice here.

It was mostly because the `bin` scripts used relative paths to find the subcommand scripts under `libexec`, so the relocation dir had to be on the same level as `bin`. `r` is just short for `real`, but I guess I could just call it `realbin`, or is there a convention I'm missing here?

> Let's use `HOME` to be nicer for multi-user environments, and avoid clobbering existing `TFENV_CONFIG_DIR` configuration:

Sure, I'll figure that one out...

Comment (carlocab) [reply Formula/t/tfenv.rb]: We normally use `libexec`, but presumably we avoid that here since `tfenv` already makes use of `libexec`. What do we risk if we use `libexec`?

Or, maybe, `share`? FHS describes it as "architecture-independent data", which seems appropriate.

That said, not hugely opposed to `prefix/"realbin"`, so we can go with that if you think that's best.

**Review by carlocab — APPROVED** [review]
Minor bike-shedding comments above. Fine with this as-is, or with any of the suggested bike-shedding alternatives.

File: Formula/t/tfenv.rb (hunk 1 above)
Comment (gromgit) [reply Formula/t/tfenv.rb]: > We normally use `libexec`, but presumably we avoid that here since `tfenv` already makes use of `libexec`. What do we risk if we use `libexec`?

If upstream later decides to do the same thing (move the core `tfenv` to `libexec` and put a wrapper script in its place), major breakage results that may be hard to trace. (I just tested creating a `libexec/tfenv` dummy file, and `env_script_all_files` silently overwrote it with the core `tfenv` script.) 

> Or, maybe, `share`? FHS describes it as "architecture-independent data", which seems appropriate.

This also breaks the formula if upstream decides to populate a `share/tfenv` directory, because `env_script_all_files` will silently move the source script inside that directory without warning, which leaves the upstream `tfenv` script unable to find the `libexec` subcommands.

I'm basically trying to avoid silently doing the wrong thing. 😁

Comment (Bo98) [reply Formula/t/tfenv.rb]: We already override `Pathname#write` to prevent overwriting so it sounds like `env_script_all_files` should probably be changed to do the same.

Comment (gromgit) [reply Formula/t/tfenv.rb]: OK, I'll switch to `libexec`, since there aren't any conflicts for this version, and I've initiated https://github.com/Homebrew/brew/pull/20281 to catch future conflicts.

File: Formula/t/tfenv.rb [hunk 2]
```diff
@@ -29,6 +29,8 @@ class Tfenv < Formula
 
   def install
     prefix.install %w[bin lib libexec share]
+    bin.env_script_all_files prefix/"libexec",
```
Comment (carlocab) [inline Formula/t/tfenv.rb]:
```suggestion
    bin.env_script_all_files libexec,
```

**Review by carlocab — APPROVED** [review]

File: Formula/t/tfenv.rb (hunk 2 above)
Comment (gromgit) [reply Formula/t/tfenv.rb]: 🤦‍♂️

**Review by carlocab — APPROVED** [review]
