### PR TITLE
lume: install resource bundle alongside binary

### LINKED ISSUE #1089: lume_lume.bundle missing from the brew install
Some functionality such as creating a new VM requires a lume_lume.bundle which is missing from the brew install. This causes build (and perhaps other functions?) to fail. 

lume/resource_bundle_accessor.swift:12: Fatal error: could not load resource bundle: from /opt/homebrew/bin/lume_lume.bundle or /private/tmp/lume-20260211-4524-h56vqx/cua-lume-v0.2.80/libs/lume/.build/arm64-apple-macosx/release/lume_lume.bundle

Seems like the bundle is in the release tarball.

### PR DESCRIPTION
**Pull request by f-trycua**
The `lume` formula currently only installs the binary but not the `lume_lume.bundle` resource bundle that is built alongside it. This bundle contains unattended install presets (e.g., `tahoe.yml`, `sequoia.yml`) required for VM creation.

Without the bundle, `lume build` crashes with:

```
lume/resource_bundle_accessor.swift:12: Fatal error: could not load resource bundle:
from /opt/homebrew/bin/lume_lume.bundle or ...
```

The fix adds `bin.install ".build/release/lume_lume.bundle"` so the bundle is placed next to the binary, where the Swift resource bundle accessor expects to find it.

Fixes https://github.com/trycua/cua/issues/1089

### CODE REVIEW

File: Formula/l/lume.rb [hunk 1]
```diff
@@ -28,6 +28,7 @@ def install
              "--entitlements", "resources/lume.local.entitlements", # Avoid SIGKILL with ad-hoc signing.
              ".build/release/lume"
       bin.install ".build/release/lume"
+      bin.install ".build/release/lume_lume.bundle"
```
Comment (carlocab) [inline Formula/l/lume.rb]: Since `lume_lume.bundle` appears to be data, and not an executable, it should not be in `bin`.
```suggestion
      libexec.install ".build/release/lume", ".build/release/lume_lume.bundle"
      bin.write_exec_script libexec/"lume"
```

File: Formula/l/lume.rb [hunk 2]
```diff
@@ -40,6 +41,9 @@ def install
   end
 
   test do
+    # Verify resource bundle is installed alongside the binary
+    assert_path_exists libexec/"lume_lume.bundle"
```
Comment (carlocab) [inline Formula/l/lume.rb]: Actually asserting the path exists isn't that helpful. We need to verify that the installed `lume_lume.bundle` is actually usable by `lume` (e.g. we didn't happen to install the wrong file at that location, or that the bundle wasn't corrupted by the bottling process, etc.)

**Review by carlocab — APPROVED** [review]

**Review by botantony — APPROVED** [review]
