### PR TITLE
leafnode: add plist files

### LINKED ISSUE #45402: leafnode - no plist file
Thanks to @DomT4 for the fix letting leafnode run. However, I can't get it to run as a service. I've run

 ```brew tap homebrew services```

and then tried

```brew services start leafnode```

but just get the error:

Error: Formula `leafnode` not installed, #startup_plist not implemented or no plist file found.

So I think I need a .plist.

### PR DESCRIPTION
**Pull request by rakkesh**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- leafnode: run on demand
- fetchnews: run every 30 minutes
- texpire: run every 7 hours

Closes [#45402](https://github.com/Homebrew/legacy-homebrew/issues/45402) (legacy-homebrew)

### CODE REVIEW

**Comment by rakkesh** [comment]
```
To have launchd start leafnode now and restart at startup:
  sudo brew services start leafnode
Or, if you don't want/need a background service you can just run:
  leafnode
```
I did not notice `sudo` in the above message earlier; seems to be auto-generated based on `sbin` path.

The following works as well,
`$ brew services start leafnode` 

I guess, I need to change `plist_options` as,
```rb
plist_options :startup => false, :manual => "leafnode"
```

File: Formula/leafnode.rb [hunk 1]
```diff
@@ -14,6 +14,89 @@ def install
                           "--with-user=#{ENV["USER"]}", "--with-group=admin",
                           "--sysconfdir=#{etc}/leafnode", "--with-spooldir=#{var}/spool/news/leafnode"
     system "make", "install"
+    (prefix/"homebrew.mxcl.fetchnews.plist").write fetchnews_plist
+    (prefix/"homebrew.mxcl.texpire.plist").write texpire_plist
+  end
+
+  def caveats; <<-EOS.undent
```
Comment (DomT4) [inline Formula/leafnode.rb]: Pretty sure we'll vomit these caveats automatically based on our core `plist` detection. Not the case?

File: Formula/leafnode.rb [hunk 2]
```diff
@@ -14,6 +14,89 @@ def install
...
+    <?xml version="1.0" encoding="UTF-8"?>
+    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+    <plist version="1.0">
+      <dict>
+        <key>OnDemand</key>
+        <true/>
+        <key>Label</key>
+        <string>#{plist_name}</string>
+        <key>Program</key>
+        <string>#{opt_sbin}/#{name}</string>
```
Comment (DomT4) [inline Formula/leafnode.rb]: Just use `leafnode` rather than `#{name}`. I'm never convinced `#{name}` usage is wildly obvious to people new to Ruby.

File: Formula/leafnode.rb (hunk 1 above)
Comment (rakkesh) [inline Formula/leafnode.rb]: This caveat does show up, in addition to `Homebrew` generated plist caveat for the main executable.

```
==> Caveats
For starting fetchnews and texpire, create links,
  ln -s /usr/local/opt/leafnode/homebrew.mxcl.{fetchnews,texpire}.plist ~/Library/LaunchAgents
And to start the services,
  launchctl load -w ~/Library/LaunchAgent/homebrew.mxcl.{fetchnews,texpire}.plist

To have launchd start leafnode now and restart at login:
  brew services start leafnode
Or, if you don't want/need a background service you can just run:
  leafnode
```

File: Formula/leafnode.rb (hunk 2 above)
Comment (rakkesh) [inline Formula/leafnode.rb]: I'll change this to a hardcoded value of formula's executable name.

File: Formula/leafnode.rb (hunk 1 above)
Comment (DomT4) [inline Formula/leafnode.rb]: I thought we produced a generic message where multiple `plists` exists? i.e. tell people to symlink with `*` rather than a direct path? Is that not the case? Maybe I'm misremembering 😅.

Comment (rakkesh) [inline Formula/leafnode.rb]: No, there is no generic message generated. I did not put `*` as `Homebrew` would probably take care of `leafnode.plist` when using `brew services`. Let me know, if you prefer `*.plist` to selecting of individual files here.

Without custom `caveats` here, `brew info` shows only the following content under `caveats`.
```
==> Caveats
To have launchd start leafnode now and restart at login:
  brew services start leafnode
Or, if you don't want/need a background service you can just run:
  leafnode
```

**Comment by rakkesh** [comment]
@DomT4 let me know, if you have any more concerns which need to be addressed.

**Comment by DomT4** [comment]
It smells like a bug that `brew services` can't handle multiple plists; our older system wasn't much better but it would at least nudge users to symlink all the `plists` in the Cellar to the correct location. The new `brew services` system _seems to_ completely ignore plists that don't match the formula name.

@MikeMcQuaid has done the majority of the work on `brew services` recently. Maybe Mike has some thoughts on the multiple plist situation.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid has done the majority of the work on brew services recently. Maybe Mike has some thoughts on the multiple plist situation.

`brew services` can, I believe, support multiple plists it just needs a bit more manual coaxing. @rakkesh Any chance you could take a look at it and try to produce a general solution for this (even if that's not using `brew services` for now)?

**Comment by rakkesh** [comment]
@MikeMcQuaid sure, I'll look into it.

**Comment by MikeMcQuaid** [comment]
@rakkesh Any news?

File: Formula/leafnode.rb (hunk 1 above)
Comment (MikeMcQuaid) [inline Formula/leafnode.rb]: I'm happy to ship this as-is if @DomT4 is but @rakkesh a PR to handle multiple plists would be great.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Thanks @rakkesh!
