### PR TITLE
checkmake: fix version output

### LINKED ISSUE #262426: checkmake --version not showing version
### `brew config` AND `brew doctor` output OR `brew gist-logs <formula>` link

the checkmake formula has been upgraded to the latest version v0.3.2.
However, `checkmake --version`does not print the version.

related upstream issue:

https://github.com/checkmake/checkmake/issues/233

output of `brew gist-logs checkmake`:
https://gist.github.com/obnoxxx/6463cb1c37a2e783cfe928f5871d2def 
```

### Verification

- [ ] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

latest checkmake is not reporting its version correctly:

As an upstream maintainer of chekmake, I wanted to check the output after the upgrade to the recent new upstream release.




### What happened (include all command output)?

```console
$ brew uninstall --force checkmake                                         
Uninstalling checkmake... (8 files, 7.7MB)
$ brew install checkmake 
✔︎ JSON API cask.jws.json                                                                                Downloaded   15.3MB/ 15.3MB
✔︎ JSON API formula.jws.json                                                                             Downloaded   32.0MB/ 32.0MB
==> Fetching downloads for: checkmake
✔︎ Bottle Manifest checkmake (0.3.2)                                                                     Downloaded    7.4KB/  7.4KB
.⠴ Bottle checkmake (0.3.2) #########                                                                    Downloading 454.7KB/  4.0M✔︎ Bottle checkmake (0.3.2)                                                                              Downloaded    4.0MB/  4.0MB
==> Pouring checkmake--0.3.2.arm64_tahoe.bottle.tar.gz
./🍺  /opt/homebrew/Cellar/checkmake/0.3.2: 8 files, 7.7MB
==> Running `brew cleanup checkmake`...
Disable this behaviour by setting `HOMEBREW_NO_INSTALL_CLEANUP=1`.
Hide these hints with `HOMEBREW_NO_ENV_HINTS=1` (see `man brew`).
$ checkmake --version
checkmake  built at 2026-01-10T17:01:00Z by Homebrew <homebrew@brew.sh> with go version go1.25.5 darwin/arm64
#259415 ```

### What did you expect to happen?

version should be printed. Like this:

```console
$ checkmake --version                                                      
checkmake 0.3.2 built at 2026-01-12T12:04:17Z by Homebrew <homebrew@brew.sh> with go version go1.25.5 darwin/arm64
$ 
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
* ` brew reinstall --force checkmake`
* `checkmake --version`
```

### PR DESCRIPTION
**Pull request by obnoxxx**
This fixes the output of `checkmake --version`after the latest update to checkmake v0.3.2.

Fixes: #262426 

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

File: Formula/c/checkmake.rb [hunk 1]
```diff
@@ -22,7 +22,7 @@ def install
     ENV["BUILDER_NAME"] = "Homebrew"
     ENV["BUILDER_EMAIL"] = "homebrew@brew.sh"
     ENV["PREFIX"] = prefix
-    system "make"
+    system "make", "VERSION=0.3.2"
```
Comment (chenrui333) [inline Formula/c/checkmake.rb]:
```suggestion
    system "make", "VERSION=#{version}"
```

File: Formula/c/checkmake.rb
Comment (chenrui333) [inline Formula/c/checkmake.rb:1]: you should also update test to reflect the build change

File: Formula/c/checkmake.rb [hunk 2]
```diff
@@ -4,7 +4,7 @@ class Checkmake < Formula
   url "https://github.com/checkmake/checkmake/archive/refs/tags/v0.3.2.tar.gz"
   sha256 "450412ba6500ef7c4c8a0150a5e1a3d2e76591ce9f37609bcbd5508298ad9bef"
   license "MIT"
-  head "https://github.com/checkmake/checkmake.git", branch: "main"
+  head "https://github.com/checkmake/checkmake.git", branch: "release-0.3"
```
Comment (SMillerDev) [inline Formula/c/checkmake.rb]: Why not main? That seems to be the development branch if you open the repo.

**Review by botantony — APPROVED** [review]

File: Formula/c/checkmake.rb (hunk 2 above)
Comment (chenrui333) [reply Formula/c/checkmake.rb]: right now, release-0.3 is not in sync with main?

image


cc @obnoxxx

Comment (SMillerDev) [reply Formula/c/checkmake.rb]: Sure, but main seems to be the repo `HEAD` and the other seems to be a release branch for 0.3. That's not what the `head` stanza is meant for.

Comment (obnoxxx) [reply Formula/c/checkmake.rb]: @SMillerDev wrote:

> Why not main? That seems to be the development branch if you open the repo.

correct: main is the development branch. But release-0.3 is the branch from which the 0.3.z patch releases are cut.

The v0.3.2 release tag is not found in the main branch.

So what would be the point of using main for creating packages for a stable version?

I was even surprised to see main there for the previous version's package.

Comment (obnoxxx) [reply Formula/c/checkmake.rb]: @SMillerDev  wrote:
> right now, release-0.3 is not in sync with main?
> image
> 
> cc @obnoxxx


Right, and it is not in sync on purpose.

main is for active development and release-0.3 is only for the 0.3.z patch release stream.

Comment (obnoxxx) [reply Formula/c/checkmake.rb]: @SMillerDev wrote:

> Sure, but main seems to be the repo `HEAD` and the other seems to be a release branch for 0.3. That's not what the `head` stanza is meant for.

OK. I can change it back to main, but I am
still not clear yet  why the package would care about the   development branch instead of a release branch or tag.
Just trying to understand.

Comment (obnoxxx) [reply Formula/c/checkmake.rb]: changed back to main. @SMillerDev

Comment (SMillerDev) [reply Formula/c/checkmake.rb]: > So what would be the point of using main for creating packages for a stable version?

This configuration is not for the normal package. This is for `brew install --head checkmake` which is supposed to install the latest development version, not a stable version.

Comment (obnoxxx) [reply Formula/c/checkmake.rb]: > > So what would be the point of using main for creating packages for a stable version?
> 
> This configuration is not for the normal package. This is for `brew install --head checkmake` which is supposed to install the latest development version, not a stable version.

Thanks @SMillerDev !

My intention was to fix the stable version package.
Is my approach wrong?

**Review by p-linnane — APPROVED** [review]
Added a version check in the test block so we avoid issues like this in the future.

File: Formula/c/checkmake.rb (hunk 2 above)
Comment (p-linnane) [reply Formula/c/checkmake.rb]: Changes to HEAD only affect users trying to install from the HEAD branch, not stable, so that change isn't necessary. The change you made by adding `VERSION=#{version}` is all you needed. You did it correctly.

**Comment by obnoxxx** [comment]
@p-linnane  wrote:
> Added a version check in the test block so we avoid issues like this in the future.

Oh, that is great! But note that `checkmake --version`outputs more than just the version.

**Comment by p-linnane** [comment]
That's fine. As long as the correct version is in the output, it will pass as evident in the green CI run.

**Review by stefanb — APPROVED** [review]
