### PR TITLE
pulseaudio: avoid wiping user configuration on upgrades

### LINKED ISSUE #224722: PulseAudio - No such file or directory "/opt/homebrew/Cellar/pulseaudio/17.0/etc/pulse/default.pa.d"
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Hello,
When creating a pulse file to include the default PulseAudio settings from Brew, PulseAudio fails to start with ``pulseaudio`` command with the output:


W: [] cli-command.c: stat('/opt/homebrew/Cellar/pulseaudio/17.0/etc/pulse/default.pa.d'): No such file or directory
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Reproduce PulseAudio from a Ubuntu Noble container to macOS.

### What happened (include all command output)?

PulseAudio fails to start with ``pulseaudio -k`` and ``pulseaudio --start`` command.

### What did you expect to happen?

PulseAudio starts as expected.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pulseaudio
mkdir -p "${HOME}/.config/pulse"
\echo -e ".include $(brew --prefix)/var/homebrew/linked/pulseaudio/etc/pulse/default.pa\nload-module module-native-protocol-tcp auth-anonymous=1" > "${HOME}/.config/pulse/default.pa"
pulseaudio -k
pulseaudio
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This installs user configuration into the formula prefix. Let's make it
install into `etc` instead.

Let's also create the `default.pa.d` directory to avoid unexpected error
messages.

Fixes #224722.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

File: Formula/p/pulseaudio.rb [hunk 1]
```diff
@@ -89,6 +89,14 @@ def install
     system "meson", "setup", "build", *args, *std_meson_args
     system "meson", "compile", "-C", "build", "--verbose"
     system "meson", "install", "-C", "build"
+
+    # Don't hardcode Cellar references in configuration files
+    inreplace etc.glob("pulse/*"), prefix, opt_prefix, audit_result: false
+
+    # Create the `default.pa.d` directory to avoid error messages like
+    # https://github.com/Homebrew/homebrew-core/issues/224722
+    (etc/"pulse/default.pa.d").mkpath
```
Comment (SMillerDev) [inline Formula/p/pulseaudio.rb:98]: Maybe we can create an issue upstream to create this in the build?
