### PR TITLE
temporal: fix HEAD install version string

### LINKED ISSUE #350: [Bug] Homebrew HEAD install has non-semver version string
### What are you really trying to do?

Install temporal cli from homebrew with `--head` and use it.

### Describe the bug

https://github.com/josh-berry/homebrew-core/blob/25aa0c4bb3512f98e0e7f6fd078686f2ea8bc4d7/Formula/t/temporal.rb#L22 sets the version string to `HEAD-#{sha}` which isn't semver so the server fails to parse it.

### Minimal Reproduction

$ brew install --head temporal
$ temporal workflow query -w 33c33110-8a30-4f8c-a5e9-cbbbe1012376_9 --type getStatus
Error: query workflow failed: Unable to parse client version: No Major.Minor.Patch elements found
('export TEMPORAL_CLI_SHOW_STACKS=1' to see stack traces)

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

### PR DESCRIPTION
**Pull request by chaptersix**
When installing with `--head`, use a valid semver version (`0.0.0-HEAD+sha`) instead of the non-semver HEAD string. This fixes an issue where the Temporal server fails to parse the client version.

**Before:** `temporal version HEAD-f843757`
**After:** `temporal version 0.0.0-HEAD+f843757`

Fixes temporalio/cli#350

### CODE REVIEW

File: Formula/t/temporal.rb [hunk 1]
```diff
@@ -23,7 +23,12 @@ class Temporal < Formula
   depends_on "go" => :build
 
   def install
-    ldflags = "-s -w -X github.com/temporalio/cli/internal/temporalcli.Version=#{version}"
+    v = if build.head?
+      "0.0.0-HEAD+#{Utils.git_short_head}"
+    else
+      version.to_s
+    end
```
Comment (chenrui333) [inline Formula/t/temporal.rb]: is this good enough?
```suggestion
    v = build.head? ? "0.0.0-HEAD+#{Utils.git_short_head}" : version.to_s
```

**Review by botantony — APPROVED** [review]

File: Formula/t/temporal.rb [hunk 2]
```diff
@@ -39,7 +40,8 @@ def install
 
   test do
     run_output = shell_output("#{bin}/temporal --version")
-    assert_match "temporal version #{version}", run_output
+    expected_version = build.head? ? "0.0.0-HEAD" : version.to_s
+    assert_match "temporal version #{expected_version}", run_output
```
Comment (chenrui333) [inline Formula/t/temporal.rb]: actually, we dont test head build in test, might be better to remove it as with other formulae

**Review by botantony — APPROVED** [review]
