### PR TITLE
x265: fix source tarball

### LINKED ISSUE #196321: Wrong x265 version number
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 5 days ago
Core tap JSON: 01 Nov 03:49 UTC
Core cask tap JSON: 01 Nov 03:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.cloud.tencent.com/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  dozer

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  neofetch
  openssl@1.1

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
Untap them with `brew untap`.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMoltenVK.dylib
  /usr/local/lib/libSPIRV-Tools-shared.dylib
  /usr/local/lib/libVkLayer_api_dump.dylib
  /usr/local/lib/libVkLayer_khronos_profiles.dylib
  /usr/local/lib/libVkLayer_khronos_shader_object.dylib
  /usr/local/lib/libVkLayer_khronos_synchronization2.dylib
  /usr/local/lib/libVkLayer_khronos_validation.dylib
  /usr/local/lib/libVkLayer_screenshot.dylib
  /usr/local/lib/libaacs.dylib
  /usr/local/lib/libavcodec.61.11.100.dylib
  /usr/local/lib/libavdevice.61.2.100.dylib
  /usr/local/lib/libavfilter.10.2.102.dylib
  /usr/local/lib/libavformat.61.5.101.dylib
  /usr/local/lib/libavutil.59.32.100.dylib
  /usr/local/lib/libbestsource.dylib
  /usr/local/lib/libbm3dcpu.dylib
  /usr/local/lib/libdxcompiler.3.7.dylib
  /usr/local/lib/libdxcompiler.dylib
  /usr/local/lib/libeedi2.dylib
  /usr/local/lib/libffms2.5.dylib
  /usr/local/lib/libfmtconv.dylib
  /usr/local/lib/libknlmeanscl.dylib
  /usr/local/lib/liblsmash.dylib
  /usr/local/lib/libltdl.7.dylib
  /usr/local/lib/libnnedi3.dylib
  /usr/local/lib/libonnxruntime.1.17.1.dylib
  /usr/local/lib/libonnxruntime.1.19.2.dylib
  /usr/local/lib/libsangnom.0.dylib
  /usr/local/lib/libshaderc_shared.1.dylib
  /usr/local/lib/libspirv-cross-c-shared.0.50.0.dylib
  /usr/local/lib/libspirv-cross-c-shared.0.61.0.dylib
  /usr/local/lib/libswresample.5.2.100.dylib
  /usr/local/lib/libswscale.8.2.100.dylib
  /usr/local/lib/libvapoursynth-script.0.dylib
  /usr/local/lib/libvapoursynth.dylib
  /usr/local/lib/libvulkan.1.3.231.dylib
  /usr/local/lib/libvulkan.1.3.290.dylib
  /usr/local/lib/libwavelet.dylib
  /usr/local/lib/libx265.213.dylib
  /usr/local/lib/libxxhash.0.8.2.dylib
  /usr/local/lib/libzimg.2.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected header files:
  /usr/local/include/CL/sycl_gtx_compatibility.h
  /usr/local/include/LLVMSPIRVLib/LLVMSPIRVLib.h
  /usr/local/include/LLVMSPIRVLib/LLVMSPIRVOpts.h
  /usr/local/include/MoltenVK/mvk_config.h
  /usr/local/include/MoltenVK/mvk_datatypes.h
  /usr/local/include/MoltenVK/mvk_deprecated_api.h
  /usr/local/include/MoltenVK/mvk_private_api.h
  /usr/local/include/MoltenVK/mvk_vulkan.h
  /usr/local/include/MoltenVK/vk_mvk_moltenvk.h
  /usr/local/include/SYCL/access.h
  /usr/local/include/SYCL/accessor.h
  /usr/local/include/SYCL/accessors/buffer.h
  /usr/local/include/SYCL/accessors/buffer_base.h
  /usr/local/include/SYCL/accessors/buffer_device.h
  /usr/local/include/SYCL/accessors/buffer_host.h
  /usr/local/include/SYCL/accessors/device_reference.h
  /usr/local/include/SYCL/accessors/local.h
  /usr/local/include/SYCL/atomic.h
  /usr/local/include/SYCL/buffer.h
  /usr/local/include/SYCL/buffer_base.h
  /usr/local/include/SYCL/command_group.h
  /usr/local/include/SYCL/context.h
  /usr/local/include/SYCL/detail/common.h
  /usr/local/include/SYCL/detail/counter.h
  /usr/local/include/SYCL/detail/data_ref.h
  /usr/local/include/SYCL/detail/debug.h
  /usr/local/include/SYCL/detail/error_code.h
  /usr/local/include/SYCL/detail/flow_control.h
  /usr/local/include/SYCL/detail/function_traits.h
  /usr/local/include/SYCL/detail/kernel_name.h
  /usr/local/include/SYCL/detail/msvc_version.h
  /usr/local/include/SYCL/detail/opencl.h
  /usr/local/include/SYCL/detail/point_ref.h
  /usr/local/include/SYCL/detail/ptr_or_val.h
  /usr/local/include/SYCL/detail/src_handlers/invoke_source.h
  /usr/local/include/SYCL/detail/src_handlers/issue_command.h
  /usr/local/include/SYCL/detail/src_handlers/kernel_source.h
  /usr/local/include/SYCL/detail/src_handlers/register_resource.h
  /usr/local/include/SYCL/detail/synchronizer.h
  /usr/local/include/SYCL/device.h
  /usr/local/include/SYCL/device_selector.h
  /usr/local/include/SYCL/error_handler.h
  /usr/local/include/SYCL/event.h
  /usr/local/include/SYCL/exception.h
  /usr/local/include/SYCL/functions/common.h
  /usr/local/include/SYCL/handler.h
  /usr/local/include/SYCL/handler_event.h
  /usr/local/include/SYCL/info.h
  /usr/local/include/SYCL/kernel.h
  /usr/local/include/SYCL/param_traits.h
  /usr/local/include/SYCL/platform.h
  /usr/local/include/SYCL/program.h
  /usr/local/include/SYCL/queue.h
  /usr/local/include/SYCL/ranges.h
  /usr/local/include/SYCL/ranges/id.h
  /usr/local/include/SYCL/ranges/item.h
  /usr/local/include/SYCL/ranges/nd_item.h
  /usr/local/include/SYCL/ranges/nd_range.h
  /usr/local/include/SYCL/ranges/point.h
  /usr/local/include/SYCL/ranges/range.h
  /usr/local/include/SYCL/refc.h
  /usr/local/include/SYCL/vectors/base.h
  /usr/local/include/SYCL/vectors/cl_type.h
  /usr/local/include/SYCL/vectors/cl_vec.h
  /usr/local/include/SYCL/vectors/helpers.h
  /usr/local/include/SYCL/vectors/swizzled_vec.h
  /usr/local/include/SYCL/vectors/type_string.h
  /usr/local/include/SYCL/vectors/vec.h
  /usr/local/include/SYCL/vectors/vec_members.h
  /usr/local/include/SYCL/workitem_functions.h
  /usr/local/include/dxc/WinAdapter.h
  /usr/local/include/dxc/dxcapi.h
  /usr/local/include/f3kdb/f3kdb.h
  /usr/local/include/f3kdb/f3kdb_enums.h
  /usr/local/include/f3kdb/f3kdb_params.h
  /usr/local/include/ffms.h
  /usr/local/include/ffmscompat.h
  /usr/local/include/fftw3.h
  /usr/local/include/glslang/Include/ResourceLimits.h
  /usr/local/include/glslang/Include/glslang_c_interface.h
  /usr/local/include/glslang/Include/glslang_c_shader_types.h
  /usr/local/include/glslang/MachineIndependent/Versions.h
  /usr/local/include/glslang/Public/ResourceLimits.h
  /usr/local/include/glslang/Public/ShaderLang.h
  /usr/local/include/glslang/Public/resource_limits_c.h
  /usr/local/include/glslang/SPIRV/GlslangToSpv.h
  /usr/local/include/glslang/SPIRV/Logger.h
  /usr/local/include/glslang/SPIRV/SPVRemapper.h
  /usr/local/include/glslang/SPIRV/disassemble.h
  /usr/local/include/glslang/build_info.h
  /usr/local/include/google/protobuf/any.h
  /usr/local/include/google/protobuf/any.pb.h
  /usr/local/include/google/protobuf/api.pb.h
  /usr/local/include/google/protobuf/arena.h
  /usr/local/include/google/protobuf/arena_impl.h
  /usr/local/include/google/protobuf/arenastring.h
  /usr/local/include/google/protobuf/arenaz_sampler.h
  /usr/local/include/google/protobuf/compiler/code_generator.h
  /usr/local/include/google/protobuf/compiler/command_line_interface.h
  /usr/local/include/google/protobuf/compiler/cpp/cpp_generator.h
  /usr/local/include/google/protobuf/compiler/cpp/file.h
  /usr/local/include/google/protobuf/compiler/cpp/generator.h
  /usr/local/include/google/protobuf/compiler/cpp/helpers.h
  /usr/local/include/google/protobuf/compiler/cpp/names.h
  /usr/local/include/google/protobuf/compiler/csharp/csharp_doc_comment.h
  /usr/local/include/google/protobuf/compiler/csharp/csharp_generator.h
  /usr/local/include/google/protobuf/compiler/csharp/csharp_names.h
  /usr/local/include/google/protobuf/compiler/csharp/csharp_options.h
  /usr/local/include/google/protobuf/compiler/importer.h
  /usr/local/include/google/protobuf/compiler/java/generator.h
  /usr/local/include/google/protobuf/compiler/java/java_generator.h
  /usr/local/include/google/protobuf/compiler/java/kotlin_generator.h
  /usr/local/include/google/protobuf/compiler/java/names.h
  /usr/local/include/google/protobuf/compiler/objectivec/objectivec_generator.h
  /usr/local/include/google/protobuf/compiler/objectivec/objectivec_helpers.h
  /usr/local/include/google/protobuf/compiler/parser.h
  /usr/local/include/google/protobuf/compiler/php/php_generator.h
  /usr/local/include/google/protobuf/compiler/plugin.h
  /usr/local/include/google/protobuf/compiler/plugin.pb.h
  /usr/local/include/google/protobuf/compiler/python/generator.h
  /usr/local/include/google/protobuf/compiler/python/pyi_generator.h
  /usr/local/include/google/protobuf/compiler/python/python_generator.h
  /usr/local/include/google/protobuf/compiler/ruby/ruby_generator.h
  /usr/local/include/google/protobuf/descriptor.h
  /usr/local/include/google/protobuf/descriptor.pb.h
  /usr/local/include/google/protobuf/descriptor_database.h
  /usr/local/include/google/protobuf/duration.pb.h
  /usr/local/include/google/protobuf/dynamic_message.h
  /usr/local/include/google/protobuf/empty.pb.h
  /usr/local/include/google/protobuf/endian.h
  /usr/local/include/google/protobuf/explicitly_constructed.h
  /usr/local/include/google/protobuf/extension_set.h
  /usr/local/include/google/protobuf/extension_set_inl.h
  /usr/local/include/google/protobuf/field_access_listener.h
  /usr/local/include/google/protobuf/field_mask.pb.h
  /usr/local/include/google/protobuf/generated_enum_reflection.h
  /usr/local/include/google/protobuf/generated_enum_util.h
  /usr/local/include/google/protobuf/generated_message_bases.h
  /usr/local/include/google/protobuf/generated_message_reflection.h
  /usr/local/include/google/protobuf/generated_message_tctable_decl.h
  /usr/local/include/google/protobuf/generated_message_tctable_impl.h
  /usr/local/include/google/protobuf/generated_message_util.h
  /usr/local/include/google/protobuf/has_bits.h
  /usr/local/include/google/protobuf/implicit_weak_message.h
  /usr/local/include/google/protobuf/inlined_string_field.h
  /usr/local/include/google/protobuf/io/coded_stream.h
  /usr/local/include/google/protobuf/io/gzip_stream.h
  /usr/local/include/google/protobuf/io/io_win32.h
  /usr/local/include/google/protobuf/io/printer.h
  /usr/local/include/google/protobuf/io/strtod.h
  /usr/local/include/google/protobuf/io/tokenizer.h
  /usr/local/include/google/protobuf/io/zero_copy_stream.h
  /usr/local/include/google/protobuf/io/zero_copy_stream_impl.h
  /usr/local/include/google/protobuf/io/zero_copy_stream_impl_lite.h
  /usr/local/include/google/protobuf/map.h
  /usr/local/include/google/protobuf/map_entry.h
  /usr/local/include/google/protobuf/map_entry_lite.h
  /usr/local/include/google/protobuf/map_field.h
  /usr/local/include/google/protobuf/map_field_inl.h
  /usr/local/include/google/protobuf/map_field_lite.h
  /usr/local/include/google/protobuf/map_type_handler.h
  /usr/local/include/google/protobuf/message.h
  /usr/local/include/google/protobuf/message_lite.h
  /usr/local/include/google/protobuf/metadata.h
  /usr/local/include/google/protobuf/metadata_lite.h
  /usr/local/include/google/protobuf/parse_context.h
  /usr/local/include/google/protobuf/port.h
  /usr/local/include/google/protobuf/reflection.h
  /usr/local/include/google/protobuf/reflection_ops.h
  /usr/local/include/google/protobuf/repeated_field.h
  /usr/local/include/google/protobuf/repeated_ptr_field.h
  /usr/local/include/google/protobuf/service.h
  /usr/local/include/google/protobuf/source_context.pb.h
  /usr/local/include/google/protobuf/struct.pb.h
  /usr/local/include/google/protobuf/stubs/bytestream.h
  /usr/local/include/google/protobuf/stubs/callback.h
  /usr/local/include/google/protobuf/stubs/casts.h
  /usr/local/include/google/protobuf/stubs/common.h
  /usr/local/include/google/protobuf/stubs/hash.h
  /usr/local/include/google/protobuf/stubs/logging.h
  /usr/local/include/google/protobuf/stubs/macros.h
  /usr/local/include/google/protobuf/stubs/map_util.h
  /usr/local/include/google/protobuf/stubs/mutex.h
  /usr/local/include/google/protobuf/stubs/once.h
  /usr/local/include/google/protobuf/stubs/platform_macros.h
  /usr/local/include/google/protobuf/stubs/port.h
  /usr/local/include/google/protobuf/stubs/status.h
  /usr/local/include/google/protobuf/stubs/stl_util.h
  /usr/local/include/google/protobuf/stubs/stringpiece.h
  /usr/local/include/google/protobuf/stubs/strutil.h
  /usr/local/include/google/protobuf/stubs/template_util.h
  /usr/local/include/google/protobuf/text_format.h
  /usr/local/include/google/protobuf/timestamp.pb.h
  /usr/local/include/google/protobuf/type.pb.h
  /usr/local/include/google/protobuf/unknown_field_set.h
  /usr/local/include/google/protobuf/util/delimited_message_util.h
  /usr/local/include/google/protobuf/util/field_comparator.h
  /usr/local/include/google/protobuf/util/field_mask_util.h
  /usr/local/include/google/protobuf/util/json_util.h
  /usr/local/include/google/protobuf/util/message_differencer.h
  /usr/local/include/google/protobuf/util/time_util.h
  /usr/local/include/google/protobuf/util/type_resolver.h
  /usr/local/include/google/protobuf/util/type_resolver_util.h
  /usr/local/include/google/protobuf/wire_format.h
  /usr/local/include/google/protobuf/wire_format_lite.h
  /usr/local/include/google/protobuf/wrappers.pb.h
  /usr/local/include/lemon/adaptors.h
  /usr/local/include/lemon/arg_parser.h
  /usr/local/include/lemon/assert.h
  /usr/local/include/lemon/bellman_ford.h
  /usr/local/include/lemon/bfs.h
  /usr/local/include/lemon/bin_heap.h
  /usr/local/include/lemon/binomial_heap.h
  /usr/local/include/lemon/bits/alteration_notifier.h
  /usr/local/include/lemon/bits/array_map.h
  /usr/local/include/lemon/bits/bezier.h
  /usr/local/include/lemon/bits/default_map.h
  /usr/local/include/lemon/bits/edge_set_extender.h
  /usr/local/include/lemon/bits/enable_if.h
  /usr/local/include/lemon/bits/graph_adaptor_extender.h
  /usr/local/include/lemon/bits/graph_extender.h
  /usr/local/include/lemon/bits/lock.h
  /usr/local/include/lemon/bits/map_extender.h
  /usr/local/include/lemon/bits/path_dump.h
  /usr/local/include/lemon/bits/solver_bits.h
  /usr/local/include/lemon/bits/traits.h
  /usr/local/include/lemon/bits/variant.h
  /usr/local/include/lemon/bits/vector_map.h
  /usr/local/include/lemon/bits/windows.h
  /usr/local/include/lemon/bucket_heap.h
  /usr/local/include/lemon/capacity_scaling.h
  /usr/local/include/lemon/cbc.h
  /usr/local/include/lemon/christofides_tsp.h
  /usr/local/include/lemon/circulation.h
  /usr/local/include/lemon/clp.h
  /usr/local/include/lemon/color.h
  /usr/local/include/lemon/concept_check.h
  /usr/local/include/lemon/concepts/bpgraph.h
  /usr/local/include/lemon/concepts/digraph.h
  /usr/local/include/lemon/concepts/graph.h
  /usr/local/include/lemon/concepts/graph_components.h
  /usr/local/include/lemon/concepts/heap.h
  /usr/local/include/lemon/concepts/maps.h
  /usr/local/include/lemon/concepts/path.h
  /usr/local/include/lemon/config.h
  /usr/local/include/lemon/connectivity.h
  /usr/local/include/lemon/core.h
  /usr/local/include/lemon/cost_scaling.h
  /usr/local/include/lemon/counter.h
  /usr/local/include/lemon/cplex.h
  /usr/local/include/lemon/cycle_canceling.h
  /usr/local/include/lemon/dfs.h
  /usr/local/include/lemon/dheap.h
  /usr/local/include/lemon/dijkstra.h
  /usr/local/include/lemon/dim2.h
  /usr/local/include/lemon/dimacs.h
  /usr/local/include/lemon/edge_set.h
  /usr/local/include/lemon/edmonds_karp.h
  /usr/local/include/lemon/elevator.h
  /usr/local/include/lemon/error.h
  /usr/local/include/lemon/euler.h
  /usr/local/include/lemon/fib_heap.h
  /usr/local/include/lemon/fractional_matching.h
  /usr/local/include/lemon/full_graph.h
  /usr/local/include/lemon/glpk.h
  /usr/local/include/lemon/gomory_hu.h
  /usr/local/include/lemon/graph_to_eps.h
  /usr/local/include/lemon/greedy_tsp.h
  /usr/local/include/lemon/grid_graph.h
  /usr/local/include/lemon/grosso_locatelli_pullan_mc.h
  /usr/local/include/lemon/hao_orlin.h
  /usr/local/include/lemon/hartmann_orlin_mmc.h
  /usr/local/include/lemon/howard_mmc.h
  /usr/local/include/lemon/hypercube_graph.h
  /usr/local/include/lemon/insertion_tsp.h
  /usr/local/include/lemon/karp_mmc.h
  /usr/local/include/lemon/kruskal.h
  /usr/local/include/lemon/lgf_reader.h
  /usr/local/include/lemon/lgf_writer.h
  /usr/local/include/lemon/list_graph.h
  /usr/local/include/lemon/lp.h
  /usr/local/include/lemon/lp_base.h
  /usr/local/include/lemon/lp_skeleton.h
  /usr/local/include/lemon/maps.h
  /usr/local/include/lemon/matching.h
  /usr/local/include/lemon/math.h
  /usr/local/include/lemon/max_cardinality_search.h
  /usr/local/include/lemon/min_cost_arborescence.h
  /usr/local/include/lemon/nagamochi_ibaraki.h
  /usr/local/include/lemon/nauty_reader.h
  /usr/local/include/lemon/nearest_neighbor_tsp.h
  /usr/local/include/lemon/network_simplex.h
  /usr/local/include/lemon/opt2_tsp.h
  /usr/local/include/lemon/pairing_heap.h
  /usr/local/include/lemon/path.h
  /usr/local/include/lemon/planarity.h
  /usr/local/include/lemon/preflow.h
  /usr/local/include/lemon/quad_heap.h
  /usr/local/include/lemon/radix_heap.h
  /usr/local/include/lemon/radix_sort.h
  /usr/local/include/lemon/random.h
  /usr/local/include/lemon/smart_graph.h
  /usr/local/include/lemon/soplex.h
  /usr/local/include/lemon/static_graph.h
  /usr/local/include/lemon/suurballe.h
  /usr/local/include/lemon/time_measure.h
  /usr/local/include/lemon/tolerance.h
  /usr/local/include/lemon/unionfind.h
  /usr/local/include/lsmash.h
  /usr/local/include/ltdl.h
  /usr/local/include/obuparse.h
  /usr/local/include/shaderc/env.h
  /usr/local/include/shaderc/shaderc.h
  /usr/local/include/shaderc/status.h
  /usr/local/include/shaderc/visibility.h
  /usr/local/include/spirv-tools/libspirv.h
  /usr/local/include/spirv/1.0/GLSL.std.450.h
  /usr/local/include/spirv/1.0/OpenCL.std.h
  /usr/local/include/spirv/1.0/spirv.h
  /usr/local/include/spirv/1.1/GLSL.std.450.h
  /usr/local/include/spirv/1.1/OpenCL.std.h
  /usr/local/include/spirv/1.1/spirv.h
  /usr/local/include/spirv/1.2/GLSL.std.450.h
  /usr/local/include/spirv/1.2/OpenCL.std.h
  /usr/local/include/spirv/1.2/spirv.h
  /usr/local/include/spirv/unified1/AMD_gcn_shader.h
  /usr/local/include/spirv/unified1/AMD_shader_ballot.h
  /usr/local/include/spirv/unified1/AMD_shader_explicit_vertex_parameter.h
  /usr/local/include/spirv/unified1/AMD_shader_trinary_minmax.h
  /usr/local/include/spirv/unified1/DebugInfo.h
  /usr/local/include/spirv/unified1/GLSL.std.450.h
  /usr/local/include/spirv/unified1/NonSemanticClspvReflection.h
  /usr/local/include/spirv/unified1/NonSemanticDebugBreak.h
  /usr/local/include/spirv/unified1/NonSemanticDebugPrintf.h
  /usr/local/include/spirv/unified1/NonSemanticShaderDebugInfo100.h
  /usr/local/include/spirv/unified1/NonSemanticVkspReflection.h
  /usr/local/include/spirv/unified1/OpenCL.std.h
  /usr/local/include/spirv/unified1/OpenCLDebugInfo100.h
  /usr/local/include/spirv/unified1/spirv.h
  /usr/local/include/spirv_cross/GLSL.std.450.h
  /usr/local/include/spirv_cross/spirv.h
  /usr/local/include/spirv_cross/spirv_cross_c.h
  /usr/local/include/vapoursynth/VSConstants4.h
  /usr/local/include/vapoursynth/VSHelper.h
  /usr/local/include/vapoursynth/VSHelper4.h
  /usr/local/include/vapoursynth/VSScript.h
  /usr/local/include/vapoursynth/VSScript4.h
  /usr/local/include/vapoursynth/VapourSynth.h
  /usr/local/include/vapoursynth/VapourSynth4.h
  /usr/local/include/vk_video/vulkan_video_codec_av1std.h
  /usr/local/include/vk_video/vulkan_video_codec_av1std_decode.h
  /usr/local/include/vk_video/vulkan_video_codec_h264std.h
  /usr/local/include/vk_video/vulkan_video_codec_h264std_decode.h
  /usr/local/include/vk_video/vulkan_video_codec_h264std_encode.h
  /usr/local/include/vk_video/vulkan_video_codec_h265std.h
  /usr/local/include/vk_video/vulkan_video_codec_h265std_decode.h
  /usr/local/include/vk_video/vulkan_video_codec_h265std_encode.h
  /usr/local/include/vk_video/vulkan_video_codecs_common.h
  /usr/local/include/vulkan/utility/vk_format_utils.h
  /usr/local/include/vulkan/vk_enum_string_helper.h
  /usr/local/include/vulkan/vk_icd.h
  /usr/local/include/vulkan/vk_layer.h
  /usr/local/include/vulkan/vk_platform.h
  /usr/local/include/vulkan/vulkan.h
  /usr/local/include/vulkan/vulkan_android.h
  /usr/local/include/vulkan/vulkan_beta.h
  /usr/local/include/vulkan/vulkan_core.h
  /usr/local/include/vulkan/vulkan_directfb.h
  /usr/local/include/vulkan/vulkan_fuchsia.h
  /usr/local/include/vulkan/vulkan_ggp.h
  /usr/local/include/vulkan/vulkan_ios.h
  /usr/local/include/vulkan/vulkan_macos.h
  /usr/local/include/vulkan/vulkan_metal.h
  /usr/local/include/vulkan/vulkan_screen.h
  /usr/local/include/vulkan/vulkan_vi.h
  /usr/local/include/vulkan/vulkan_wayland.h
  /usr/local/include/vulkan/vulkan_win32.h
  /usr/local/include/vulkan/vulkan_xcb.h
  /usr/local/include/vulkan/vulkan_xlib.h
  /usr/local/include/vulkan/vulkan_xlib_xrandr.h
  /usr/local/include/wauxlib.h
  /usr/local/include/wavelet.h
  /usr/local/include/wavelib.h
  /usr/local/include/x265.h
  /usr/local/include/x265_config.h
  /usr/local/include/xxh3.h
  /usr/local/include/xxhash.h
  /usr/local/include/zimg.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libeedi2.la
  /usr/local/lib/libffms2.la
  /usr/local/lib/libfftw3.la
  /usr/local/lib/libfmtconv.la
  /usr/local/lib/libltdl.la
  /usr/local/lib/libnnedi3.la
  /usr/local/lib/libsangnom.la
  /usr/local/lib/libvapoursynth-script.la
  /usr/local/lib/libvapoursynth.la
  /usr/local/lib/libzimg.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/LLVMSPIRVLib.pc
  /usr/local/lib/pkgconfig/SPIRV-Headers.pc
  /usr/local/lib/pkgconfig/SPIRV-Tools-shared.pc
  /usr/local/lib/pkgconfig/SPIRV-Tools.pc
  /usr/local/lib/pkgconfig/ffms2.pc
  /usr/local/lib/pkgconfig/fftw3.pc
  /usr/local/lib/pkgconfig/lemon.pc
  /usr/local/lib/pkgconfig/libavcodec.pc
  /usr/local/lib/pkgconfig/libavdevice.pc
  /usr/local/lib/pkgconfig/libavfilter.pc
  /usr/local/lib/pkgconfig/libavformat.pc
  /usr/local/lib/pkgconfig/libavutil.pc
  /usr/local/lib/pkgconfig/liblsmash.pc
  /usr/local/lib/pkgconfig/libonnxruntime.pc
  /usr/local/lib/pkgconfig/libswresample.pc
  /usr/local/lib/pkgconfig/libswscale.pc
  /usr/local/lib/pkgconfig/libxxhash.pc
  /usr/local/lib/pkgconfig/protobuf-lite.pc
  /usr/local/lib/pkgconfig/protobuf.pc
  /usr/local/lib/pkgconfig/shaderc.pc
  /usr/local/lib/pkgconfig/spirv-cross-c-shared.pc
  /usr/local/lib/pkgconfig/spirv-cross-c.pc
  /usr/local/lib/pkgconfig/vapoursynth-script.pc
  /usr/local/lib/pkgconfig/vapoursynth.pc
  /usr/local/lib/pkgconfig/vulkan.pc
  /usr/local/lib/pkgconfig/x265.pc
  /usr/local/lib/pkgconfig/zimg.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libGenericCodeGen.a
  /usr/local/lib/libHLSL.a
  /usr/local/lib/libLLVMSPIRVLib.a
  /usr/local/lib/libMachineIndependent.a
  /usr/local/lib/libOGLCompiler.a
  /usr/local/lib/libOSDependent.a
  /usr/local/lib/libSPIRV-Tools-diff.a
  /usr/local/lib/libSPIRV-Tools-link.a
  /usr/local/lib/libSPIRV-Tools-lint.a
  /usr/local/lib/libSPIRV-Tools-opt.a
  /usr/local/lib/libSPIRV-Tools-reduce.a
  /usr/local/lib/libSPIRV-Tools.a
  /usr/local/lib/libSPIRV.a
  /usr/local/lib/libSPVRemapper.a
  /usr/local/lib/libavcodec.a
  /usr/local/lib/libavdevice.a
  /usr/local/lib/libavfilter.a
  /usr/local/lib/libavformat.a
  /usr/local/lib/libavutil.a
  /usr/local/lib/libemon.a
  /usr/local/lib/libffms2.a
  /usr/local/lib/libfftw3.a
  /usr/local/lib/libglslang-default-resource-limits.a
  /usr/local/lib/libglslang.a
  /usr/local/lib/liblsmash.a
  /usr/local/lib/libltdl.a
  /usr/local/lib/libobuparse.a
  /usr/local/lib/libprotobuf-lite.a
  /usr/local/lib/libprotobuf.a
  /usr/local/lib/libprotoc.a
  /usr/local/lib/libshaderc.a
  /usr/local/lib/libshaderc_combined.a
  /usr/local/lib/libshaderc_util.a
  /usr/local/lib/libspirv-cross-c.a
  /usr/local/lib/libspirv-cross-core.a
  /usr/local/lib/libspirv-cross-cpp.a
  /usr/local/lib/libspirv-cross-glsl.a
  /usr/local/lib/libspirv-cross-hlsl.a
  /usr/local/lib/libspirv-cross-msl.a
  /usr/local/lib/libspirv-cross-reflect.a
  /usr/local/lib/libspirv-cross-util.a
  /usr/local/lib/libswresample.a
  /usr/local/lib/libswscale.a
  /usr/local/lib/libsycl-gtx.a
  /usr/local/lib/libvapoursynth-script.a
  /usr/local/lib/libvapoursynth.a
  /usr/local/lib/libwauxlib.a
  /usr/local/lib/libwavelib.a
  /usr/local/lib/libx265.a
  /usr/local/lib/libx265_main.a
  /usr/local/lib/libzimg.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  vapoursynth
  dotnet
  x264
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install x265 version 4.0 for video encoding.

### What happened (include all command output)?

Although brew tells it's 4.0, in fact the installed version is 3.6.
```
/opt/homebrew/Cellar/x265/4.0/bin/x265 -V
x265 [info]: HEVC encoder version 3.6+1-aa7f602f7
x265 [info]: build info [Mac OS X][clang 16.0.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: NEON Neon_DotProd
```

The same problem have existed since (maybe earlier than) 3.6.

### What did you expect to happen?

The correct version should be 4.0, and using CPU capabilities I8MM in addition.
Here's the  output of manually compiled 4.0 (with some personal modify)
```
x265 -V                                
x265 [info]: HEVC encoder version 4.0-YUYGFGG
x265 [info]: build info [Mac OS X][clang 19.1.0][64 bit]  8bit+10bit+12bit
x265 [info]: (lsmash 2.16.1)
x265 [info]: using cpu capabilities: NEON Neon_DotProd Neon_I8MM
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
brew install x265
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Not sure what BitBucket has been serving us, but it doesn't appear to be
the correct tarball at all.

Closes #196321.

### CODE REVIEW

File: Formula/x/x265.rb [hunk 1]
```diff
@@ -22,6 +23,7 @@ class X265 < Formula
   end
 
   def install
+    ENV.runtime_cpu_detection
```
Comment (carlocab) [inline Formula/x/x265.rb:26]: Haven't checked if this is actually accurate, but the build fails without it, so 🤞

Seems like it should be though.

**Review by daeho-ro — APPROVED** [review]
