### PR TITLE
ansible-lint: use same version of `ansible-core` as `ansible`

### LINKED ISSUE #173128: Problem with ansible-lint formula
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
MyMac:facts-aap user1$ brew doctor
Your system is ready to brew.
MyMac:facts-aap user1$ brew config
HOMEBREW_VERSION: 4.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fdb0d53990d3e62e25325a6f89dbb769e84a530
Last commit: 3 days ago
Core tap JSON: 29 May 13:01 UTC
Core cask tap JSON: 29 May 13:01 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.45.1 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
MyMac:facts-aap user1$
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

When trying to run ansible-lint, it shows an incompatibility between the installed ansible formula (2.16.7) and installed ansible-lint formula (24.5.0), both were installed via brew. Linter fails to execute, output provided below.

### What happened (include all command output)?

`MyMac:facts-aap user1$ ansible-lint
Ansible CLI (2.16.7) and python module (2.16.6) versions do not match. This indicates a broken execution environment.`

### What did you expect to happen?

I expected ansible-lint to run and check ansible content in the directory recursively.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ansible ansible-lint
```

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

fixes #173128

image

### CODE REVIEW

File: Formula/a/ansible-lint.rb [hunk 1]
```diff
@@ -182,6 +184,12 @@ def install
   end
 
   test do
+    output = shell_output("#{bin}/ansible-lint --version")
+    ansible_lint_core_version = output.match(/ansible-core:([\d.]+)/)[1]
+
+    ansible = Formula["ansible"].opt_bin/"ansible"
+    assert_match "[core #{ansible_lint_core_version}]", shell_output("#{ansible} --version")
+
```
Comment (chenrui333) [inline Formula/a/ansible-lint.rb:192]: this is the best way I can think of to make sure ansible-core versions in sync between ansible and ansible-lint

**Review by fxcoudert — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
