### PR TITLE
haskell-stack: Fix building from source, add Apple Silicon support

### LINKED ISSUE #94796: Cannot install haskell "stack" HEAD macOS Monterey 12.2
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/45a4cabea80e957343c51a40a4ddd156
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install stack from HEAD to get support for M1 chip

### What happened (include all command output)?

Warning: Treating stack as a formula. For the cask, use homebrew/cask/stack
==> Cloning https://github.com/commercialhaskell/stack.git
Updating /Users/tom/Library/Caches/Homebrew/haskell-stack--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at aac15d03 Add FreeBSD aarch64 support
==> cabal v2-update
==> cabal v2-install --jobs=8 --max-backjumps=100000 --install-method=copy --ins
Last 15 lines from /Users/tom/Library/Logs/Homebrew/haskell-stack/02.cabal:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text v0’
      Expected type: HashMap Text v0
        Actual type: Object
    • In the first argument of ‘HashMap.keys’, namely ‘obj’
      In the first argument of ‘Set.fromList’, namely
        ‘(HashMap.keys obj)’
      In the first argument of ‘Set.difference’, namely
        ‘(Set.fromList (HashMap.keys obj))’
    |
124 |                              (Set.fromList (HashMap.keys obj))
    |                                                          ^^^
cabal: Failed to build pantry-0.5.3 (which is required by stack-2.7.4). See
the build log above for details.

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

### What did you expect to happen?

Install stack successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`$ brew install stack --HEAD`
```

### PR DESCRIPTION
**Pull request by simnalamburt**
1.  Fixed building from source.

    Due to recent update of aeson-2.0.0.0, stack can no longer be built with cabal-install. So I patched stack to freeze cabal dependencies using stackage 17.15 LTS.

2.  Add Apple Silicon support.

    HEAD version of stack has already been patched to support Apple Silicon. However, the next release containing that patch hasn't release yet. So I manually patched stack v2.7.3 to support Apple Silicon.

3.  Add llvm@12 as a dependency only on ARM

    All ghc versions before 9.2.1 requires LLVM Code Generator as a backend on ARM.

Fixes https://github.com/Homebrew/homebrew-core/issues/94796

###### References:
- https://github.com/commercialhaskell/stack/pull/5562
- https://github.com/commercialhaskell/stack/pull/5677

###### Checklists:
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] `brew install --build-from-source --formula ./haskell-stack.rb`
- [x] `brew test ./haskell-stack.rb`
- [x] `brew audit --strict haskell-stack`
- [x] `brew install --build-from-source --HEAD --formula ./haskell-stack.rb`

### CODE REVIEW

File: Formula/haskell-stack.rb [hunk 1]
```diff
@@ -19,14 +42,34 @@ class HaskellStack < Formula
...
+
+    # Due to aeson-2.0.0.0 update, stack can no longer be built with cabal.
+    # Dependencies freezing is required to build stack with cabal.
+    #
+    # Reference: https://github.com/commercialhaskell/stack/pull/5677
+    patch do
+      url "https://github.com/commercialhaskell/stack/commit/b2a2e56c.patch?full_index=1"
+      sha256 "43c59b4af52e372cf4af14514f1c89b62bc450171eed344aeed46e2d9d9c0d96"
+    end
+  end
```
Comment (carlocab) [inline Formula/haskell-stack.rb:56]: Let's leave `head` alone -- it's not tested, and the PR could be merged at any time.

File: Formula/haskell-stack.rb [hunk 2]
```diff
@@ -1,10 +1,33 @@
...
+    #   release yet. So I manually patched stack v2.7.3 to support Apple
+    #   Silicon.
+    #
+    # Reference:
+    #   https://github.com/commercialhaskell/stack/pull/5562
+    #   https://github.com/commercialhaskell/stack/pull/5677
+    patch do
+      url "https://github.com/commercialhaskell/stack/compare/7927a3ae..32b80476.patch?full_index=1"
+      sha256 "8e87e3f3409cf1427b46124586536c91f94dde4c27d2708764604c24c4ea98d7"
+    end
```
Comment (carlocab) [inline Formula/haskell-stack.rb:29]: This seems like a pretty big patch to apply unconditionally. Can we use a smaller patch? We should also use the commits from the relevant pull requests instead of doing `compare/<hash>..<hash>`.

Comment (simnalamburt) [reply Formula/haskell-stack.rb:29]: That patch does only two thing.

1. First commit: Let “cabal build” get the exactly same result with “stack build”
2. Second commit: Add M1 support by adding only a single line `Platform AArch64               Cabal.OSX     -> return "macosx-aarch64"`

This is the minimalist patch that I could made. I’ll accept feedback if there is another way to do better or smaller.

File: Formula/haskell-stack.rb (hunk 1 above)
Comment (carlocab) [reply Formula/haskell-stack.rb:56]: Sorry, by "not tested" I mean "not tested in CI", so what is and isn't the official build tool of stack isn't relevant.

That said, we've been building stack with cabal for about 7 years now, and there are about 30,000 downloads of `haskell-stack` a year, so even "way less tested" in your terms is "pretty damn thoroughly tested".

Comment (carlocab) [reply Formula/haskell-stack.rb:56]: To put my point another way: if we really must patch `head` to get a working build, then instead let's just remove it. We don't carry around patched for head builds.

Comment (simnalamburt) [reply Formula/haskell-stack.rb:56]: Fair point. I’ll revert the head block.

File: Formula/haskell-stack.rb (hunk 2 above)
Comment (simnalamburt) [reply Formula/haskell-stack.rb:30]: I tried to make a smaller patch in [this way](https://github.com/simnalamburt/stack/compare/v2.7.3..no-aeson-2), but I found that another dependency has broken their API as well.

```
src/Stack/Setup.hs:847:24: error:
    • Couldn't match expected type ‘SimpleRepo’ with actual type ‘Repo’
    • In the first argument of ‘withRepo’, namely ‘repo’
      In the expression: withRepo repo
      In a stmt of a 'do' block:
        withRepo repo
          $ do mcwd <- traverse parseAbsDir =<< view workingDirL
               let cwd = fromMaybe (error "Invalid working directory") mcwd
               threads <- view $ configL . to configJobs
               let hadrianArgs = fmap T.unpack ...
                   hadrianScripts
                     | osIsWindows = hadrianScriptsWindows
                     | otherwise = hadrianScriptsPosix
               ....
    |
847 |        Pantry.withRepo repo $ do
    |                        ^^^^
```

**Comment by xtendo-org** [comment]
@carlocab I'd really, really appreciate if you could merge this PR.

At this point, `brew install haskell-stack` on Apple Silicon machines is just ... broken. `brew install` seemingly does "something", but afterwards, the GHC tool chain doesn't work, leaving users puzzled. In fact, for users of M1`*` machines, at this point, there is no hassle-free way to use the Haskell Stack at all.

Well, as the PR author mentioned, there is `brew install simnalamburt/x/haskell-stack`, but this is obviously not what we want to recommend to all newcomers, and users will probably try `brew install haskell-stack` anyway, so leaving it broken will simply confuse and deter them. I think this is bad for both for brew and Haskell.

Stack provides their own installation method (distribution of binary executables) but they haven't released the version 2.7.4 that supports the Apple Silicon arch. Users will have to wait indefinitely. Besides, regardless of Stack's own release policy, `brew install` should work, right?

As you pointed out, the patch size (in terms of bytes) is pretty big, but what it does is actually small and simple: Freeze the versions of dependency packages in the build process. Hopefully Stack will solve the "dependency version problem when building with cabal" issue, at which point we can probably ditch this patch. Furthermore, since this is in the `patch do ~ end` form, we should be able to remove it easily in the future.

I think this serves as a really nice stopgap for Apple Silicon users right now. Please merge this. I beg you.

**Comment by SMillerDev** [comment]
> Besides, regardless of Stack's own release policy, brew install should work, right?

Generally brew just ships what upstream ships and almost everywhere in our documentation we tell people not to patch things in brew (but to fix it upstream). If upstream doesn't feel comfortable releasing this patch yet I'm not sure if we should.

File: Formula/haskell-stack.rb (hunk 2 above)
Comment (carlocab) [reply Formula/haskell-stack.rb:30]: Ok, that's fine, but we should still do this:

> We should also use the commits from the relevant pull requests instead of doing `compare/<hash>..<hash>`.

Comment (simnalamburt) [reply Formula/haskell-stack.rb:30]: Thanks @carlocab! But.. actually I couldn't understand what you meant by "use the commits from the relevant pull requests instead of doing compare/<hash>..<hash>.". Is there any special Homebrew DSL for that? (Sorry this is my first time submitting patch to the Homebrew)

Comment (simnalamburt) [reply Formula/haskell-stack.rb:30]: Oh did you mean that there is a way to apply multiple patches at once?

Comment (SMillerDev) [reply Formula/haskell-stack.rb:30]: You can have multiple patch blocks. But you should have the URL of a single commit per block, not the `aaa...bbb` style url.

Comment (simnalamburt) [reply Formula/haskell-stack.rb]: Thanks for the help! I've updated the PR :) 🎉

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by simnalamburt** [comment]
@carlocab Since I wrote this PR, I’m willing to help you if this PR caused any issue with bottling haskell-stack or others.

**Comment by carlocab** [comment]
`haskell-stack` bottled fine. The messages you're seeing are for (recursive) dependents. At least one of them looks to have been broken by `aeson`.

**Comment by simnalamburt** [comment]
I just checked https://github.com/Homebrew/homebrew-core/commit/87ec35b5876e17d5ec5c55cf70d4b8542b49f217. Thanks!

Can you rebuild the “arm64_big_sur” image too? The existing arm64_big_sur binary does not work properly without this PR. It will enable other haskell-stack dependents’ arm64_big_sur builds too!

**Comment by carlocab** [comment]
Can you explain the problem with the `arm64_big_sur` bottle, and give a minimal reproduction? We haven't had any issues using the existing `haskell-stack` build to build other formulae on Big Sur (and there have been a few of those recently).

**Comment by simnalamburt** [comment]
WIth existing binary:

```bash
brew install haskell-stack
cd any-stack-project # navigate into any stack project
stack setup
```

Will fail with `I don't know how to install GHC for (OSX,AArch64), please install manually.`.

This issue was fixed by https://github.com/commercialhaskell/stack/pull/5562. This is the reason why I patched haskell-stack with https://github.com/Homebrew/homebrew-core/commit/e3910edd5aae91962d04ea6a23b95c78030c15e6#diff-7262ae90068953c6fc17eb4ec7deac3a69c7edf2ed4e32edc4ce2e4dc00d73dfR22-R31.

**Comment by simnalamburt** [comment]
Actually this is what @xtendo-org meant by "`brew install` seemingly does "something", but afterwards, the GHC tool chain doesn't work, leaving users puzzled.". On ARM Big Sur, `brew install haskell-stack` does install you some binaries but all stack commands like `stack setup`, `stack ghci`, `stack build`, etc won't work.

**Comment by carlocab** [comment]
We should've bumped the `revision`, then. Feel free to open a new PR that does so.
