### PR TITLE
bitcoin: use release tarball

### LINKED ISSUE #21774: SHA256 mismatch in bitcoin
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) <del>and included the output link?<del> <ins>No logs.</ins>
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

***

Tried on multiple Homebrew installations across multiple Macs on multiple network connections.

```
$ brew config
HOMEBREW_VERSION: 1.4.0-27-g67c4402
ORIGIN: https://github.com/Homebrew/brew
HEAD: 67c4402634e24400accdb59fa81cde9020dd0386
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 841256fddd1f137bc43769ac0506165d1f2fd8dd
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BINTRAY_USER: alyssais
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_DEVELOPER: 1
HOMEBREW_VERBOSE: 1
HOMEBREW_VISUAL: kak
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/qyliss/.rubies/ruby-2.4.2/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.1.0.0.1.1508540944
X11: N/A
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```

```
$ brew install -vs bitcoin
/usr/bin/sandbox-exec -f /tmp/homebrew20171215-766-94yau6.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bitcoin.rb --verbose
==> Downloading https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz
==> Downloading from https://codeload.github.com/bitcoin/bitcoin/tar.gz/v0.15.1
/usr/bin/curl --show-error --user-agent Homebrew/1.4.0-27-g67c4402 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/qyliss/Library/Caches/Homebrew/bitcoin-0.15.1.tar.gz.incomplete https://codeload.github.com/bitcoin/bitcoin/tar.gz/v0.15.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7370k  100 7370k    0     0  1137k      0  0:00:06  0:00:06 --:--:-- 1381k
==> Verifying bitcoin-0.15.1.tar.gz checksum
Error: SHA256 mismatch
Expected: e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79
Actual: 98b3a98a67054123bef6714e4035e18f9250a1b6d63829258ad057906e75d8b1
Archive: /Users/qyliss/Library/Caches/Homebrew/bitcoin-0.15.1.tar.gz
To retry an incomplete download, remove the file above.
```

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #21774.

### CODE REVIEW

File: Formula/bitcoin.rb [hunk 1]
```diff
@@ -1,9 +1,9 @@
 class Bitcoin < Formula
   desc "Decentralized, peer to peer payment network"
   homepage "https://bitcoin.org/"
-  url "https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz"
-  sha256 "e429d4f257f2b5b6d0caaf36ed1a5f5203e5918c57837efac00b0c322a1fef79"
-  head "https://github.com/bitcoin/bitcoin.git"
+  url "https://bitcoin.org/bin/bitcoin-core-0.15.1/bitcoin-0.15.1.tar.gz"
+  sha256 "34de2dbe058c1f8b6464494468ebe2ff0422614203d292da1c6458d6f87342b4"
+  revision 1
```
Comment (alyssais) [inline Formula/bitcoin.rb]: Curious: what's the revision bump needed for?

Comment (ilovezfs) [reply Formula/bitcoin.rb]: We generally revision bump if the tarball changed as a matter of course.

**Review by JCount — APPROVED** [review]

**Review by alyssais — APPROVED** [review]

File: Formula/bitcoin.rb (hunk 1 above)
Comment (ilovezfs) [reply Formula/bitcoin.rb]: Given the change is useless I'll just merge without the revision bump.
