### PR TITLE
elasticsearch: fix custom config path

### LINKED ISSUE #20717: Custom config path for elasticsearch 6.0 not working
The command `ES_PATH_CONF=$PWD/elasticsearch_config elasticsearch` not working anymore.

My workaround for now is
```
ES_PATH_CONF=$PWD/elasticsearch_config /usr/local/Cellar/elasticsearch/6.0.0/libexec/bin/elasticsearch
```
But the path `/usr/local/Cellar/elasticsearch/6.0.0/` is very specific for my Mac OSX and eventually does not work on other systems.

I also copied `jvm.options` file to my config folder to fix java errors. This step was not necessary for ES 5.

related pull request https://github.com/elastic/elasticsearch/issues/21932

### PR DESCRIPTION
**Pull request by jasontedor**
This commit fixes an issue with setting a custom config path via ES_PATH_CONF.

Closes #20717

### CODE REVIEW

File: Formula/elasticsearch.rb [hunk 1]
```diff
@@ -123,5 +128,31 @@ def plist
...
+    server.close
+
+    (testpath/"config/elasticsearch.yml").write <<~EOS
+      path.data: #{testpath}/data
+      path.logs: #{testpath}/logs
+      node.name: test-es-path-conf
+      http.port: #{port}
+    EOS
+
+    cp (etc/"elasticsearch/jvm.options"), (testpath/"config")
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
    cp etc/"elasticsearch/jvm.options", "config"
```

File: Formula/elasticsearch.rb [hunk 2]
```diff
@@ -123,5 +128,31 @@ def plist
...
+    cp (etc/"elasticsearch/log4j2.properties"), (testpath/"config")
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
    cp etc/"elasticsearch/log4j2.properties", "config"
```

File: Formula/elasticsearch.rb [hunk 3]
```diff
@@ -123,5 +128,31 @@ def plist
...
+
+    ENV["ES_PATH_CONF"] = (testpath/"config")
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
    ENV["ES_PATH_CONF"] = testpath/"config"
```

File: Formula/elasticsearch.rb [hunk 4]
```diff
@@ -123,5 +128,31 @@ def plist
...
+    pid = "#{testpath}/pid"
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
    pid = testpath/"pid"
```

File: Formula/elasticsearch.rb [hunk 5]
```diff
@@ -123,5 +128,31 @@ def plist
...
+    begin
+      system "#{bin}/elasticsearch", "-d", "-p", pid
+      sleep 10
+      system "curl", "-XGET", "localhost:#{port}/"
+    ensure
+      Process.kill(9, File.read(pid).to_i)
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
      Process.kill(9, pid.read.to_i)
```

File: Formula/elasticsearch.rb [hunk 6]
```diff
@@ -34,6 +35,10 @@ def install
     # Install everything else into package directory
     libexec.install "bin", "config", "lib", "modules"
 
+    inreplace "#{libexec}/bin/elasticsearch-env",
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
    inreplace libexec/"bin/elasticsearch-env",
```

File: Formula/elasticsearch.rb [hunk 7]
```diff
@@ -34,6 +35,10 @@ def install
...
+              "if [ -z \"$ES_PATH_CONF\" ]; then ES_PATH_CONF=\"$ES_HOME\"/config; fi",
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]: Just the `then ES_PATH_CONF=\"$ES_HOME\"/config; fi",` should be enough

**Review by ilovezfs — DISMISSED** [review]
some little comments but :+1:

File: Formula/elasticsearch.rb (hunk 7 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: I prefer it this way, it's clearer to think about to simply replace the whole line.

Comment (ilovezfs) [reply Formula/elasticsearch.rb]: It goes passed the eightieth column, which is :-1:

**Comment by jasontedor** [comment]
@ilovezfs I pushed.

File: Formula/elasticsearch.rb [hunk 8]
```diff
@@ -115,13 +120,40 @@ def plist
...
+    cp etc/"elasticsearch/jvm.options", "config"
+    cp etc/"elasticsearch/log4j2.properties", "config"
+
+    ENV["ES_PATH_CONF"] = testpath/"config"
+    pid = testpath/"pid"
+    begin
+      system "#{bin}/elasticsearch", "-d", "-p", pid
+      sleep 10
+      system "curl", "-XGET", "localhost:#{port}/"
+      assert_match /test-es-path-conf/, shell_output("curl -s -XGET localhost:#{port}/_cat/nodes")
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]:
```
      output = shell_output("curl -s -XGET localhost:#{port}/_cat/nodes")
      assert_match "test-es-path-conf", output
```

File: Formula/elasticsearch.rb (hunk 7 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: That's not what the audit rule enforces. I don't think different rules should be enforced in PR reviews than are enforced by audit. I don't think less clear code should be written to fit in 80 columns if that's not what is enforced in audit.

Comment (ilovezfs) [reply Formula/elasticsearch.rb]: It's not enforced in audit because sometimes it is unavoidable, and I don't want to deal with red CI due to things we cannot avoid. This one is avoidable.

File: Formula/elasticsearch.rb [hunk 9]
```diff
@@ -115,13 +120,41 @@ def plist
...
     begin
       system "#{bin}/elasticsearch", "-d", "-p", pid, "-Epath.data=#{testpath}/data", "-Ehttp.port=#{port}"
       sleep 10
       system "curl", "-XGET", "localhost:#{port}/"
     ensure
-      Process.kill(9, File.read(pid).to_i)
+      Process.kill(9, pid.read.to_i)
+    end
+
+    require "socket"
```
Comment (DomT4) [inline Formula/elasticsearch.rb]: You seem to have required `socket` twice?

File: Formula/elasticsearch.rb [hunk 10]
```diff
@@ -115,13 +120,41 @@ def plist
...
+    cp etc/"elasticsearch/log4j2.properties", "config"
+
+    ENV["ES_PATH_CONF"] = testpath/"config"
+    pid = testpath/"pid"
+    begin
+      system "#{bin}/elasticsearch", "-d", "-p", pid
+      sleep 10
+      system "curl", "-XGET", "localhost:#{port}/"
+      output = shell_output("curl -s -XGET localhost:#{port}/_cat/nodes")
+      assert_match /test-es-path-conf/, output
```
Comment (DomT4) [inline Formula/elasticsearch.rb]: If we're not actually checking against a regex here just using `""` instead of `//` would be nice. ILZ can overrule as desired 🙈.

Comment (ilovezfs) [reply Formula/elasticsearch.rb]: yes I already said that here https://github.com/Homebrew/homebrew-core/pull/20735#discussion_r151705124 but perhaps that here but I think @jasontedor missed that part

Comment (DomT4) [reply Formula/elasticsearch.rb]: Ah, apologies. I clicked through a few of the review bubbles but not all of them, evidently 😅.

File: Formula/elasticsearch.rb [hunk 11]
```diff
@@ -34,6 +35,10 @@ def install
     # Install everything else into package directory
     libexec.install "bin", "config", "lib", "modules"
 
+    inreplace libexec/"bin/elasticsearch-env",
+              "if [ -z \"$ES_PATH_CONF\" ]; then ES_PATH_CONF=\"$ES_HOME\"/config; fi",
```
Comment (ilovezfs) [inline Formula/elasticsearch.rb]: needs to say <= 80 character

**Review by ilovezfs — CHANGES_REQUESTED** [review]

File: Formula/elasticsearch.rb (hunk 9 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: I pushed.

File: Formula/elasticsearch.rb (hunk 10 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: I pushed.

File: Formula/elasticsearch.rb (hunk 11 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: I don't understand this and I actually find it quite frustrating. Either the rule is 80 characters or it's what is enforced by audit. Please, enforcing on contributors in PR reviews rules different than what audit enforces makes maintaining these formula more onerous than necessary. I'm with you: you're a maintainer, you have every right to request changes to the formula to have consistency across formula (e.g., what methods are used, etc.) yet if you have a tool that enforces a certain code style than that should be sufficient for PR reviews and contributors should not have to deal with formatting differently than what is necessary to get audit to pass.

Comment (ilovezfs) [reply Formula/elasticsearch.rb]: @jasontedor as I said above, there are rules that we apply to the maximum extent possible that cannot be enforced programmatically without causing CI havoc. Currently the actually enforced maximum is 190 but we will stay <= 80 where possible.

File: Formula/elasticsearch.rb (hunk 10 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: Yes, I missed it on the first round, I'm sorry for missing it. I appreciate the second ping. 😇

File: Formula/elasticsearch.rb (hunk 11 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: I think this is a mistaken approach, it's frustrating to deal with as a contributor.

Comment (ilovezfs) [reply Formula/elasticsearch.rb]: @jasontedor OK. We will endure the _heinous_ line length if it makes you :smile_cat:

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @jasontedor!

File: Formula/elasticsearch.rb (hunk 11 above)
Comment (jasontedor) [reply Formula/elasticsearch.rb]: @ilovezfs ❤️

Comment (jasontedor) [reply Formula/elasticsearch.rb]: My recommendation would be this:
 - if 80 characters is what you want to enforce, reduce the limit in audit to 80 characters
 - whitelist all formula that currently have a line exceeding the 80 character limit; this keeps new formula and existing formula that do not have lines exceeding the limit from breaching the limit
 - warn but do not error on formula that are whitelisted and have lines that exceed the 80 character limit so that maintainers are encouraged to bring them under the limit
 - prune formula from the whitelist that are corrected to have all lines under the 80 character limit (e.g., a CI job that checks the whitelisted formula on a periodic basis)
 - add the ability to annotate a line as passing the audit check even if it exceeds 80 characters if  not exceeding 80 characters really is unavoidable for a given line
