### PR TITLE
nx: revert to 21.4.1

### LINKED ISSUE #235203: nx formula points to yanked, malicious package version
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.6.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 02947ea4edbdef5fcce9ee57fa289547f4d096c9
Last commit: 3 days ago
Branch: stable
Core tap JSON: 27 Aug 17:52 UTC
Core cask tap JSON: 27 Aug 17:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.4.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 17.0.0 build 1700
Git: 2.51.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.6.1-arm64
CLT: 16.4.0.0.1.1747106510
Xcode: N/A
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

Install `nx` successfully

### What happened (include all command output)?

Yesterday a malicious version of `nx` was released to NPM, tracked by GitHub Security Advisory [`GHSA-cxm3-wv7p-598c`](https://github.com/nrwl/nx/security/advisories/GHSA-cxm3-wv7p-598c)

In PR #235085, the version of `nx` installed by Homebrew was updated to this malicious version. As a result, on install, one of the following will happen:

- A malicious version will be installed, which includes a credential stealer which will be triggered on install
- A 404 will be received from NPM, since the version was yanked, causing the install to fail

Since the relevant payload is a credential stealer that runs on install, and I do not have a spare machine to test this on, I do not wish to risk the credentials on this machine to confirm that it is indeed the 404 that occurs.

### What did you expect to happen?

`nx` to be installed successfully, free of malware

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install nx
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixes #235203.

- https://github.com/nrwl/nx/issues/32522

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Review by iMichka — APPROVED** [review]

File: Formula/n/nx.rb [hunk 1]
```diff
@@ -1,9 +1,10 @@
 class Nx < Formula
   desc "Smart, Fast and Extensible Build System"
   homepage "https://nx.dev"
-  url "https://registry.npmjs.org/nx/-/nx-21.5.0.tgz"
-  sha256 "69d9d32937ab4f87f001ca7e39e8c544b76c409c36be7fbcc40cb228cc1ee334"
+  url "https://registry.npmjs.org/nx/-/nx-21.4.1.tgz"
+  sha256 "c06b9cc57533a08fcd42b83230a5adc1245479827dbe0af3666e9f709ae7a92e"
   license "MIT"
+  version_scheme 1
```
Comment (chenrui333) [inline Formula/n/nx.rb:7]: should be just downgrade?

Comment (chenrui333) [reply Formula/n/nx.rb:7]: we can just merge as downgrade and it would avoid version_scheme

Comment (iMichka) [reply Formula/n/nx.rb:7]: We decided to bump the version scheme. We did the same for xz last time https://github.com/Homebrew/homebrew-core/pull/167512/files

Comment (chenrui333) [reply Formula/n/nx.rb:7]: I see, make sense then 👍

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Review by cho-m — APPROVED** [review]
