### PR TITLE
molten-vk: install ICD to non-overridable path

### LINKED ISSUE #203233: `molten-vk` package should install ICD json file to `etc` instead of `share`
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config ; brew doctor
HOMEBREW_VERSION: 4.4.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: f84082963da8af8c9ccd6dffbe932eba457e2b78
Last commit: 5 days ago
Branch: stable
Core tap JSON: 04 Jan 23:30 UTC
Core cask tap JSON: 04 Jan 23:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.P5q6SbcVsl/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: 16.1
Rosetta 2: false
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to use `mpv` with `--vo=gpu-next` under the new Ghostty terminal to play a video, but the video failed to display.  I reported this to `mpv` and the maintainers indicated the issue is the directory where the `molten-vk` Homebrew package is configured to install the ICD json file; see https://github.com/mpv-player/mpv/issues/15642#issuecomment-2571432029.   

### What happened (include all command output)?

I'm on an M1 Pro 2021 MB Pro, and I've installed mpv 0.39.0_1 from Homebrew.  When I try to play any video with mpv using the `--vo=gpu-next` option from ghostty, I don't see any video.  E.g., if I download [this file](https://download.samplelib.com/mp4/sample-5s.mp4) and try to play it here's what I see at the console:

```
$ mpv --vo=gpu-next sample-5s.mp4
● Video  --vid=1               (h264 1920x1080 30 fps) [default]
● Audio  --aid=1  --alang=eng  (aac 2ch 44100 Hz 128 kbps) [default]
[vo/gpu-next] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
Video: no video
AO: [coreaudio] 44100Hz stereo 2ch floatp
```
I hear audio, but see no video.  If I don't pass the `--vo=gpu-next` option and just run `mpv sample-5s.mp4`, the video plays fine from ghostty.  And, from iTerm2 and Terminal, `mpv --vo=gpu-next sample-5s.mp4` succeeds in playing the video.

### What did you expect to happen?

I expected the video to be visible in all cases.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I believe just `brew install mpv` followed by the steps outlined above under "What happened."
```

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #203233.

May as well use non-overridable path to reduce chances of user configuration impacting functionality.

Prior bottle,
```console
❯ XDG_DATA_DIRS=/tmp vulkaninfo --summary
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /tmp/vulkan-tools-20241221-15121-nec5zd/Vulkan-Tools-1.4.304/vulkaninfo/./vulkaninfo.h:456:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER

❯ vulkaninfo --summary | rg driver
VK_LUNARG_direct_driver_loading        : extension revision 1
	driverVersion      = 0.2.2019
	driverID           = DRIVER_ID_MOLTENVK
	driverName         = MoltenVK
	driverInfo         = 1.2.11
	driverUUID         = 4d564b00-0000-27e3-0f02-020700000000
```

New build:
```console
❯ XDG_DATA_DIRS=/tmp vulkaninfo --summary | rg driver
VK_LUNARG_direct_driver_loading        : extension revision 1
	driverVersion      = 0.2.2019
	driverID           = DRIVER_ID_MOLTENVK
	driverName         = MoltenVK
	driverInfo         = 1.2.11
	driverUUID         = 4d564b00-0000-27e3-0f02-020700000000
```

### CODE REVIEW

File: Formula/m/molten-vk.rb [hunk 1]
```diff
@@ -179,9 +179,9 @@ def install
                         "MoltenVKShaderConverter"]
 
     inreplace "MoltenVK/icd/MoltenVK_icd.json",
-              "./libMoltenVK.dylib",
-              (lib/"libMoltenVK.dylib").relative_path_from(share/"vulkan/icd.d")
-    (share/"vulkan").install "MoltenVK/icd" => "icd.d"
+              "\"./libMoltenVK.dylib\"",
+              "\"#{lib}/libMoltenVK.dylib\""
```
Comment (cho-m) [inline Formula/m/molten-vk.rb:183]: We could keep a relative path if preferred. Absolute path is simpler for inreplace. Relative path does avoid relocation in JSON file but wouldn't expect much impact unlike relocation in binary file.
```suggestion
              "./libMoltenVK.dylib",
              (lib/"libMoltenVK.dylib").relative_path_from(prefix/"etc/vulkan/icd.d")
```

**Comment by cho-m** [comment]
Would be nicer to test within `molten-vk` but dependency tree makes this complicated.

`vulkan-tools` is the easiest way to check Vulkan devices but it has a dependency on `molten-vk`.

**Review by p-linnane — APPROVED** [review]
