### PR TITLE
odin: added odin libraries for linux

### LINKED ISSUE #182068: odin: vendor libraries are not available on Linux
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config && brew doctor
HOMEBREW_VERSION: 4.3.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3426911432b93dc46d20d910c2f4fd33cdac62a2
Last commit: 4 days ago
Core tap JSON: 22 Aug 19:53 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
SUDO_ASKPASS: /usr/libexec/openssh/gnome-ssh-askpass
Homebrew Ruby: 3.3.4 => /var/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 18.1.8
Git: 2.46.0 => /bin/git
Curl: 8.6.0 => /bin/curl
Kernel: Linux 6.10.4-201.fsync.fc40.x86_64 x86_64 GNU/Linux
OS: Fedora Linux 40.20240627.0 (Silverblue)
Host glibc: 2.39
/usr/bin/gcc: 14.2.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Compile a simple odin project with raylib

### What happened (include all command output)?

```
$ odin run .
/usr/bin/ld: cannot find -l:/var/home/linuxbrew/.linuxbrew/Cellar/odin/2024-08/libexec/vendor/raylib//linux/libraylib.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In #164071, the prebuilt vendored libraries were removed on all platforms, but they are linked back only on macos.

### PR DESCRIPTION
**Pull request by xakep8**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #182068 

I've added the vendor libraries for linux and built them and also changed the test to verify it on linux.

### CODE REVIEW

**Comment by SMillerDev** [comment]
The solution is not to duplicate the block, but to figure out which parts should only be on macOS and make the rest unconditional. It also needs test adjustments so we know it works.

**Comment by xakep8** [comment]
@SMillerDev Do I need to update the test?

**Comment by SMillerDev** [comment]
Yes, because without it there is no way to know if this works

File: Formula/o/odin.rb [hunk 1]
```diff
@@ -128,36 +156,34 @@ def install
...
+        assert(!rl.GuiIsLocked())
+
+        // raylib.
+        num := rl.GetRandomValue(42, 1337)
+        assert(42 <= num && num <= 1337)
+      }
+    EOS
+    system bin/"odin", "run", "raylib.odin", "-file"
+    # system bin/"odin", "run", "raylib.odin", "-file",
+    #   "-define:RAYLIB_SHARED=true", "-define:RAYGUI_SHARED=true"
```
Comment (gromgit) [inline Formula/o/odin.rb:175]: Why is this commented out?

Comment (xakep8) [reply Formula/o/odin.rb:175]: that is the code for dynamic linking for the raylib and raygui but since the path to vender libraries is not specified in env it is unable to link it

File: Formula/o/odin.rb [hunk 2]
```diff
@@ -83,6 +83,34 @@ def install
       end
     end
 
+    if OS.linux?
```
Comment (SMillerDev) [inline Formula/o/odin.rb:86]: Nothing in this block seems specific to Linux, except the naming of the shared library file (.so). Why not make only that an `if OS.mac? ... else ...` block?

File: Formula/o/odin.rb (hunk 1 above)
Comment (gromgit) [reply Formula/o/odin.rb:175]: If `odin` can handle shared libraries on macOS (as the original test clearly showed) but not Linux, this should be highlighted upstream. I suspect it's more a matter of getting the Linux build config right though.

Comment (xakep8) [reply Formula/o/odin.rb:175]: The problem is with installing raylib as a shared library on linux as when the shared library flag is used `odin` looking for the `.so` files in the current `directory/linux` instead of looking in the place where they exist as the linking is not done correctly

Comment (gromgit) [reply Formula/o/odin.rb:175]: If shared library linking from Odin's vendor directories isn't working on Linux, you should ask upstream what's going on, because it works for macOS (otherwise the flags you commented out wouldn't have been written into the test in the first place).

Comment (laytan) [reply Formula/o/odin.rb:175]: I will have a look at this PR soon!

Comment (laytan) [reply Formula/o/odin.rb]: Looks like you figured it out but just have some code style issues blocking the PR?

Comment (xakep8) [reply Formula/o/odin.rb]: no actually it is still failing while detecting the shared library on linux

Comment (xakep8) [reply Formula/o/odin.rb]: the issue is that the linker is looking the `.so` files in `current directory/linux/` but it has to look at a different location. I am unable to understand why that is happening I thought it worked but the only solution that I tried was to copy the files to the directory where it is currently looking in and that way it works

Comment (xakep8) [reply Formula/o/odin.rb]: @laytan could you please take a look why the linker is looking in the wrong directory because I have tired setting the LD_LIBRARY_SHARED path to point to the corrent location yet it is failing.

Comment (laytan) [reply Formula/o/odin.rb]: Yeah so shared libraries are indeed kind of broken.

The reason it does work for macos is because brew rewrites `@rpath` to the absolute path of the library.

Currently, Odin wants you to copy the shared library into the `$(pwd)/linux/libraylib.so.500` but that is not a good thing and I will be bringing this up internally and seeing if we can unify this with all the other platforms and provide better errors.

We do want to have the user (or maybe Odin could do that automatically) copy over shared libraries into a known path though, if you think about shipping software, you can't rely on linking to a shared library that is at `/foo/whatever.so`, when you ship you want that to be relative to your executable so you can bundle up a release and have the shared libraries load on any system.

I think in the near future it makes sense to make changes so it works consistently the same everywhere, where the same is: expect the user to copy the shared libraries next to the executable. So `$executable/libraylib.so.500` and not `$(pwd)/linux/libraylib.so.500`. But we still need to work this all out and talk it over.

---

Because this is an upstream issue that also happens on our own releases, I think this should not be blocking this PR. Maybe skipping the test with a comment is the best to get this through.

File: Formula/o/odin.rb [hunk 3]
```diff
@@ -81,6 +81,32 @@ def install
           "-I#{Formula["raylib"].include}", "-L#{Formula["raylib"].lib}", "-lraylib"
         cp "libraygui.dylib", buildpath/raylib_installpath
       end
+    else
+      raylib_installpath = "vendor/raylib/linux"
+
+      # Create symbolic links for GLFW and Raylib libraries
+      ln_s Formula["glfw"].lib/"libglfw3.a", buildpath/"vendor/glfw/lib/darwin/libglfw3.a"
+      ln_s Formula["raylib"].lib/"libraylib.a", buildpath/raylib_installpath/"libraylib.a"
```
Comment (carlocab) [inline Formula/o/odin.rb:89]: These are very similar across Linux and macOS so should be moved out of this `if`-`else` block and made unconditional. (You can define `raylib_installpath` conditionally.)

File: Formula/o/odin.rb [hunk 4]
```diff
@@ -81,6 +81,32 @@ def install
...
+
+      # Adjust the name of the Raylib dynamic library for Linux
+      ln_s Formula["raylib"].lib/"libraylib.so.4.5.0", buildpath/raylib_installpath/"libraylib.so.500"
```
Comment (carlocab) [inline Formula/o/odin.rb:92]: You can also make this unconditional on the OS if you do:
```suggestion
      ln_s Formula["raylib"].lib/shared_library("libraylib", "4.5.0"), buildpath/raylib_installpath/shared_library("libraylib", "500")
```

File: Formula/o/odin.rb [hunk 5]
```diff
@@ -81,6 +81,32 @@ def install
...
+
+      resource("raygui").stage do
+        # Copy the raygui header and source files
+        cp "src/raygui.h", "src/raygui.c"
+
+        # Build the static library for raygui
+        system ENV.cc, "-c", "-o", "raygui.o", "src/raygui.c",
+               "-fpic", "-DRAYGUI_IMPLEMENTATION", "-I#{Formula["raylib"].include}"
+        system "ar", "-rcs", "libraygui.a", "raygui.o"
+        cp "libraygui.a", buildpath/raylib_installpath
```
Comment (carlocab) [inline Formula/o/odin.rb:102]: This is identical to the macOS codepath and should be moved outside of the `if`-`else` block.

File: Formula/o/odin.rb [hunk 6]
```diff
@@ -81,6 +81,32 @@ def install
...
+
+        # Build the shared library for raygui
+        system ENV.cc, "-o", "libraygui.so", "src/raygui.c",
+               "-shared", "-fpic", "-DRAYGUI_IMPLEMENTATION", "-lm", "-lpthread", "-ldl",
+               "-I#{Formula["raylib"].include}", "-L#{Formula["raylib"].lib}", "-lraylib"
+        cp "libraygui.so", buildpath/raylib_installpath
```
Comment (carlocab) [inline Formula/o/odin.rb:108]:
```suggestion
        system ENV.cc, "-o", shared_library("libraygui"), "src/raygui.c",
               "-shared", "-fpic", "-DRAYGUI_IMPLEMENTATION", "-lm", "-lpthread", "-ldl",
               "-I#{Formula["raylib"].include}", "-L#{Formula["raylib"].lib}", "-lraylib"
        cp shared_library("libraygui"), buildpath/raylib_installpath
```
And make this unconditional. You can make the exact flags conditional on OS.

File: Formula/o/odin.rb [hunk 7]
```diff
@@ -128,36 +154,34 @@ def install
...
+        assert(!rl.GuiIsLocked())
+
+        // raylib.
+        num := rl.GetRandomValue(42, 1337)
+        assert(42 <= num && num <= 1337)
+      }
+    EOS
+    system bin/"odin", "run", "raylib.odin", "-file"
+    # system bin/"odin", "run", "raylib.odin", "-file",
+    #   "-define:RAYLIB_SHARED=true", "-define:RAYGUI_SHARED=true"
```
Comment (carlocab) [inline Formula/o/odin.rb:173]: Either delete this or make it conditional on the OS.

**Review by carlocab — COMMENTED** [review]
Thanks for your work here; this is looking good. Let's just DRY it up.

File: Formula/o/odin.rb [hunk 8]
```diff
@@ -29,6 +29,14 @@ class Odin < Formula
...
   end
 
+  def shared_library(name)
+    return( OS.mac? ? "lib#{name}.dylib" : "lib#{name}.so")
+  end
+
+  def shared_library_versioned(name, version)
+    return( OS.mac? ? "lib#{name}.#{version}.dylib" : "lib#{name}.so.#{version}")
+  end
+
```
Comment (carlocab) [inline Formula/o/odin.rb:39]:
```suggestion
```
You don't need these. `brew` already defines the `shared_library` method.

File: Formula/o/odin.rb [hunk 9]
```diff
@@ -56,31 +64,32 @@ def install
...
-        cp "libraygui.a", buildpath/raylib_installpath
-
-        # build shared library
-        system ENV.cc, "-o", "libraygui.dylib", "src/raygui.c",
-          "-shared", "-fpic", "-DRAYGUI_IMPLEMENTATION", "-framework", "OpenGL",
-          "-lm", "-lpthread", "-ldl",
-          "-I#{Formula["raylib"].include}", "-L#{Formula["raylib"].lib}", "-lraylib"
-        cp "libraygui.dylib", buildpath/raylib_installpath
-      end
+    raylib_installpath = OS.mac? ? (Hardware::CPU.arm? ? "vendor/raylib/macos-arm64" : "vendor/raylib/macos") : "vendor/raylib/linux"
```
Comment (carlocab) [inline Formula/o/odin.rb:67]:
```suggestion
    raylib_installpath = if OS.linux?
      "vendor/raylib/linux"
    elsif Hardware::CPU.intel?
      "vendor/raylib/macos"
    else
      "vendor/raylib/macos-arm64"
    end
```

File: Formula/o/odin.rb [hunk 10]
```diff
@@ -56,31 +64,32 @@ def install
...
+
+    ln_s Formula["glfw"].lib/"libglfw3.a", buildpath/"vendor/glfw/lib/darwin/libglfw3.a"
+
+    ln_s Formula["raylib"].lib/"libraylib.a", buildpath/raylib_installpath/"libraylib.a"
+    # This is actually raylib 5.0, but upstream had not incremented this number yet when it released.
+    ln_s Formula["raylib"].lib/shared_library_versioned("libraylib", "4.5.0"), buildpath/raylib_installpath/shared_library_versioned("libraylib", "500")
```
Comment (carlocab) [inline Formula/o/odin.rb:73]:
```suggestion
    ln_s Formula["raylib"].lib/shared_library("libraylib", "4.5.0"),
         buildpath/raylib_installpath/shared_library("libraylib", "500")
```

**Review by carlocab — APPROVED** [review]
Thanks, looking good! A few minor tweaks.

After applying these, please run
```
brew style --fix odin
```
to fix any remaining `brew` linter issues.

File: Formula/o/odin.rb [hunk 11]
```diff
@@ -29,6 +29,24 @@ class Odin < Formula
...
+
+  def shared_library_versioned(name, version)
+    on_macos do
+      "lib#{name}.#{version}.dylib"
+    end
+    on_linux do
+      "lib#{name}.so.#{version}"
+    end
+  end
+
```
Comment (carlocab) [inline Formula/o/odin.rb]:
```suggestion
```
You don't need this.

File: Formula/o/odin.rb [hunk 12]
```diff
@@ -56,31 +56,38 @@ def install
...
+    else
+      "vendor/raylib/macos-arm64"
+    end
+
+    ln_s Formula["glfw"].lib/"libglfw3.a", buildpath/"vendor/glfw/lib/darwin/libglfw3.a"
+
+    ln_s Formula["raylib"].lib/"libraylib.a", buildpath/raylib_installpath/"libraylib.a"
+    # This is actually raylib 5.0, but upstream had not incremented this number yet when it released.
+    ln_s Formula["raylib"].lib/shared_library("libraylib", "4.5.0"),
+    buildpath/raylib_installpath/shared_library("libraylib", "500")
```
Comment (carlocab) [inline Formula/o/odin.rb:72]:
```suggestion
    ln_s Formula["raylib"].lib/shared_library("libraylib", "4.5.0"),
         buildpath/raylib_installpath/shared_library("libraylib", "500")
```

File: Formula/o/odin.rb [hunk 13]
```diff
@@ -56,31 +56,38 @@ def install
...
+      # build static library
+      system ENV.cc, "-c", "-o", "raygui.o", "src/raygui.c",
+        "-fpic", "-DRAYGUI_IMPLEMENTATION", "-I#{Formula["raylib"].include}"
+      system "ar", "-rcs", "libraygui.a", "raygui.o"
+      cp "libraygui.a", buildpath/raylib_installpath
+
+      # build shared library
+      args = ["-o", shared_library("libraygui"), "src/raygui.c", "-shared", "-fpic"]
+      args += ["-DRAYGUI_IMPLEMENTATION", "-lm", "-lpthread", "-ldl", "-I#{Formula["raylib"].include}"]
+      args += ["-L#{Formula["raylib"].lib}", "-lraylib"]
```
Comment (carlocab) [inline Formula/o/odin.rb:86]:
```suggestion
      args = [
        "-o", shared_library("libraygui"),
        "src/raygui.c",
        "-shared",
        "-fpic",
        "-DRAYGUI_IMPLEMENTATION",
        "-lm", "-lpthread", "-ldl",
        "-I#{Formula["raylib"].include}",
        "-L#{Formula["raylib"].lib}",
        "-lraylib"
      ]
```

**Comment by xakep8** [comment]
@carlocab I've made all the requested changes and I am pushing my new code in a bit kindly review that for any changes required.

**Review by carlocab — APPROVED** [review]
Thank you; very nice work!
