### PR TITLE
gobject-introspection: fix doctemplates error

### LINKED ISSUE #92992: Brew Installation Failing: ./giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
brew install gobject-introspection

Warning: Building gobject-introspection from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/myuser/homebrew/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/myuser/homebrew)
==> Downloading https://gitlab.gnome.org/tschoonj/gobject-introspection/-/commit
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/8b05b2a9de1da2191fe40b8fb80652d77efaa426382912d3d850e303bcf08d38--a7be304478b25271166cd92d110f251a8742d16b.diff
==> Downloading https://gitlab.gnome.org/rokm/gobject-introspection/-/commit/56d
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/cf90f085e421f2f49eef9de6383e9ad30c0cddae0e837f541a20d2c0b7b4404d--56df7b0f007fe260b2bd26ef9cc331ad73022700.diff
==> Cloning https://gist.github.com/7a0023656ccfe309337a.git
Updating /Users/myuser/Library/Caches/Homebrew/gobject-introspection--tutorial--git
==> Checking out revision 499ac89f8a9ad17d250e907f74912159ea216416
HEAD is now at 499ac89 
HEAD is now at 499ac89
==> Downloading https://download.gnome.org/sources/gobject-introspection/1.70/go
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/521d3ce8b76d8614697dc2dcf53d58c641569d12aed515db213ab68208976101--gobject-introspection-1.70.0.tar.xz
==> Patching
==> Applying a7be304478b25271166cd92d110f251a8742d16b.diff
patching file girepository/gitypelib.c
Hunk #1 succeeded at 2261 (offset 2 lines).
patching file meson.build
Hunk #1 succeeded at 122 (offset -2 lines).
patching file meson_options.txt
==> Applying 56df7b0f007fe260b2bd26ef9cc331ad73022700.diff
patching file girepository/gitypelib.c
Hunk #1 succeeded at 2278 with fuzz 2 (offset 16 lines).
==> meson --prefix=/Users/myuser/homebrew/Cellar/gobject-introspection/1.70.0_3 --libdir=/Users/myuser/homebrew/Cellar/gobject-introspection/1.70.0_3/lib --buildtype=release --wrap-mode=nofa
Last 15 lines from /Users/myuser/Library/Logs/Homebrew/gobject-introspection/01.meson:
Configuring message.py using configuration
Configuring msvccompiler.py using configuration
Configuring pkgconfig.py using configuration
Configuring shlibs.py using configuration
Configuring scannermain.py using configuration
Configuring sectionparser.py using configuration
Configuring sourcescanner.py using configuration
Configuring testcodegen.py using configuration
Configuring transformer.py using configuration
Configuring utils.py using configuration
Configuring xmlwriter.py using configuration

../giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.

A full log can be found at /private/tmp/gobject-introspection-20220112-23499-16tgkpd/gobject-introspection-1.70.0/build/meson-logs/meson-log.txt

Do not report this issue to Homebrew/brew or Homebrew/core!
```

macOS BigSur 11.5.2 (M1)

brew configured to custom folder.

brew doctor:

```
Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install graphwiz via brew install graphviz.

I found that issue related to dependency gobject-introspection

### What happened (include all command output)?

```
brew install gobject-introspection

Warning: Building gobject-introspection from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/myuser/homebrew/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/myuser/homebrew)
==> Downloading https://gitlab.gnome.org/tschoonj/gobject-introspection/-/commit
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/8b05b2a9de1da2191fe40b8fb80652d77efaa426382912d3d850e303bcf08d38--a7be304478b25271166cd92d110f251a8742d16b.diff
==> Downloading https://gitlab.gnome.org/rokm/gobject-introspection/-/commit/56d
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/cf90f085e421f2f49eef9de6383e9ad30c0cddae0e837f541a20d2c0b7b4404d--56df7b0f007fe260b2bd26ef9cc331ad73022700.diff
==> Cloning https://gist.github.com/7a0023656ccfe309337a.git
Updating /Users/myuser/Library/Caches/Homebrew/gobject-introspection--tutorial--git
==> Checking out revision 499ac89f8a9ad17d250e907f74912159ea216416
HEAD is now at 499ac89 
HEAD is now at 499ac89
==> Downloading https://download.gnome.org/sources/gobject-introspection/1.70/go
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/521d3ce8b76d8614697dc2dcf53d58c641569d12aed515db213ab68208976101--gobject-introspection-1.70.0.tar.xz
==> Patching
==> Applying a7be304478b25271166cd92d110f251a8742d16b.diff
patching file girepository/gitypelib.c
Hunk #1 succeeded at 2261 (offset 2 lines).
patching file meson.build
Hunk #1 succeeded at 122 (offset -2 lines).
patching file meson_options.txt
==> Applying 56df7b0f007fe260b2bd26ef9cc331ad73022700.diff
patching file girepository/gitypelib.c
Hunk #1 succeeded at 2278 with fuzz 2 (offset 16 lines).
==> meson --prefix=/Users/myuser/homebrew/Cellar/gobject-introspection/1.70.0_3 --libdir=/Users/myuser/homebrew/Cellar/gobject-introspection/1.70.0_3/lib --buildtype=release --wrap-mode=nofa
Last 15 lines from /Users/myuser/Library/Logs/Homebrew/gobject-introspection/01.meson:
Configuring message.py using configuration
Configuring msvccompiler.py using configuration
Configuring pkgconfig.py using configuration
Configuring shlibs.py using configuration
Configuring scannermain.py using configuration
Configuring sectionparser.py using configuration
Configuring sourcescanner.py using configuration
Configuring testcodegen.py using configuration
Configuring transformer.py using configuration
Configuring utils.py using configuration
Configuring xmlwriter.py using configuration

../giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.

A full log can be found at /private/tmp/gobject-introspection-20220112-23499-16tgkpd/gobject-introspection-1.70.0/build/meson-logs/meson-log.txt

Do not report this issue to Homebrew/brew or Homebrew/core!
```

macOS BigSur 11.5.2 (M1)

brew configured to custom folder.

### What did you expect to happen?

I expect normal installation 

Already reported to gobject-introspection devs, but redirected here via message: 

> The fix for #414 hasn't been backported to the 1.70 branch, so there's no point in trying that. You need to test the current main development branch, or ask the Homebrew maintainers to cherry pick the fix.

https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/415

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gobject-introspection
```

### PR DESCRIPTION
**Pull request by gromgit**
Fixes https://github.com/Homebrew/homebrew-core/issues/92992 and https://github.com/Homebrew/homebrew-core/issues/93211.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

File: Formula/gobject-introspection.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ class GobjectIntrospection < Formula
   url "https://download.gnome.org/sources/gobject-introspection/1.70/gobject-introspection-1.70.0.tar.xz"
   sha256 "902b4906e3102d17aa2fcb6dad1c19971c70f2a82a159ddc4a94df73a3cafc4a"
   license all_of: ["GPL-2.0-or-later", "LGPL-2.0-or-later", "MIT"]
-  revision 3
+  revision 4
```
Comment (carlocab) [inline Formula/gobject-introspection.rb:9]: This patch seems to be only needed at build-time. If so, perhaps we can omit the revision bump.

Comment (gromgit) [reply Formula/gobject-introspection.rb:9]: OK, let's try that...

**Review by carlocab — APPROVED** [review]
