### PR TITLE
claude-agent-acp: respect ripgrep

### LINKED ISSUE #367: Homebrew install: vendored ripgrep binary missing, Grep tool falls back to shell grep
## Description

When `claude-agent-acp` is installed via Homebrew, the vendored ripgrep binary is missing. The SDK expects it at:

```
<cellar>/node_modules/@anthropic-ai/claude-agent-sdk/vendor/ripgrep/arm64-darwin/rg
```

But the `vendor/` directory is empty. This causes the native Grep tool to fail with:

```
spawn /opt/homebrew/Cellar/claude-agent-acp/0.19.2/libexec/lib/node_modules/@zed-industries/claude-agent-acp/node_modules/@anthropic-ai/claude-agent-sdk/vendor/ripgrep/arm64-darwin/rg ENOENT
```

The agent then falls back to a plain shell `grep` command, which is significantly slower and less capable.

## Environment

- macOS (Apple Silicon / arm64)
- `claude-agent-acp` 0.19.2, installed via Homebrew
- System ripgrep 15.1.0 is available at `/opt/homebrew/bin/rg`
- The Homebrew formula declares `ripgrep` as a dependency, but the SDK doesn't use it

## Workaround

Symlink the system `rg` into the expected vendor path:

```bash
mkdir -p "/opt/homebrew/Cellar/claude-agent-acp/0.19.2/libexec/lib/node_modules/@zed-industries/claude-agent-acp/node_modules/@anthropic-ai/claude-agent-sdk/vendor/ripgrep/arm64-darwin"
ln -s /opt/homebrew/bin/rg "/opt/homebrew/Cellar/claude-agent-acp/0.19.2/libexec/lib/node_modules/@zed-industries/claude-agent-acp/node_modules/@anthropic-ai/claude-agent-sdk/vendor/ripgrep/arm64-darwin/rg"
```

## Expected behavior

Either:
1. The vendor directory should be populated with the ripgrep binary during the Homebrew install, or
2. The SDK should fall back to a system `rg` on `PATH` when the vendored binary is missing

### PR DESCRIPTION
**Pull request by timvisher-dd**
Built and tested locally on macOS 26.3.

- Keep the SDK vendor ripgrep path but point it to Homebrew's rg so the Grep tool no longer hits ENOENT on the missing vendored binary and falls back to slow shell grep (fixes https://github.com/zed-industries/claude-agent-acp/issues/367).
- Remove the `USE_BUILTIN_RIPGREP` wrapper so user settings can opt into system ripgrep when desired.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- [x] AI was used to generate or assist with generating this PR. *Please specify below how you used AI to help you, and what steps you have taken to manually verify the changes*.

AI assistance: Drafted the formula change and validation plan. Manually verified by running brew install --build-from-source (with HOMEBREW_NO_INSTALL_FROM_API=1), brew test, brew audit --strict, and an ACP ripgrep debug check.

-----

### CODE REVIEW

File: Formula/c/claude-agent-acp.rb [hunk 1]
```diff
@@ -20,11 +21,18 @@ class ClaudeAgentAcp < Formula
...
-    (bin/"claude-agent-acp").write_env_script libexec/"bin/claude-agent-acp",
-                                              USE_BUILTIN_RIPGREP: "1"
+    ripgrep_vendor_dir = libexec/"lib/node_modules/@zed-industries/claude-agent-acp" /
+                         "node_modules/@anthropic-ai/claude-agent-sdk/vendor/ripgrep"
+    rm_r ripgrep_vendor_dir
+    ripgrep_platform = if OS.mac?
+      Hardware::CPU.arm? ? "arm64-darwin" : "x64-darwin"
+    else
+      Hardware::CPU.arm? ? "arm64-linux" : "x64-linux"
+    end
```
Comment (carlocab) [inline Formula/c/claude-agent-acp.rb]:
```suggestion
    arch = Hardware::CPU.intel? ? "x64" : Hardware::CPU.arch.to_s
    ripgrep_platform = "#{arch}-#{OS.kernel_name.downcase}"
```
This should be simpler. Please test; I may be misremembering some of these methods.

**Review by carlocab — APPROVED** [review]
