### PR TITLE
netcdf: fix livecheck and resource URL

### LINKED ISSUE #95915: sha256sum mismatch when building netcdf from source
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

https://gist.github.com/ipatch/9740fefd0a4753e31df7bbd3bb2365d7

```shell
Error: SHA256 mismatch
Expected: 6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445
  Actual: fb49efac53117e7760662f9d6654d616a3a304a3bdcaf4d794dfd040ee6475b9
    File: /Users/capin/Library/Caches/Homebrew/downloads/60008bd4a4b82237539c0853d7d66598828980676475b9ae07459297ffd9d888--netcdf
To retry an incomplete download, remove the file above.
```

it wouldn't happen for most, as most would just install the bottle and not build a package from source but using the below command can reproduce the error

```
brew install netcdf -v -s
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to build/install netcdf from source

### What happened (include all command output)?

```
Error: SHA256 mismatch
Expected: 6a1189a181eed043b5859e15d5c080c30d0e107406fbb212c8fb9814e90f3445
  Actual: fb49efac53117e7760662f9d6654d616a3a304a3bdcaf4d794dfd040ee6475b9
    File: /Users/capin/Library/Caches/Homebrew/downloads/60008bd4a4b82237539c0853d7d66598828980676475b9ae07459297ffd9d888--netcdf
To retry an incomplete download, remove the file above.
```

### What did you expect to happen?

the correct sha256sums to match

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install netcdf -v -s
```

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
The old page failed to retrieve versions

### CODE REVIEW

File: Formula/netcdf.rb [hunk 1]
```diff
@@ -8,8 +8,7 @@ class Netcdf < Formula
   head "https://github.com/Unidata/netcdf-c.git", branch: "main"
 
   livecheck do
-    url "https://www.unidata.ucar.edu/downloads/netcdf/"
-    regex(/href=.*?netcdf-c[._-]v?(\d+(?:\.\d+)+)\.t/i)
+    regex(/^v?(\d+(?:\.\d+)+)$/i)
```
Comment (nandahkrishna) [inline Formula/netcdf.rb:11]:
```suggestion
    url "https://downloads.unidata.ucar.edu/netcdf-c/release_info.json"
    regex(/["']version["']:\s*["']v?(\d+(?:\.\d+)+)["']/i)
```

**Comment by cho-m** [comment]
Can we also fix resource `cxx` URL in #95915?

Specifically:
- Current https://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-cxx4-4.3.1.tar.gz redirects to webpage rather than tarball
- Webpage shows https://downloads.unidata.ucar.edu/netcdf-cxx/4.3.1/netcdf-cxx4-4.3.1.tar.gz as download link now.

**Review by Bo98 — APPROVED** [review]
