### PR TITLE
dbus: fix launchd item management

### LINKED ISSUE #4: Error when trying to start dbus service
when i run brew services start dbus i receive the following error:

Error: Formula 'dbus' has not implemented #plist, #service or installed a locatable service file.

How do i fix this and get the service running?

Screenshot 2023-04-02 at 8 37 22 PM

### PR DESCRIPTION
**Pull request by EricFromCanada**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Fixes for these issues with `dbus`:

- moves the supplied launchd plist into the formula prefix, where it needs to be for `brew services` to see it. (Only a half dozen formulae currently supply their own plists.) Fixes https://github.com/zbentley/dbus-osx-examples/issues/4.
- patches out deprecated plist keys. This patch was removed in its [last version bump](https://github.com/Homebrew/homebrew-core/pull/209163), but the [associated merge request](https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/179) hasn't been completed.
- since the provided plist is only for the session bus, this supplies an additional plist for the system bus and adjusts the instructions to show how to manually enable it, since `brew services` doesn't currently support managing multiple services from a single formula.

### CODE REVIEW

File: Formula/d/dbus.rb [hunk 1]
```diff
@@ -65,17 +76,18 @@ def post_install
...
+
+          brew services start dbus
+
+        To start the system bus now and on boot, install and activate the included daemon:
 
-          sudo cp #{lib}/Library/LaunchAgents/org.freedesktop.dbus-session.plist /Library/LaunchAgents
-          sudo chmod 644 /Library/LaunchAgents/org.freedesktop.dbus-session.plist
-          sudo launchctl load -w /Library/LaunchAgents/org.freedesktop.dbus-session.plist
+          sudo cp -f $(brew --prefix dbus)/org.freedesktop.dbus-system.plist /Library/LaunchDaemons
+          sudo launchctl bootstrap system /Library/LaunchDaemons/org.freedesktop.dbus-system.plist
```
Comment (carlocab) [inline Formula/d/dbus.rb:86]:
```suggestion
          sudo brew services start --file=#{opt_bin}/org.freedesktop.dbus-system.plist
```
Does this work?

File: Formula/d/dbus.rb [hunk 2]
```diff
@@ -47,14 +52,20 @@ def install
...
 
     # rpath is not set for meson build
     ENV.append "LDFLAGS", "-Wl,-rpath,#{lib}"
 
     system "meson", "setup", "build", *args, *std_meson_args
     system "meson", "compile", "-C", "build", "--verbose"
     system "meson", "install", "-C", "build"
+
+    # Manually create plist for system bus service
+    (prefix/"org.freedesktop.dbus-system.plist").write system_plist
```
Comment (carlocab) [inline Formula/d/dbus.rb]:
```suggestion
    (prefix/"org.freedesktop.dbus-system.plist").write system_plist if OS.mac?
```

File: Formula/d/dbus.rb (hunk 1 above)
Comment (EricFromCanada) [reply Formula/d/dbus.rb:86]: The problem with suggesting `sudo brew services start dbus --file=$(brew --prefix dbus)/org.freedesktop.dbus-system.plist` is that although the plist's `Label` is still set to "org.freedesktop.dbus-system", the plist is renamed and the service is started under the name "org.freedesktop.dbus-session". This results in a daemon that can no longer be managed with `brew services`:
```
$ sudo brew services start dbus --file=$(brew --prefix dbus)/org.freedesktop.dbus-system.plist
Password:
Warning: Taking root:admin ownership of some dbus paths:
  /opt/homebrew/Cellar/dbus/1.16.2/bin
  /opt/homebrew/Cellar/dbus/1.16.2/bin/dbus-daemon
  /opt/homebrew/opt/dbus
  /opt/homebrew/opt/dbus/bin
  /opt/homebrew/var/homebrew/linked/dbus
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Warning: dbus must be run as non-root to start at user login!
==> Successfully started `dbus` (label: org.freedesktop.dbus-session)

$ brew services info dbus
dbus (org.freedesktop.dbus-session)
Running: ✘
Loaded: ✘
Schedulable: ✘

$ sudo brew services stop dbus
Password:
Warning: Service `dbus` is not started.

$ sudo launchctl list | grep dbus
74515	0	org.freedesktop.dbus-system

$ sudo launchctl bootout system/org.freedesktop.dbus-system
```

**Review by p-linnane — APPROVED** [review]
Thanks Eric!
