### PR TITLE
nim: update formula to HEAD works (and simplify code)

### LINKED ISSUE #17907: Build error for nim-git
Building nim-git with Pakku just now resulted in this, tried with a recent nim-git also a 1.4 release.
```
/tmp/pakku-/nim-git/src/Nim/compiler/semtypes.nim(259, 78) Error: undeclared field: 'isNaN' for type system.BiggestFloat [declared in /tmp/pakku-/nim-git/src/Nim/lib/system.nim(1402, 3)] 
FAILURE
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'nim-git'
```
Possibly related to 
https://github.com/nim-lang/Nim/commit/3192995ac97ad0648b6d1e5a5a1a42d403b37e72
https://github.com/nim-lang/Nim/issues/16646
(It builds OK at the previous commit)

### LINKED ISSUE #18117: homebrew nim HEAD broken: Error: invalid command line option: '--hint'
I have nim on macOS Big Sur installed via Homebrew (the HEAD version).

When running `brew update`, I got these:
```
nim HEAD-22e06ee -> HEAD-22e06ee
==> Upgrading nim HEAD-22e06ee -> HEAD-22e06ee 
==> Cloning https://github.com/nim-lang/csources.git
Updating /Users/anta40/Library/Caches/Homebrew/nim--csources--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 64e34778 Update readme.markdown
==> Cloning https://github.com/nim-lang/Nim.git
Updating /Users/anta40/Library/Caches/Homebrew/nim--git
==> Checking out branch devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.
HEAD is now at d62a298a2 fix typo in ci/funs.sh (#18115)
...
...
...
/private/tmp/nim-20210528-7165-seu30s/config/nim.cfg(16, 1) Error: invalid command line option: '--hint'
```

Not sure how this relates with this commit:
https://github.com/nim-lang/Nim/pull/18085

### LINKED ISSUE #76550: nim --HEAD failing due to upstream changes
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.1.5-18-g4f4fb49
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4f4fb49481685208c5756c897944ae28757ca5c7
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7fd84fcfb65ae8a5faa90356020c2ae00bfbc8ad
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.OV4dGjRKuQ/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1205
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5

❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  afuse
  ccze
  ext2fuse
  ext4fuse
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/powerline-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
  /usr/local/Caskroom/miniconda/base/bin/pcre-config
  /usr/local/Caskroom/miniconda/base/bin/python3.8-config
  /Users/john.vandenberg/.cargo/bin/cargo-install-update-config
  /run/current-system/sw/bin/python-config
  /run/current-system/sw/bin/python3-config
  /run/current-system/sw/bin/python3.8-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.9/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  nim
  pyside
  dotnet
  googletest
  sip
  kubernetes-cli
  poppler
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the HEAD nim, as https://github.com/nim-dev/nimlint depends on it.

broken due to https://github.com/nim-lang/Nim/issues/17907

### What happened (include all command output)?

```
❯ brew install nim --HEAD
==> Cloning https://github.com/nim-lang/csources.git
Updating /Users/john.vandenberg/Library/Caches/Homebrew/nim--csources--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 64e3477 Update readme.markdown
==> Cloning https://github.com/nim-lang/Nim.git
Updating /Users/john.vandenberg/Library/Caches/Homebrew/nim--git
==> Checking out branch devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.
HEAD is now at 01f316c mention -d:nimLegacyConvEnumEnum in error msg (#17928)
==> /bin/sh build.sh
==> bin/nim c -d:release koch
==> ./koch boot -d:release -d:useLinenoise
Last 15 lines from /Users/john.vandenberg/Library/Logs/Homebrew/nim/03.koch:
Hint: macrocacheimpl [Processing]
Hint: vmprofiler [Processing]
Hint: evaltempl [Processing]
Hint: vmconv [Processing]
Hint: aliases [Processing]
Hint: patterns [Processing]
Hint: semmacrosanity [Processing]
Hint: active [Processing]
Hint: pluginsupport [Processing]
Hint: locals [Processing]
Hint: itersgen [Processing]
Hint: enumtostr [Processing]
Hint: spawn [Processing]
/private/tmp/nim-20210504-21598-mv0mn9/compiler/semtypes.nim(259, 78) Error: undeclared field: 'isNaN' for type system.BiggestFloat [declared in /private/tmp/nim-20210504-21598-mv0mn9/lib/system.nim(1397, 3)]
FAILURE

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

### What did you expect to happen?

nim HEAD should be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install nim --HEAD
```

### PR DESCRIPTION
**Pull request by timotheecour**
(will address the below points tomorrow)

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

* fix https://github.com/nim-lang/Nim/issues/17907
* fix https://github.com/Homebrew/homebrew-core/issues/76550
* fix https://github.com/nim-lang/Nim/issues/18117

### CODE REVIEW

**Comment by SMillerDev** [comment]
Since we don't actively support head builds and this breaks the build we do support I don't think we should merge this.

File: Formula/nim.rb [hunk 1]
```diff
@@ -14,28 +14,23 @@ class Nim < Formula
 
   head do
     url "https://github.com/nim-lang/Nim.git", branch: "devel"
-    resource "csources" do
-      url "https://github.com/nim-lang/csources.git"
-    end
   end
```
Comment (carlocab) [inline Formula/nim.rb:17]: We don't need a one-line `head` block. You can just put
```ruby
head "https://github.com/nim-lang/Nim.git", branch: "devel"
```
in the line after `license`.

File: Formula/nim.rb [hunk 2]
```diff
@@ -14,28 +14,23 @@ class Nim < Formula
...
 
   depends_on "help2man" => :build
 
   def install
     if build.head?
-      resource("csources").stage do
-        system "/bin/sh", "build.sh"
-        (buildpath/"bin").install "bin/nim"
-      end
+      system "/bin/sh", "build_all.sh"
```
Comment (carlocab) [inline Formula/nim.rb:23]: Does this download anything? Why do we no longer need the `csources` resource?

**Review by carlocab — CHANGES_REQUESTED** [review]
Thanks, @timotheecour. Just a few comments. When you make further changes, please squash them into one commit, and use the commit message
```
nim: fix HEAD
```
(or similar).

For future reference, please use the preferred commit-message style for homebrew/core. We put the name of the formula first in commit-message headings. Refer to the [documentation](https://docs.brew.sh/Formula-Cookbook#commit) or the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md) for more details.

File: Formula/nim.rb (hunk 2 above)
Comment (timotheecour) [reply Formula/nim.rb:23]: the details are handled inside build_all.sh which handles cloning a csources repo at the correct revision (it's not csources anymore, it's some csources_v1 due to recent changes to avoid breaking previous builds relying on HEAD of csources)

File: Formula/nim.rb (hunk 1 above)
Comment (timotheecour) [reply Formula/nim.rb]: done

File: Formula/nim.rb (hunk 2 above)
Comment (carlocab) [reply Formula/nim.rb:20]: I see. In that case, we can't use `build_all.sh` outside of `HEAD`, because formulae should not be downloading anything that isn't declared in a `resource` block at install time. See https://docs.brew.sh/Acceptable-Formulae#we-dont-like-install-scripts-that-download-unversioned-things.

Ideally, we shouldn't be doing this for `HEAD` either, but the existing `resource` block for `csound` isn't checksummed anyway.

Comment (timotheecour) [reply Formula/nim.rb]: > I see. In that case, we can't use build_all.sh outside of HEAD

i've updated comments accordingly; build_all.sh is only used for HEAD (in future we can declare a resource for csources_v1, clone it, and then call: `. ci/funs.sh && nimBuildCsourcesIfNeeded` to install it at the right revision; but it should be deferred to future work IMO since this is only done for HEAD)

**Comment by timotheecour** [comment]
PTAL

> When you make further changes, please squash them into one commit, and use the commit message

@carlocab no strong opinion here but why not instead do the squash at merge time (or optionally, even enforcing it via github settings > merge button > Allow squash merging  (and disabling the other 2 merging strategies)) so that intermediate commit history is preserved in PRs ?

also the squash merge requirement isn't mentioned in https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md

**Comment by carlocab** [comment]
> no strong opinion here but why not instead do the squash at merge time (or optionally, even enforcing it via github settings > merge button > Allow squash merging (and disabling the other 2 merging strategies)) so that intermediate commit history is preserved in PRs ?

Most PRs require a bottle commit to be merged simultaneously, and that's done by @BrewTestBot. Unfortunately, @BrewTestBot isn't quite smart enough yet to reword commit message headers properly when squashing several commits at a time.

We could do what you suggest for PRs that don't require a bottle commit (and indeed that's already what we do), but initially, your PR looked like it required a new bottle commit.

> also the squash merge requirement isn't mentioned in https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md

It's mentioned in the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook).

> Now, [open a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) for your changes.
> 
> * One formula per commit; one commit per formula.
> * Keep merge commits out of the pull request.

The cookbook is linked here:

>Ensure your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit).

**Review by carlocab — APPROVED** [review]
