### PR TITLE
julia: fix printing of `BigFloat`s

### LINKED ISSUE #131422: Homebrew-published Julia `1.9.0` version `BigFloat` behaving unexpectedly
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Copied from: https://github.com/JuliaLang/julia/issues/49895


julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292* (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
2.0
```

compare to:

```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
1.5
```

`1.9.0` was installed via `homebrew` (i.e. `brew install julia`) and `1.8.5` via `juliaup` (`brew install juliaup; juliaup add 1.8.5`).

I then tried installing `1.9.0` via `juliaup` (`juliaup add 1.9.0; juliaup default 1.9.0`) and now it works as expected (but the `versioninfo()` string is _slightly_ different in the way it prints the commit hash?)

```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
1.5
```

So there seems to be something going on with the `1.9.0` builds being published to homebrew.

This is also being reported by other people on StackOverflow: https://stackoverflow.com/questions/76222931/how-to-use-setprecision-in-julia-under-macos

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use the `BigFloat` types in `julia 1.9.0` because... they're useful

### What happened (include all command output)?

They did not work as expected:

```
julia> x = BigFloat(1.5)
2.0
```

### What did you expect to happen?

Installing through `juliaup` works as expected:

```
julia> x = BigFloat(1.5)
1.5
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install julia
$ julia

julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292* (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
2.0
```

Working:

```
$ brew install juliaup
$ juliaup add 1.9.0
$ juliaup default 1.9.0
$ julia

julia> versioninfo()

Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
1.5
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is needed because we use a newer version of MPFR.

Closes #131422

### CODE REVIEW

File: Formula/julia.rb [hunk 1]
```diff
@@ -1,15 +1,26 @@
...
+    # Issue ref: https://github.com/JuliaLang/julia/issues/47884
+    url "https://github.com/JuliaLang/julia/releases/download/v1.9.0/julia-1.9.0-full.tar.gz"
+    sha256 "222eb533c9dc54734949eb3a4169f54aefa1bc20be385fc1cf798c8219fe6400"
+
+    # Fix printing of BigFloats with new MPFR.
+    # https://github.com/Homebrew/homebrew-core/issues/131422
+    patch do
+      url "https://github.com/JuliaLang/julia/commit/1e5fdb29f8858f3244f6aff116ee12e4c8247f3a.patch?full_index=1"
+      sha256 "973087cdfa646f714f1dcfdb0cc8e36d33a6e2be36d1a8facf8e3c0310730ff8"
+    end
```
Comment (Bo98) [inline Formula/julia.rb:21]: We probably don't want the API additions this patch has.

Comment (Bo98) [reply Formula/julia.rb:21]: Use https://github.com/JuliaLang/julia/commit/5d43397ee52323f1c015513b2be3909078b646ef

File: Formula/julia.rb [hunk 2]
```diff
@@ -1,15 +1,26 @@
...
+  stable do
+    # Use the `-full` tarball to avoid having to download during the build.
+    #
+    # TODO: Use system `suite-sparse` when `julia` supports v7.
+    # Issue ref: https://github.com/JuliaLang/julia/issues/47884
+    url "https://github.com/JuliaLang/julia/releases/download/v1.9.0/julia-1.9.0-full.tar.gz"
+    sha256 "222eb533c9dc54734949eb3a4169f54aefa1bc20be385fc1cf798c8219fe6400"
+
+    # Fix printing of BigFloats with new MPFR.
+    # https://github.com/Homebrew/homebrew-core/issues/131422
```
Comment (Bo98) [inline Formula/julia.rb:17]: Just to note, this will be fixed in 1.9.1.

**Review by Bo98 — APPROVED** [review]
