### PR TITLE
gpsbabel: add -std=c++11 to compilation flags

### LINKED ISSUE #7023: gpsbabel failed to build on 10.12.1
Trying to build gpsbabel on Sierra fails.  Output at

https://gist.github.com/23d23a037817196bdb8bbe8a75c13333

At first sight it might be due to a missing CXXFLAGS=-std=c++11 flag?

### PR DESCRIPTION
**Pull request by toeklk**
This one should fix issue #7023 .  As this is my first attempt at contributing, and I'm not sure if this is the most appropriate way of fixing, please review carefully!

Fixes #7023

### CODE REVIEW

File: Formula/gpsbabel.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@ class Gpsbabel < Formula
 
   def install
     args = ["--disable-debug", "--disable-dependency-tracking",
-            "--prefix=#{prefix}"]
+            "--prefix=#{prefix}", "CXXFLAGS=-std=c++11"]
```
Comment (woodruffw) [inline Formula/gpsbabel.rb]: `ENV.cxx11` should be used instead of modifying `args`.

Just call it before `args` is declared and everything should be fine.

**Review by woodruffw — CHANGES_REQUESTED** [review]

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
LGTM, thanks for contributing @toeklk!
