### PR TITLE
gcc: avoid BOOT_CFLAGS

### LINKED ISSUE #235732: Homebrew gcc runs much slower than the corresponding Ubuntu gcc of the same version on Linux
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
(See the Dockerfile below)
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.
- [x] My issue is not about a failure to build a formula from source.

### What were you trying to do (and why)?

I notice that Homebrew gcc runs much slower than the corresponding Ubuntu gcc of the same version on Linux. As an example, when building [Abseil LTS 20250814.0](https://github.com/abseil/abseil-cpp/releases/tag/20250814.0) using the default build options, `gcc@13` installed via Homebrew is almost 4x slower than `gcc-13` installed via Ubuntu's `apt-get`:

```plaintext
# Ubuntu gcc-13
real   0m18.604s
user   2m8.699s
sys    0m9.893s

# Homebrew gcc@13
real  1m4.824s
user  7m58.068s
sys   0m16.152s
```

The results can be reproduced using the following Dockerfile:

```dockerfile
FROM ubuntu:24.04

SHELL ["/bin/bash", "-c"]

RUN set -ex; \
    apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential curl file git procps; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    touch /.dockerenv; \
    NONINTERACTIVE=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

RUN set -ex; \
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"; \
    brew install gcc@13 cmake ninja

RUN git clone --branch=20250814.0 --depth=1 https://github.com/abseil/abseil-cpp.git

RUN set -ex; \
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"; \
    cd abseil-cpp; \
    mkdir build-ubuntu && cd build-ubuntu; \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++-13 -G Ninja ..; \
    time ninja

RUN set -ex; \
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"; \
    cd abseil-cpp; \
    mkdir build-homebrew && cd build-homebrew; \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/home/linuxbrew/.linuxbrew/bin/g++-13 -G Ninja ..; \
    time ninja
```

The difference is also reproducible with other versions of gcc (e.g., `gcc@14`) and other C++ projects.

### What happened (include all command output)?

See above.

### What did you expect to happen?

See above.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

libgccjit in separate PR

Closes #235732

### CODE REVIEW

File: Formula/g/gcc.rb [hunk 1]
```diff
@@ -120,24 +120,22 @@ def install
...
-      args << "--with-boot-ldflags=-static-libstdc++ -static-libgcc #{ENV.ldflags}"
-
       # Fix Linux error: gnu/stubs-32.h: No such file or directory.
       args << "--disable-multilib"
 
       # Enable to PIE by default to match what the host GCC uses
       args << "--enable-default-pie"
 
+      # Use GNU hash tables similar to Linux distros for better performance
+      args << "--with-linker-hash-style=gnu"
```
Comment (cho-m) [inline Formula/g/gcc.rb]: Trying this out too. Didn't backport to versioned GCC as not sure of compatibility impact. May need to check if anything still uses "sysv" hash tables and if we need to force `-Wl,--hash-style=gnu` into superenv.

I think most Linux distros already do this or something similar, e.g.
- Arch Linux[^1]
- Fedora[^2]
- Debian[^3] - via patch

There is a size and performance improvement from only GNU hash. Glibc >= 2.36 will only support GNU hash[^4] (unless manually worked around like https://salsa.debian.org/glibc-team/glibc/-/commit/88d22cad4ace523059c0756d77449e7f10bda003)

[^1]: https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/blob/main/PKGBUILD?ref_type=heads#L84
[^2]: https://src.fedoraproject.org/rpms/gcc/blob/rawhide/f/gcc.spec#_1177
[^3]: https://salsa.debian.org/toolchain-team/gcc/-/blob/master/debian/patches/gcc-hash-style-gnu.diff?ref_type=heads
[^4]: https://www.phoronix.com/news/Glibc-2.36-EAC-Problems

**Review by carlocab — APPROVED** [review]

**Comment by fxcoudert** [comment]
About `--with-linker-hash-style=gnu`, Linux distro also build binutils with `--enable-default-hash-style=gnu`. Do we want that? Are we sure that all our supported linux/glibc/binutils versions are compatible with that? I am trying to digest https://maskray.me/blog/2022-08-21-glibc-and-dt-gnu-hash

**Comment by cho-m** [comment]
> About `--with-linker-hash-style=gnu`, Linux distro also build binutils with `--enable-default-hash-style=gnu`. Do we want that? 

Will check on binutils. Likely want that to match host toolchain.

> Are we sure that all our supported linux/glibc/binutils versions are compatible with that? 

I'm also trying to make sure. We do use Ubuntu/Debian toolchain already so I think we are implicitly using their patch (i.e. GCC will pass `--hash-style=gnu` and ld will default to GNU hash) when building most formulae. 

GCC itself may be one of exceptions as it is bootstrapping. This results in our Linux GCC bottles with both section headers:
```
  [ 3] .gnu.hash         GNU_HASH         00000000003f1ab0  00001ab0
       00000000000000ac  0000000000000000   A       2     0     8
  [ 4] .hash             HASH             00000000003f1b60  00001b60
       0000000000000480  0000000000000004   A       2     0     8
```

Though build-from-source users is the tricky part to verify.

**Comment by cho-m** [comment]
Can also defer to a separate PR/issue to discuss further as GNU hash is a minor impact compared to restoring `-O2`.

**Comment by fxcoudert** [comment]
@cho-m I'd rather split this into the short-term fix, and then a later PR to test GNU hash (enabling it on both binutils and gcc to see if anything breaks)

**Review by fxcoudert — APPROVED** [review]
