### PR TITLE
Fix lastpass-cli install with or without docs

### LINKED ISSUE #9740: brew install lastpass-cli --with-pinentry fails
### Bug reports:
I am running brew v1.1.9 on OSX 10.12.3

I ran `brew install lastpass-cli --with-pinentry`

and received 
```bash
==> Using the sandbox
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v1.1.2.tar.gz
Already downloaded: /Users/lphilbrook/Library/Caches/Homebrew/lastpass-cli-1.1.2.tar.gz
==> make PREFIX=/usr/local/Cellar/lastpass-cli/1.1.2 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/1.1.2/share/man install-doc
Last 15 lines from /Users/lphilbrook/Library/Logs/Homebrew/lastpass-cli/02.make:
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/lastpass-cli-20170207-12595-my48hu/lastpass-cli-1.1.2/build
/Library/Developer/CommandLineTools/usr/bin/make -C build install-doc
Scanning dependencies of target doc-man
[100%] Generating lpass.1
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20170207-12595-my48hu/lastpass-cli-1.1.2/build/lpass.1.xml" returned non-zero exit status 5
make[4]: *** [lpass.1] Error 1
make[3]: *** [CMakeFiles/doc-man.dir/all] Error 2
make[2]: *** [CMakeFiles/install-doc.dir/rule] Error 2
make[1]: *** [install-doc] Error 2
make: *** [install-doc] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

Running these commands first seemed to solve it.
```bash
brew reinstall asciidoc --with-docbook-xsl
export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
```

### PR DESCRIPTION
**Pull request by phoolish**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Fixes #9740 by making doc installation optional.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CI shows all nodes passing without this PR: https://jenkins.brew.sh/job/Homebrew%20Testing/281/

File: Formula/lastpass-cli.rb [hunk 1]
```diff
@@ -13,15 +13,20 @@ class LastpassCli < Formula
     sha256 "710ae68c279e7fa9f63a4c79c4137448e1d00b14f5cb5885cc09da41e6fee22e" => :yosemite
   end
 
-  depends_on "asciidoc" => :build
+  option "with-doc", "Build man pages"
```
Comment (DomT4) [inline Formula/lastpass-cli.rb]: Can we use `with-docs` instead? It's slightly more common in core.

**Comment by ilovezfs** [comment]
Actually going to close this out until someone can tell me how to reproduce this issue as it doesn't affect CI.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @phoolish!
