### PR TITLE
tcl-tk: fixes #12114 for python and #12808 for python3 by bumping tcl-tk version

### LINKED ISSUE #12114: python --with-tcl-tk crashes, buffer overflow error
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/0f94790ebaa91323ab885ddfe587cd6a

To help us debug your issue please explain:
- What you were trying to do (and why)
  - Trying to install python 2.7 with TK interface
  - The purpose is to run pyraf in OSX
- What happened (include command output)
  - installed tcl-tk with `brew install tcl-tk` without error
  - added `export PATH="/usr/local/opt/tcl-tk/bin:$PATH"` to .bash_profile and sourced it
  - installed python with `brew install python --with-tcl-tk` without error
  - test by running `python -m Tkinter` => crash with `Abort trap: 6`
- What you expected to happen
  - Tkinter does not crash
- Step-by-step reproduction instructions (by running `brew install` commands)
  - `brew install tcl-tk`
  - `brew install python --with-tcl-tk`
  - `python -m Tkinter`

Additional info:
- OSX Sierra
- Retried after installing all OS patch and Xcode patches
- Brew doctor reported nothing

Apple crash info:

    Crashed Thread:        0  Dispatch queue: com.apple.main-thread

    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000
    Exception Note:        EXC_CORPSE_NOTIFY

    Application Specific Information:
    detected buffer overflow

Stack trace: --unfortunately could not figure out how to install debug symbols

    frame #0: 0x00007fff90801d42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff908ef5bf libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff90767420 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff90767592 libsystem_c.dylib`abort_report_np + 181
    frame #4: 0x00007fff9078df28 libsystem_c.dylib`__chk_fail + 48
    frame #5: 0x00007fff9078def8 libsystem_c.dylib`__chk_fail_overflow + 16
    frame #6: 0x00007fff9078e145 libsystem_c.dylib`__strcpy_chk + 83
    frame #7: 0x00000001025cbe86 libtk8.6.dylib`Tk_WmObjCmd + 12920
    frame #8: 0x000000010265779f libtcl8.6.dylib`TclNRRunCallbacks + 80
    frame #9: 0x00000001005eea92 _tkinter.so`Tkapp_Call + 425
    frame #10: 0x0000000100116623 Python`PyEval_EvalFrameEx + 9903
    frame #11: 0x0000000100113d7f Python`PyEval_EvalCodeEx + 1621
    frame #12: 0x000000010011c58d Python`fast_function + 298
    frame #13: 0x0000000100116557 Python`PyEval_EvalFrameEx + 9699
    frame #14: 0x000000010011c528 Python`fast_function + 197
    --snip--
    frame #37: 0x00007fff906d3235 libdyld.dylib`start + 1
    frame #38: 0x00007fff906d3235 libdyld.dylib`start + 1

### PR DESCRIPTION
**Pull request by telamonian**
to a version in which the upstream has fixed the relevant bugs.

Hopefully this is a better attempt at a fix than my last one (#15855).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [mostly] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
 
So apparently all of the trouble that people have been having with `brew python install --with-tcl-tk` and `brew python3 install --with-tcl-tk` (#12114 and #12808) is due to a whole mess of bugs in the upstream that have apparently all been fixed.

However, there's still no official release aside from the version of 8.6.6 that was put out last year. So what I've done is to update the formula so that it pulls from the core_8_6_7_rc branch in which all of the relevant fixes have been applied. After installing tcl-tk with the updated formula and then building python2/3 with `--with-tcl-tk`, `brew test` passes for both pythons, and both of

    python -c 'import Tkinter; root = Tkinter.Tk(); root.mainloop()'
    python3 -c 'import tkinter; root = tkinter.Tk(); root.mainloop()'

open an application window as expected, so everything seems good.

The one remaining hiccup is that `brew audit --strict` is still picking up a single error. This is due to the fact that tk now installs a couple of icon files (`Tk.icns` and `Tk.tiff`) in `/usr/local/opt/tcl-tk/lib` alongside the libraries, and audit really doesn't like that. I looked through the `configure` and `makefile` files in tk, and the installation of the icons into the library appears to be intended behavior on the part of the tcltk devs. How should I fix this?

### CODE REVIEW

**Comment by ilovezfs** [comment]
Don't worry about the audit issue.

However, this version will need to go in a `devel do` block until upstream puts out an actual new release.

**Comment by telamonian** [comment]
Can do. Can you please point me to a good example of a `devel do` block in an existing formula?

**Comment by ilovezfs** [comment]
`dbus`

**Comment by telamonian** [comment]
I put the 8.6.7 stuff in a `devel do` block, and I brought back the old 8.6.6 stuff in a `stable do` block so that devel could have it's own separate `tk` resource.

File: Formula/tcl-tk.rb [hunk 1]
```diff
@@ -1,18 +1,40 @@
...
+    end
+  end
+
   bottle do
     sha256 "de26155e0b2fee960af4791d39e3d6c79421c635c0a914be8a0254ff28f4fad2" => :sierra
     sha256 "9481cea8f38c644eb12f6a42463082469f1e91fe7616b167fbda46ded9bef336" => :el_capitan
     sha256 "f137c8176792d8363989981c2f3838f8edee73738a02bf899caddd8460abdd86" => :yosemite
   end
 
+  devel do
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: actually let's make this `head do` since there's no 8.6.7-rc tag yet

File: Formula/tcl-tk.rb [hunk 2]
```diff
@@ -1,18 +1,40 @@
...
+    url "https://github.com/tcltk/tcl/archive/a29278e79c748bfaf8766c486eb93eca7ad586be.tar.gz"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: `url "https://github.com/tcltk/tcl.git", :branch => "core_8_6_7_rc"`

File: Formula/tcl-tk.rb [hunk 3]
```diff
@@ -1,18 +1,40 @@
...
+    version "8.6.7"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: remove this line please

File: Formula/tcl-tk.rb [hunk 4]
```diff
@@ -1,18 +1,40 @@
...
+    sha256 "90202b013184fea551a5800404f572b1b4cbadaebc60dfaa6516a7d8ad837fff"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: remove this line please

File: Formula/tcl-tk.rb [hunk 5]
```diff
@@ -1,18 +1,40 @@
...
+
+    resource "tk" do
+      url "https://github.com/tcltk/tk/archive/8aecb568ca2896cfae4253ead2fe62442d977b55.tar.gz"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: `url "https://github.com/tcltk/tk.git", :branch => "core_8_6_7_rc"`

File: Formula/tcl-tk.rb [hunk 6]
```diff
@@ -1,18 +1,40 @@
...
+      version "8.6.7"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: remove this line please

File: Formula/tcl-tk.rb [hunk 7]
```diff
@@ -1,18 +1,40 @@
...
+      sha256 "3c4f38783f2fca6e0b4e9152279fbc0576e63cbbd8024e47a006497dd8db4379"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: remove this line please

File: Formula/tcl-tk.rb [hunk 8]
```diff
@@ -58,7 +73,7 @@ def install
 
         cd "unix" do
           system "./configure", *args
-          system "make", "TK_LIBRARY=#{lib}"
```
Comment (ilovezfs) [inline Formula/tcl-tk.rb]: why this change?

**Review by ilovezfs — CHANGES_REQUESTED** [review]

File: Formula/tcl-tk.rb (hunk 8 above)
Comment (telamonian) [inline Formula/tcl-tk.rb]: Originally I thought that passing an explicit `TK_LIBRARY` might be what was causing the icon files to install to the lib. But what I found over the course of about a dozen test builds is that it makes no difference to any part of the build whether that argument is there or not.

Since it wasn't doing anything, and seems like a potential source of issues, I removed it.

**Comment by telamonian** [comment]
Changing from `devel` to `head` broke the build. Long story short, a flag along the lines of `-L/usr/local/Cellar/tcl-tk/head-a29278e/lib` gets passed to `clang` during the `tk` portion of the build. The flag is necessary in order for some previously built libs to be found, but some part of superenv seems to be removing/sanitizing the libpath before it actually gets passed to the linker.

I did manage to get the build working, but I had to change a couple of things around in the formula and in one of the low level homebrew `.rb` files.

**Comment by ilovezfs** [comment]
@telamonian that may be a `brew` bug.

CC @MikeMcQuaid it sounds like superenv is allowing `#{lib}` for stable and devel, but filtering `#{lib}` out for head.

**Comment by telamonian** [comment]
Maybe? I know at least half of what went wrong with superenv

First, I had to remove the `revision 1` statement from the `tcl-tk` formula. For whatever reason, it seems like having a `_1` in the `L/usr/local/Cellar/tcl-tk/head-a29278e_1/lib` flag is too much for some part of superenv, though I still have no idea which.

I also had to change line 214 in `$(brew --prefix)/Homebrew/Library/Homebrew/shims/super/cc` from

    if formula_prefix && path.start_with?("#{formula_prefix}/")

to 

    if formula_prefix && path.start_with?("#{formula_prefix}")

Basically, `formula_prefix` was set to `/usr/local/Cellar/tcl-tk/head`, whereas path was `set` to `/usr/local/Cellar/tcl-tk/head-a29278e/lib`, so with the extra forward slash `/usr/local/Cellar/tcl-tk/head/` did not match to the start of `path`. Once path fails that check, it leads to a couple of other events that then cause it to be filtered out.

If there's a security concern to removing the forward slash from the end of the check, maybe `formula_prefix` can be changed in order to include the commit-specific stuff that gets stuck on the end of a head cellar path?

**Comment by ilovezfs** [comment]
@telamonian this reminds me of
https://github.com/Homebrew/brew/issues/535
https://github.com/Homebrew/brew/pull/536

CC @vladshablinsky

**Comment by telamonian** [comment]
Okay, merged all of the changes and tested them. There's no revision spec in there at the moment, so that's not a problem, but you do still definitely need to hack the `cc` shim. 

The `devel` version was working pretty well, and without all of this `head` related craziness. What would you think about maybe rolling back to the `devel` version of the formula?

**Comment by ilovezfs** [comment]
@telamonian I'm fine with using `devel do` if you can convince upstream to create `8.6.7-rc1` tags for tcl and tk for us to use!

**Comment by ilovezfs** [comment]
@telamonian you'll need to squash this down to a single commits so that the `brew pull` doesn't :boom:

**Comment by telamonian** [comment]
Trying to get the tcltk devs to release a tag when _I_ want them to sounds about as futile as me trying to convince you to bring back the `--with-x11` option for the `tcl-tk` formula  :)

**Comment by ilovezfs** [comment]
@telamonian you might be surprised. It's "only" a beta/rc/alpha/pre/whatever tag you'd be asking for.

**Comment by telamonian** [comment]
I'm not really that familiar with squash. I was looking through the docs, and there seem to be a lot of choices. Also, I hadn't realized that I managed to pull in 95 unrelated commits when I fixed those conflicts. 

What's the best practice for squashing in this situation? I assume that I'm not going to want to preserve my entire git log.

**Comment by ilovezfs** [comment]
@telamonian you can follow the steps here https://github.com/Homebrew/homebrew-core/pull/15721#issuecomment-316674549

**Comment by ilovezfs** [comment]
@telamonian it looks like upstream has posted 8.6.7rc0 on SourceForge, so we can use that for devel, if you'd like to refresh this PR.

**Comment by ilovezfs** [comment]
@telamonian ping

**Comment by telamonian** [comment]
I'll take care of this tonight. I assume you didn't merge a week ago because of the HEAD related issues in `brew`? I have two questions then:

- Should I strip the semi-functional HEAD build?
- Assuming the devel is fine, will you merge this soon? Looking at Homebrew/homebrew-science#5505 there's apparently already been a couple of people who have tried to use the new `tcl-tk` formula without realizing that it hasn't been pulled in yet.

**Comment by ilovezfs** [comment]
>I assume you didn't merge a week ago because of the HEAD related issues in brew

Right.

>Should I strip the semi-functional HEAD build?

Yes.

>Assuming the devel is fine, will you merge this soon?

Yes.

**Comment by telamonian** [comment]
All done/tested. Let me know if anything else is needed before the new tcl-tk can be merged.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@telamonian Thanks for your first contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!
