### PR TITLE
podman: remove unstartable macOS service

### LINKED ISSUE #118717: podman service fails to start on macOS
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
local:~ $ brew config
HOMEBREW_VERSION: 3.6.16-2-gf679990
ORIGIN: https://github.com/Homebrew/brew
HEAD: f679990d7918d9f99d9c6c99b7bec504bc4088fe
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ef78c6f3fc65c97c272ac000b598767543f72d77
Core tap last commit: 32 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_FORCE_VENDOR_RUBY: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/opt/git/bin/git
Curl: 7.86.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 12.6.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
local:~ $ brew doctor
Your system is ready to brew.
local:~ $
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'd like to automatically start `podman machine` in order to run Linux containers on macOS. There is a Homebrew service included with `podman`, but it fails to start on macOS. 

### What happened (include all command output)?

```
local:~ $ brew services start podman
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/503 /Users/jfoy/Library/LaunchAgents/homebrew.mxcl.podman.plist` exited with 5.
local:~ $ cat ~/Library/LaunchAgents/homebrew.mxcl.podman.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin</string>
	</dict>
	<key>Label</key>
	<string>homebrew.mxcl.podman</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/podman/bin/podman</string>
		<string>system</string>
		<string>service</string>
		<string>--time=0</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/opt/homebrew</string>
</dict>
</plist>
local:~ $ /opt/homebrew/opt/podman/bin/podman system service --time=0
Error: unknown flag: --time
See 'podman system --help'
local:~ $
```

### What did you expect to happen?

Since `podman-remote` is installed as `podman` under macOS, service startup should probably look a lot like the formula's test block and run `podman machine` using a legal image: 

```
    if OS.mac?
      out = shell_output("#{bin}/podman-remote machine init --image-path fake-testi123 fake-testvm 2>&1", 125)
      assert_match "Error: open fake-testi123: no such file or directory", out
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Under macOS
brew install podman
brew services start podman
```

### PR DESCRIPTION
**Pull request by jfoy**
Closes https://github.com/Homebrew/homebrew-core/issues/118717

`podman system service` can only start on a Linux host. On other platforms, Podman instead recommends use of the podman-desktop Cask to automatically start a default machine on login.

Alternatives considered included a macOS-specific wrapper script which could give default `podman machine init` and startup behavior, but this would be net-new functionality not provided by upstream podman.

Formula note: this change introduces use of the new hash syntax to define a service using per-OS run commands.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jfoy** [comment]
Draft pending Linux acceptance testing per https://github.com/Homebrew/homebrew-core/issues/118717#issuecomment-1376570915

**Comment by SMillerDev** [comment]
I'm not sure what you expect this change to do, but this is not a valid place for a service block so it won't be read anymore.

**Comment by jfoy** [comment]
Linux testing failed, so this change is stalled pending https://github.com/Homebrew/brew/issues/14352.

**Comment by jfoy** [comment]
@dawidd6 Thanks for completing the work to enable this change. I've updated the PR to reflect the new OS support in the service `run` command. Please review when you have a moment.

File: Formula/podman.rb [hunk 1]
```diff
@@ -148,10 +148,18 @@ def caveats
...
       EOS
     end
+    on_macos do
+      <<-EOS
+        In order to run containers locally, podman depends on a Linux kernel.
+        One can be started manually using `podman machine` from this package.
+        To start a podman VM automatically at login, also install the cask
+        "podman-desktop".
+      EOS
+    end
```
Comment (dawidd6) [inline Formula/podman.rb:158]: I don't think those are Homebrew-specific. This information is already present in the documentation of podman, where it belongs.

```suggestion
```

**Review by dawidd6 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by jfoy** [comment]
@chenrui333 @dawidd6 Bump. What's required in order to merge?

**Comment by dawidd6** [comment]
Waiting for a new `brew` release to get the necessary stuff for stable users.
