### PR TITLE
convco 0.4.1

### LINKED ISSUE #123: pgtune source url no longer exists
```
$ brew install pgtune
==> Downloading http://pgfoundry.org/frs/download.php/2449/pgtune-0.9.3.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pgtune"
Download failed: http://pgfoundry.org/frs/download.php/2449/pgtune-0.9.3.tar.gz
```

http://pgfoundry.org looks like it no longer exists.

Installing head still works:

```
$ brew install pgtune --HEAD
==> Cloning https://github.com/gregs1104/pgtune.git
Cloning into '/Library/Caches/Homebrew/pgtune--git'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 5), reused 9 (delta 3), pack-reused 0
Unpacking objects: 100% (14/14), done.
Checking connectivity... done.
==> Checking out branch master
🍺  /usr/local/Cellar/pgtune/HEAD: 10 files, 180.7K, built in 1 second
```

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>### Features

* strip prefix regex (3f0d30d)
* make `zlib-ng-compat` a default feature flag (4b17cb6)

### Fixes

* **check:** check should not fail if read from stdin (69ace8d), closes #130
* **check:** check should fail on unrecognized types from stdin (951253f),
closes #53
* parse issues in description (2778b81), closes #122
* **changelog:** changelog generator should respect the --prefix flag for
unreleased version (011d2ad), closes #123
</pre>
</details>

### CODE REVIEW

File: Formula/convco.rb [hunk 1]
```diff
@@ -18,12 +18,10 @@ class Convco < Formula
 
   depends_on "pkg-config" => :build
   depends_on "rust" => :build
-  depends_on "libgit2@1.5"
+  depends_on "libgit2"
 
   def install
-    # Link with a shared library instead of building a vendored version
-    inreplace "Cargo.toml", ', features = [ "zlib-ng-compat" ]', ""
-    system "cargo", "install", *std_cargo_args
```
Comment (chenrui333) [inline Formula/convco.rb:26]: - relates to https://github.com/convco/convco/pull/129

**Review by p-linnane — APPROVED** [review]
