### PR TITLE
sing-box: fix startup error

### LINKED ISSUE #168942: brew services start sing-box couldn't start, the cmd in services plist lack of '--directory string' which used for  set working directory
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs sing-box
Error: No logs.

brew config
HOMEBREW_VERSION: 4.2.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0476c2e5e4f02b409084553896340b2f4ab3352e
Last commit: 7 days ago
Core tap JSON: 13 Apr 11:45 UTC
Core cask tap JSON: 13 Apr 11:45 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.4-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

After `brew install sing-box`, I want to use `brew services` to manage sing-box autostart/running in background.

 I find sing-box's plist in 

`/usr/local/Cellar/sing-box/1.8.11/homebrew.mxcl.sing-box.plist`

which inidicates `config.json` location

```plist
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/opt/sing-box/bin/sing-box</string>
		<string>run</string>
		<string>--config</string>
		<string>/usr/local/etc/sing-box/config.json</string>
	</array>
```

I create `/usr/local/etc/sing-box/config.json`

Test by direct run `sudo /usr/local/opt/sing-box/bin/sing-box run --config /usr/local/etc/sing-box/config.json` in directory `/usr/local/opt/sing-box/bin/`, success starts. Using sudo because of sing-box runs in tun mode

but when I use `sudo brew service start sing-box`, it wouldn't start sing-box.

### What happened (include all command output)?

The sing-box don't start in background, 
Run `sudo brew services` or `sudo brew info sing-box` will show error but without msg.

(below screenshot I add `-d` to show what happens)

截屏2024-04-13 23 07 43

### What did you expect to happen?

The sing-box start in background, and managed by brew services

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install sing-box

sudo brew services start sing-box
```

### PR DESCRIPTION
**Pull request by Litchi2049**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #168942

### CODE REVIEW

File: Formula/s/sing-box.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ def install
   end
 
   service do
-    run [opt_bin/"sing-box", "run", "--config", etc/"sing-box/config.json"]
+    run [opt_bin/"sing-box", "run", "--config", etc/"sing-box/config.json", "--directory", etc/"sing-box"]
```
Comment (cho-m) [inline Formula/s/sing-box.rb:29]: May be better to set `--directory` as subdirectory of `var` rather than `etc`.

Upstream's systemd service as an example https://github.com/SagerNet/sing-box/blob/dev-next/release/config/sing-box.service#L9
```service
ExecStart=/usr/bin/sing-box -D /var/lib/sing-box -C /etc/sing-box run
```

It looks like they define 2 separate directories for these to align to common Linux directory structure.

**Comment by Litchi2049** [comment]
@cho-m Please review, thanks

**Review by cho-m — APPROVED** [review]
