### PR TITLE
vulkan-loader: fix include dir in .pc file

### LINKED ISSUE #152107: pkg-config include path of vulkan-loader points to an non-exist directory
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.16-15-gee9766a
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: ee9766aa7c72c04b33f309cced3922ad7d9637d1
Last commit: 3 days ago
Core tap origin: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: 8e40ab2571435ec7149d148756894a9d95ee2439
Core tap last commit: 5 days ago
Core tap branch: master
Core tap JSON: 23 Oct 00:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
HOMEBREW_BREW_GIT_REMOTE: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```
```


### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue. **Irrelevant**
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem. **Irrelevant**
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

```bash
$ brew install vulkan-loader vulkan-headers
$ pkg-config vulkan --cflags
```

### What happened (include all command output)?

```
$ brew install vulkan-loader vulkan-headers
$ pkg-config vulkan --cflags
-I/opt/homebrew/Cellar/vulkan-loader/1.3.268/include
$ command ls /opt/homebrew/Cellar/vulkan-loader/1.3.268/include
ls: cannot access '/opt/homebrew/Cellar/vulkan-loader/1.3.268/include': No such file or directory
```

### What did you expect to happen?

`pkg-config vulkan --cflags` should print `-I/opt/homebrew/Cellar/vulkan-headers/1.3.268/include` or `-I/opt/homebrew/opt/vulkan-headers/include` or `-I/opt/homebrew/opt/include`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install vulkan-loader vulkan-headers
$ pkg-config vulkan --cflags
```

### PR DESCRIPTION
**Pull request by rcombs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This is necessary for packages that pull in `vulkan` via pkgconfig to work, since the vulkan headers and .pc file are provided by separate formulae.

closes #152107

### CODE REVIEW

File: Formula/v/vulkan-loader.rb [hunk 1]
```diff
@@ -34,8 +34,12 @@ class VulkanLoader < Formula
   end
 
   def install
+    inreplace "loader/vulkan.pc.in" do |s|
+      s.gsub!(/includedir=.*/, "includedir=#{Formula["vulkan-headers"].include}")
+    end
```
Comment (SMillerDev) [inline Formula/v/vulkan-loader.rb:39]: Is there an upstream issue for this?

Comment (rcombs) [reply Formula/v/vulkan-loader.rb:39]: I'm not sure this is really an _issue_ upstream per se; they just expect that headers will be installed with the same prefix as the loader (which is true in traditional linux package management). In theory they could probably format this into the .pc themselves, but I could see that causing issues for some other cases.

Comment (SMillerDev) [reply Formula/v/vulkan-loader.rb:39]: How about asking them to make the header install location configurable?

Comment (rcombs) [reply Formula/v/vulkan-loader.rb:39]: Hmmm, it looks like it _used_ to be (since https://github.com/KhronosGroup/Vulkan-Loader/commit/d9faa0f8442d13fff3041f92c299a6361a4ebf41), but that was removed in https://github.com/KhronosGroup/Vulkan-Loader/commit/520eaa5a525adce0cdbdc7b8c7f7d8f0375340a6 to address https://github.com/KhronosGroup/Vulkan-Loader/issues/1318 and https://github.com/KhronosGroup/Vulkan-Loader/issues/1319 (BSD/Nix stuff).

We used to have an `inreplace` like this, but it was removed in 498d5de38c74b34a24b484abc75e38a26149d38f (#150267) for reasons I'm not clear on. There's currently an open issue for this (#152107).

Comment (rcombs) [reply Formula/v/vulkan-loader.rb:39]: Oh, wait, no, this was never actually supported upstream. Hmm. Though I'm pretty sure that if they _did_ add it, it'd break @jbeich's use-case (which involves building to a tmp dir), at least initially.

Comment (SMillerDev) [reply Formula/v/vulkan-loader.rb:39]: Could you make an issue asking them to add that choice back? Then I'd be fine with the inreplace until they do.

Comment (jbeich) [reply Formula/v/vulkan-loader.rb:39]: Vulkan-Loader can be built with **bundled** Vulkan-Headers. It can be used to update Vulkan-Headers independently, when Vulkan-Loader fails to build with the new version.

Comment (rcombs) [reply Formula/v/vulkan-loader.rb:39]: Hmm, maybe `vulkan-headers` shouldn't be its own formula, and instead `vulkan-loader` (renamed to `vulkan`?) should pull the headers in as a resource?

Comment (rcombs) [reply Formula/v/vulkan-loader.rb:39]: In any case, filed https://github.com/KhronosGroup/Vulkan-Loader/issues/1359 for now.

Comment (juan-lunarg) [reply Formula/v/vulkan-loader.rb:39]: Specifying `CMAKE_INSTALL_FULL_INCLUDEDIR` should work based on what I am seeing here. You will also need to specify `CMAKE_INSTALL_FULL_LIBDIR` and ensure CMAKE_INSTALL_PREFIX evaluates to an empty string.

```
    # BUG: The following code will NOT work well with `cmake --install ... --prefix <dir>`
    # due to this code relying on CMAKE_INSTALL_PREFIX being defined at configure time.
    #
    # NOTE: vulkan.pc essentially cover both Vulkan-Loader and Vulkan-Headers for legacy reasons.
    if ("${CMAKE_INSTALL_PREFIX}" STREQUAL "")
        set(CMAKE_INSTALL_LIBDIR_PC ${CMAKE_INSTALL_FULL_LIBDIR})
        set(CMAKE_INSTALL_INCLUDEDIR_PC ${CMAKE_INSTALL_FULL_INCLUDEDIR})
    else()
        file(RELATIVE_PATH CMAKE_INSTALL_LIBDIR_PC ${CMAKE_INSTALL_PREFIX} ${CMAKE_INSTALL_FULL_LIBDIR})
        file(RELATIVE_PATH CMAKE_INSTALL_INCLUDEDIR_PC ${CMAKE_INSTALL_PREFIX} ${CMAKE_INSTALL_FULL_INCLUDEDIR})
    endif()
```

Comment (rcombs) [reply Formula/v/vulkan-loader.rb]: Done.

**Review by chenrui333 — APPROVED** [review]

File: Formula/v/vulkan-loader.rb (hunk 1 above)
Comment (chenrui333) [reply Formula/v/vulkan-loader.rb]: make sense, yeah, I removed `inreplace` mostly because of the pc patch is not usable (I think)

**Review by juan-lunarg — COMMENTED** [review]
LGTM
