### PR TITLE
openjdk: allow postinstall without Xcode

### LINKED ISSUE #69100: OpenJDK post-install fails without Xcode on M1
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install openjdk on an M1 Mac that doesn't have Xcode installed.
## What happened (include command output)

The post-install stage had an error.

```
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 2.7.4-32-gbca4804
ORIGIN: https://github.com/Homebrew/brew
HEAD: bca4804a9e48de5319383d3eddadaa7f054c77da
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 74271951793445b680a247300b3c2e621aa4ff80
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: false
```
<details>
  <summary>Command output</summary>
  <pre>
==> Reinstalling openjdk
==> Pouring openjdk-15.0.1.arm64_big_sur.bottle.tar.gz
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openjdk`
==> An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_file_s_stat - /opt/homebrew/Library/Taps/homebrew/homebrew-core/SharedFrameworks/ContentDeliveryServices.framework/Versions/Current/itms/java/Frameworks/JavaNativeFoundation.framework

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1305:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1305:in `lstat'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1350:in `copy'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:478:in `block in copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1484:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:475:in `copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:453:in `block in cp_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:452:in `cp_r'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb:155:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1057:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:899:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1056:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:531:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1045:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
==> Caveats
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
This is a beta version of openjdk for Apple Silicon
(openjdk 16 preview).

openjdk is keg-only, which means it was not symlinked into /opt/homebrew,
because it shadows the macOS `java` wrapper.

If you need to have openjdk first in your PATH run:
  echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> /Users/dustin/.bash_profile

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

==> Summary
🍺  /opt/homebrew/Cellar/openjdk/15.0.1: 607 files, 305.2MB
  </pre>
</details>

## What you expected to happen

Post-install to not fail or to enforce an Xcode dependency on Apple Silicon.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install openjdk`

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes #69100

poke @tresf

### CODE REVIEW

File: Formula/openjdk.rb [hunk 1]
```diff
@@ -70,10 +70,10 @@ class Openjdk < Formula
     end
   end
 
-  # Calculate Xcode's dual-arch JavaNativeFoundation.framework path
+  # Path to dual-arch JavaNativeFoundation.framework from the CLT
+  # (not Xcode, since not all users have Xcode installed)
   def framework_path
-    File.expand_path("../SharedFrameworks/ContentDeliveryServices.framework/Versions/Current/itms/java/Frameworks",
-                     MacOS::Xcode.prefix)
+    MacOS.sdk_path/"System/Library/Frameworks/JavaNativeFoundation.framework"
```
Comment (carlocab) [inline Formula/openjdk.rb:76]: Don't you want the directory containing `JavaNativeFoundation.framework` here, and not the full path?

**Comment by fxcoudert** [comment]
```
checking for version string... 16+14
configure: Found potential Boot JDK using configure arguments
checking for Boot JDK... /private/tmp/openjdk-20210116-15639-1ao9ehn/jdk-sandbox-a56ddad05cf1808342aeff1b1cd2b0568a6cdc3a/boot-jdk/Contents/Home
Error: g Boot JDK version... [0.022s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 16384 openjdk version "16-ea" 2021-03-16 OpenJDK Runtime Environment (build 16-ea+31-2150) OpenJDK 64-Bit Server VM (build 16-ea+31-2150, mixed mode) 
```

**Comment by carlocab** [comment]
Related, maybe: https://developer.apple.com/forums/thread/654601

**Comment by tresf** [comment]
> Related, maybe: https://developer.apple.com/forums/thread/654601

From my understanding, the Xcode is the only viable version unless it's built from source.

@fxcoudert can you offer some context as to why this isn't desired?

**Comment by carlocab** [comment]
@tresf An Xcode installation takes ~10GB of space. CLT takes ~500MB.

**Comment by fxcoudert** [comment]
@tresf most of our users don't have Xcode installed: we require the presence of the CLT or Xcode, and the CLT is much lighter.

As I understand it, the reason you made this step part of `postinstall` rather than `install` is a signature issue? We could also fix that. Do you remember what file were involved?

**Comment by fxcoudert** [comment]
The only signed file I can see is this one:

```
Executable=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/Frameworks/JavaNativeFoundation.framework/Versions/A/JavaNativeFoundation
Identifier=com.apple.JavaNativeFoundation
Format=bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20200 size=926 flags=0x0(none) hashes=23+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=44762c356f6bd6c99e0d060817ee44652df73d00
CandidateCDHashFull sha256=44762c356f6bd6c99e0d060817ee44652df73d004bb15202da03d68a6c0628cf
Hash choices=sha256
CMSDigest=44762c356f6bd6c99e0d060817ee44652df73d004bb15202da03d68a6c0628cf
CMSDigestType=2
CDHash=44762c356f6bd6c99e0d060817ee44652df73d00
Signature size=4547
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist entries=21
TeamIdentifier=59GAB85EFG
Sealed Resources version=2 rules=13 files=2
Internal requirements count=1 size=80
```

It's possible `brew` is making its signature invalid by issuing a new ad hoc signature upon install, due to our relocation process. I can see two solutions:

- Remove the Apple signature, so it can then have a valid ad hoc-signature. I'm not sure if something in openjdk relies on this being actually signed by Apple?
- Or a cruder hack: hide it somehow during install (e.g. by compressing it) and restore it during postinstall.

**Comment by tresf** [comment]
> @tresf An Xcode installation takes ~10GB of space. CLT takes ~1GB.
> @tresf most of our users don't have Xcode installed: we require the presence of the CLT or Xcode, and the CLT is much lighter.

Then I'd assume it's a packaging issue.  I'm not familiar with what's bottled and what's not, but this should be distributed with the bottle and should only affect source installs.

**Comment by tresf** [comment]
Here's much more context regarding the decision to use XCode's version: https://gist.github.com/claui/ea4248aa64d6a1b06c6d6ed80bc2d2b8#gistcomment-3539574

**Comment by tresf** [comment]
> Remove the Apple signature, so it can then have a valid ad hoc-signature. I'm not sure if something in openjdk relies on this being actually signed by Apple?

It should work fine with ad-hoc, but it was never tackled due to order of operations (`install` vs. `post_install`) and the caching issues.  In hindsight it probably would have been better to keep it in the `install` step.  I think that will correct both the bottle and the Xcode dependency, assuming Homebrew's ok with keeping Xcode as a build-from-source dependency.

**Comment by fxcoudert** [comment]
@tresf thanks for that link, I think I understand. So if I'm right, we can copy the file from Xcode on install, replace its Apple signature by an ad-hoc one, and it should be good.

Is there a specific way I can test that this is working? Do you expect that the current test would catch it if it failed, or do I need to add something more specific to exercise this framework?

**Comment by tresf** [comment]
> Is there a specific way I can test that this is working? Do you expect that the current test would catch it if it failed, or do I need to add something more specific to exercise this framework?

Good question.  No, apparently not, the included Hello World doesn't seem to require this.  A relatively quick unit test is to compile and test if `JavaNativeFoundation.framework` is linked:

```
brew install maven
git clone https://github.com/apache/pdfbox
cd pdfbox
mvn test # <---- this is the test
```

* ✅ When it's linked properly, all but a font test will pass.
* 🚫 When it's not linked, you'll be spammed with `Could not initialize class` errors.

File: Formula/openjdk.rb [hunk 2]
```diff
@@ -147,14 +148,15 @@ def install
...
-      cp_r "#{framework_path}/JavaNativeFoundation.framework",
-           "#{libexec}/openjdk.jdk/Contents/Home/lib/JavaNativeFoundation.framework",
-           remove_destination: true
+      dest = libexec/"openjdk.jdk/Contents/Home/lib/JavaNativeFoundation.framework"
+      # Copy JavaNativeFoundation.framework from Xcode
+      # https://gist.github.com/claui/ea4248aa64d6a1b06c6d6ed80bc2d2b8#gistcomment-3539574
+      cp_r "#{framework_path}/JavaNativeFoundation.framework", dest, remove_destination: true
+
+      # Replace Apple signature by ad-hoc one (otherwise relocation will break it)
+      system "codesign", "-f", "-s", "-", "#{dest}/Versions/A/JavaNativeFoundation"
```
Comment (SMillerDev) [inline Formula/openjdk.rb:159]: Can we use the `MachO` gem for this?

Comment (fxcoudert) [reply Formula/openjdk.rb:159]: I'd rather not, because it passes arguments I don't think we want in this case: `--preserve-metadata=entitlements,requirements,flags,runtime`

**Comment by fxcoudert** [comment]
Testing was good, and local testing indicates that things are working as expected on ARM. But the `mockserver` test refuses to timeout and hangs. Will rebottle separately.
