### PR TITLE
glib: use homebrew Python to build

### LINKED ISSUE #210787: Failed to build glib from source if Xcode is not installed.
Many people met this issue. See the comments in [#207900](https://github.com/Homebrew/homebrew-core/pull/207900#issuecomment-2683802541).

### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.4.24-124-g6ac3311
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6ac3311f17a3b4c11fff700a70a7670fe46d7e1a
Last commit: 13 hours ago
Branch: master
Core tap JSON: 13 Mar 10:58 UTC
Core cask tap JSON: 13 Mar 10:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_DOMAIN: https://mirrors.aliyun.com/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
https_proxy: http://127.0.0.1:3128
Homebrew Ruby: 3.3.7 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 16.0.0 build 1600
Git: 2.48.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.3.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I want to build glib from source.

### What happened (include all command output)?

```bash
$ brew install -s glib
...
==> meson setup build -Dcairo=disabled -Ddoctool=disabled --prefix=/private/tmp/glib-20250226-87061-7mx920/glib-2.82.5/staging --libdir=/private/tmp/glib-20250226-87061-7mx920/glib-2.82.5/stag
Last 15 lines from /Users/***/Library/Logs/Homebrew/glib/04.meson:
Checking for size of "long" : 8
Found pkg-config: YES (/opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config) 2.3.0
Run-time dependency glib-2.0 found: YES 2.82.5
Run-time dependency gobject-2.0 found: YES 2.82.5
Run-time dependency gio-2.0 found: YES 2.82.5
Run-time dependency gmodule-2.0 found: YES 2.82.5
Run-time dependency gio-unix-2.0 found: YES 2.82.5
Run-time dependency libffi found: YES 3.4-rc1
Program pkg-config found: YES (/opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config)
Configuring config.h using configuration
Run-time dependency python found: NO (tried pkgconfig, pkgconfig and sysconfig)

meson.build:184:50: ERROR: Python dependency not found

A full log can be found at /private/tmp/glib--gobject-introspection-20250226-87061-ugii3g/gobject-introspection-1.82.0/build/meson-logs/meson-log.txt
```

### What did you expect to happen?

Build glib from source successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run `brew install -s glib`
```

### PR DESCRIPTION
**Pull request by adonis0147**
Fix #210787 

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by botantony** [comment]
If this is a real problem (which is kinda strange, how do you use Homebrew without Xcode) then it'd be more reasonable to change `uses_from_macos` function so that Homebrew would install missing formulae if there's no Xcode

**Comment by botantony** [comment]
@adonis0147 can you check if this patch fixes your problem?
```diff
diff --git a/Library/Homebrew/dependency.rb b/Library/Homebrew/dependency.rb
index 7ab9abbafa..86d3401e15 100644
--- a/Library/Homebrew/dependency.rb
+++ b/Library/Homebrew/dependency.rb
@@ -270,6 +270,8 @@ class UsesFromMacOSDependency < Dependency
   def use_macos_install?
     # Check whether macOS is new enough for dependency to not be required.
     if Homebrew::SimulateSystem.simulating_or_running_on_macos?
+      # Assume the dependency is not installed if there's no Xcode
+      return false if OS::Mac::Xcode.installed?
       # Assume the oldest macOS version when simulating a generic macOS version
       return true if Homebrew::SimulateSystem.current_os == :macos && !bounds.key?(:since)
 
```

Go to you Homebrew directory (`cd "$(brew --prefix)"`), then `cd Library/Homebrew` and apply patch on `dependency.rb` file

**Comment by SMillerDev** [comment]
> which is kinda strange, how do you use Homebrew without Xcode

Homebrew has no requirement on Xcode, only on the command line tools.

**Comment by botantony** [comment]
Yeah but shouldn't CLI dev tools install Python as well?

**Comment by gromgit** [comment]
> Yeah but shouldn't CLI dev tools install Python as well?

It should, which is why I asked @adonis0147 in the [related issue](https://github.com/Homebrew/homebrew-core/issues/210787) what errors he was getting during his glib build.

**Comment by adonis0147** [comment]
> > Yeah but shouldn't CLI dev tools install Python as well?
> 
> It should, which is why I asked @adonis0147 in the [related issue](https://github.com/Homebrew/homebrew-core/issues/210787) what errors he was getting during his glib build.

It seems that the log was removed after executing the command.

**Comment by gromgit** [comment]
> It seems that the log was removed after executing the command.

It's removed when you run `brew install -s` _again_, since it logs the new run in the same directory. Try this:
```
# Revert to the existing Homebrew code
git -C $(brew --repo) checkout master
# Run the install again
brew install -s glib
```
then check the Meson logs that are reported. I suspect that, once you drill down to the root cause, it's likely something local to your system which may not justify a Homebrew change for everybody.

**Comment by cho-m** [comment]
Looks like an Apple bug in CLT:
```console
❯ /Library/Developer/CommandLineTools/usr/bin/python3 -m sysconfig | grep INCLUDEPY
	CONFINCLUDEPY = "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers"
	INCLUDEPY = "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers"
```

Only a problem at build time due to how Meson uses the above path.

After #210662 is merged (to avoid conflict), can just add a build-time dependency (which is part of build dependency tree via Meson) while leaving runtime dependency as CLT/Xcode Python (to avoid extra runtime dependency):
```diff
diff --git a/Formula/g/glib.rb b/Formula/g/glib.rb
index c5f6dd208cf..928ac916d28 100644
--- a/Formula/g/glib.rb
+++ b/Formula/g/glib.rb
@@ -22,6 +22,7 @@ class Glib < Formula
   depends_on "ninja" => :build
   depends_on "pkgconf" => :build
   depends_on "python-setuptools" => :build # for gobject-introspection
+  depends_on "python@3.13" => :build
   depends_on "pcre2"
 
   uses_from_macos "flex" => :build # for gobject-introspection
```

Alternative would be adding C*FLAGS to help Meson find header, but directory path is a bit of a pain:
```console
❯ fd Python.h /Library/Developer/
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Headers/Python.h
```

**Comment by daeho-ro** [comment]
Can you rebase onto master?

File: Formula/g/glib.rb [hunk 1]
```diff
@@ -23,11 +23,11 @@ class Glib < Formula
   depends_on "ninja" => :build
   depends_on "pkgconf" => :build
   depends_on "python-setuptools" => :build # for gobject-introspection
+  depends_on "python@3.13" => :build
   depends_on "pcre2"
 
   uses_from_macos "flex" => :build # for gobject-introspection
   uses_from_macos "libffi", since: :catalina
-  uses_from_macos "python"
```
Comment (cho-m) [inline Formula/g/glib.rb:30]: This needs to be restored to allow Linux to find `python3` on PATH

**Review by carlocab — APPROVED** [review]
