### PR TITLE
rqlite: set version, commit hash etc build flags

### LINKED ISSUE #203123: rqlite: full version is missing
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.4.14-10-geac5720
ORIGIN: https://github.com/Homebrew/brew
HEAD: eac5720d44457fcfcb24b325bde3a70fce41ac15
Last commit: 4 days ago
Branch: master
Core tap JSON: 03 Jan 16:09 UTC
Core cask tap JSON: 03 Jan 16:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 604800
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.2
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

For now `rqlited -version` and `rqlite -v` gives version `8`.
Platform: macOS arm64, installed via homebrew

### What happened (include all command output)?

Current output:

```sh
$ rqlite -v
Version 8, commit unknown, branch unknown, built on unknown

$ rqlited -version
rqlited 8 darwin arm64 go1.23.4 sqlite3.46.1 (commit unknown, branch unknown, compiler gc)

$ rqlited /tmp/rqlite
...
[rqlited] 2025/01/03 19:09:34 rqlited starting, version 8, SQLite 3.46.1, commit unknown, branch unknown, compiler (toolchain) gc, compiler (command) unknown
...
```

### What did you expect to happen?

Output a full version, like `8.36.3`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install rqlite

rqlite -v

rqlited -version

rqlited /tmp/rqlite
```

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Closes https://github.com/Homebrew/homebrew-core/issues/203123

### CODE REVIEW

File: Formula/r/rqlite.rb [hunk 1]
```diff
@@ -18,8 +19,15 @@ class Rqlite < Formula
   depends_on "go" => :build
 
   def install
+    ldflags = %W[
+      -s -w
+      -X github.com/rqlite/rqlite/v8/cmd.Commit=#{Utils.git_head}
```
Comment (chenrui333) [inline Formula/r/rqlite.rb:24]:
```suggestion
      -X github.com/rqlite/rqlite/v8/cmd.Commit=#{tap.user}
```

File: Formula/r/rqlite.rb [hunk 2]
```diff
@@ -1,8 +1,9 @@
 class Rqlite < Formula
   desc "Lightweight, distributed relational database built on SQLite"
   homepage "https://www.rqlite.io/"
-  url "https://github.com/rqlite/rqlite/archive/refs/tags/v8.36.3.tar.gz"
-  sha256 "c57e1499e013d69f2c0201a368546691537a67388e967c38c03948a9ea208b57"
+  url "https://github.com/rqlite/rqlite.git",
+    tag:      "v8.36.3",
+    revision: "92bcff8e0b50570294c3d13f6b598821ad3daff6"
```
Comment (chenrui333) [inline Formula/r/rqlite.rb:6]: would be better to use tarball

File: Formula/r/rqlite.rb
Comment (chenrui333) [inline Formula/r/rqlite.rb:1]: might also need to check the version in test block as well

**Comment by dtrodrigues** [comment]
I switched to git so that the commit hash would be available. The tarball could continue to be used, but then the hash would be lost.

**Comment by chenrui333** [comment]
the hash is a bit of useless for release builds, we can either set empty or using tap.user.

**Comment by SMillerDev** [comment]
Generally upstreams think differently about that. Let's just use the checkout.

**Comment by dtrodrigues** [comment]
This is the output from the compiled upstream release, so I think it would make sense to mirror their values
```
./rqlite-v8.36.3-linux-amd64/rqlite -v
Version v8.36.3, commit 92bcff8e0b50570294c3d13f6b598821ad3daff6, branch master, built on 2024-12-27T20:06:47+0000
```

It also aligns with what the `rqlite` creator suggested: https://github.com/Homebrew/homebrew-core/issues/203123#issuecomment-2569496469

File: Formula/r/rqlite.rb (hunk 2 above)
Comment (dtrodrigues) [reply Formula/r/rqlite.rb:6]: Tarball cannot be used if we want the commit hash.

File: Formula/r/rqlite.rb (hunk 1 above)
Comment (dtrodrigues) [reply Formula/r/rqlite.rb:24]: Continuing to use the commit hash mirrors upstream behavior.

File: Formula/r/rqlite.rb
Comment (dtrodrigues) [reply Formula/r/rqlite.rb:1]: Test to check the version string has been added.

**Comment by otoolep** [comment]
I added the commit hash for my own convenience, I agree it's a bit low-level for most folks. In practise it is the tag value e.g. v8.36.1 that is most important to include. So I can either way whether you want to set it, or just leave it at `unknown`.

File: Formula/r/rqlite.rb (hunk 2 above)
Comment (otoolep) [reply Formula/r/rqlite.rb:6]: As mentioned, commit hash is a nice-to-have. I don't consider it critical to the release information.

File: Formula/r/rqlite.rb (hunk 1 above)
Comment (otoolep) [reply Formula/r/rqlite.rb:24]: We may wish to parameterize `v8`, not sure. What is the right way to handle the eventual release of rqlite v9? I expect a new major release during 2025.

Comment (otoolep) [inline Formula/r/rqlite.rb:24]: We may wish to parameterize v8, not sure. What is the right way to handle the eventual release of rqlite v9? I expect a new major release during 2025.

**Comment by dtrodrigues** [comment]
Thanks @otoolep. Since there isn't a strong desire to include the commit hash, we'll switch back to the release tarball but will still include the full version string.

File: Formula/r/rqlite.rb (hunk 1 above)
Comment (dtrodrigues) [reply Formula/r/rqlite.rb:24]: We can use the `version.major` to account for this.

**Comment by otoolep** [comment]
LGTM.

**Review by branchv — APPROVED** [review]

**Comment by otoolep** [comment]
Thank you @dtrodrigues
