### PR TITLE
neo4j 4.1.3

### LINKED ISSUE #61713: Neo4j 4.1.x requires java 11, but the formula requires java 8
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- N/A ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- N/A if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install neo4j

## What happened (include command output)

Neo4j 4.1.2 installed, with output:

```
==> Upgrading neo4j 4.1.1 -> 4.1.2
neo4j: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: neo4j: An unsatisfied requirement failed this build.
```

However neo4j 4.x requires java 11 see https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-software 

`/usr/local/Cellar/neo4j/4.1.1/libexec/bin/neo4j` explicitly mentions:
```
* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
```

## What you expected to happen

Install should require java 11.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install neo4j
```

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

File: Formula/neo4j.rb [hunk 1]
```diff
@@ -13,17 +13,13 @@ class Neo4j < Formula
...
-  # https://github.com/Homebrew/homebrew-core/issues/31090
-  # As of v4.1.0, neo4j still needs to build with java 1.8
-  # https://github.com/neo4j/neo4j/issues/12516
-  depends_on java: "1.8"
+  depends_on "openjdk@11"
 
   def install
-    ENV["NEO4J_HOME"] = libexec
+    env = {
+      JAVA_HOME:  Formula["openjdk@11"].opt_prefix,
```
Comment (chenrui333) [inline Formula/neo4j.rb:20]: is there anyway that we can use `overridable_java_home`?

Comment (alebcay) [reply Formula/neo4j.rb:20]: I thought about it, but felt that there wouldn't be much need for it. It's a database, not a development tool of some kind that would actually benefit from allowing this to be overridden. See https://github.com/Homebrew/homebrew-core/pull/60128#issuecomment-679455200.

Comment (chenrui333) [reply Formula/neo4j.rb:20]: Got you, that comment link is helpful!

**Review by chenrui333 — APPROVED** [review]
