### PR TITLE
node@16: bump revision (icu4c 74.2)

### LINKED ISSUE #168102: node@16 has breaking changes with icu4c
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@16
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

node --version

### What happened (include all command output)?

❯ node --version 
                                                                                                                                                                                    j
dyld[22683]: Library not loaded: /opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib
  Referenced from: <C1E5A803-7E1C-3145-87AA-6A712C26D8B9> /opt/homebrew/Cellar/node@16/16.20.2/bin/node
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file)
[1]    22683 abort      node --version

### What did you expect to happen?

print node version

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
node or npm both are not working with version the new version of icu4c
```

### LINKED ISSUE #168513: Please add  icu4c@73 to the list of icu4c tap versions
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
All fine
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I need to install icu4c v. 73.2, since my project has a required Node v.16

Please, add icu4c@73 to the tap versions of icu4c. Thanks.

### What happened (include all command output)?

user_name$ node -v

dyld[4874]: Library not loaded: '/usr/local/opt/icu4c/lib/libicui18n.73.dylib'
  Referenced from: '/usr/local/Cellar/node@16/16.20.2/bin/node'
  Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/usr/local/lib/libicui18n.73.dylib' (no such file), '/usr/lib/libicui18n.73.dylib' (no such file), '/usr/local/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/usr/local/lib/libicui18n.73.dylib' (no such file), '/usr/lib/libicui18n.73.dylib' (no such file)
Abort trap: 6

### What did you expect to happen?

See the installed Node version

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install icu4c 

installs the latest v74.2

Unfortunately, I cannot run

brew install icu4c@73

to install the version my node@16 requires.
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

We've received queries regarding `node@16` being broken due to `icu4c` update. Since it's not disabled yet let's build the bottles for it.

Fixes #168102.
Fixes #168513.

### CODE REVIEW

File: Formula/n/node@16.rb [hunk 1]
```diff
@@ -22,7 +23,6 @@ class NodeAT16 < Formula
   deprecate! date: "2023-11-02", because: :unsupported
 
   depends_on "pkg-config" => :build
-  depends_on "python-setuptools" => :build
```
Comment (chenrui333) [inline Formula/n/node@16.rb:25]: still need it?

Comment (ZhongRuoyu) [reply Formula/n/node@16.rb:25]: Oops, didn't work -- trying a different approach.

**Comment by ZhongRuoyu** [comment]
```
  npm ERR! Traceback (most recent call last):
  npm ERR!   File "/home/linuxbrew/.linuxbrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
  npm ERR!     import gyp  # noqa: E402
  npm ERR!     ^^^^^^^^^^
  npm ERR!   File "/home/linuxbrew/.linuxbrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
  npm ERR!     import gyp.input
  npm ERR!   File "/home/linuxbrew/.linuxbrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
  npm ERR!     from distutils.version import StrictVersion
  npm ERR! ModuleNotFoundError: No module named 'distutils'
  npm ERR! gyp ERR! configure error 
  npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
  npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/linuxbrew/.linuxbrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
  npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
  npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
  npm ERR! gyp ERR! System Linux 6.5.0-1017-azure
  npm ERR! gyp ERR! command "/home/linuxbrew/.linuxbrew/Cellar/node@16/16.20.2_1/bin/node" "/home/linuxbrew/.linuxbrew/Cellar/node@16/16.20.2_1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

`node-gyp` from the bundled npm does not support Python 3.12: https://github.com/nodejs/node-gyp#installation

**Review by SMillerDev — APPROVED** [review]
