### PR TITLE
octave: fix for Qt 5.12 compatibility

### LINKED ISSUE #35903: Octave `--with-qt` GUI build broken
- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? *A couple lingering issues; they don't look relevalt.*
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

-------

I'm trying to build Octave with the Qt GUI using `brew install octave --with-qt`. The build succeeds, but it's built without Qt.

Launching the GUI fails.
```
$ octave --gui
octave: GUI features missing or disabled in this build
```
That should have brought up the Qt GUI.

Looks like it's failing because it's expecting `qcollectiongenerator` from Qt 5.11 and earlier, but in Qt 5.12 that has been folded into `qhelpgenerator`.

To reproduce:
```
brew install octave --with-qt
```

My build logs: https://gist.github.com/6bdcc4c6d59abcb1ead75f4e96a9140d

Relevant part from `configure` output:
```
  Build Octave Qt GUI:                  no (missing:qcollectiongenerator)
```

Upstream bug: https://savannah.gnu.org/bugs/index.php?55187

My `brew doctor`:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  octave-head-test
```

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #35903.

This PR hacks in Qt 5.12 support to Octave 4.4.1's build process, restoring `octave --gui` functionality.

No revision bump needed because this only affects an optional build path.

### CODE REVIEW

File: Formula/octave.rb [hunk 1]
```diff
@@ -65,7 +65,15 @@ def install
     inreplace "src/mkoctfile.in.cc", /%OCTAVE_CONF_OCT(AVE)?_LINK_(DEPS|OPTS)%/, '""'
 
     args = []
-    args << "--without-qt" if build.without? "qt"
+    if build.with? "qt"
+      # Stuff for Qt 5.12 compatibility
+      # https://savannah.gnu.org/bugs/?55187
+      ENV["QCOLLECTIONGENERATOR"]="qhelpgenerator"
+      ENV.append "CPPFLAGS", "-I#{Formula["qt"].opt_include}"
+      ENV.append "LDFLAGS", "-F#{Formula["qt"].opt_lib}"
```
Comment (fxcoudert) [inline Formula/octave.rb]: I don't understand the need for `CPPFLAGS` and `LDFLAGS`, given that Homebrew should add these automatically

Comment (apjanke) [reply Formula/octave.rb]: You're right. Those were left over from when I was building it outside Homebrew. Removed.

**Comment by fxcoudert** [comment]
Thanks @apjanke

**Comment by apjanke** [comment]
You're welcome!
