### PR TITLE
qt: depend on mysql-client optionally instead of mysql

### LINKED ISSUE #29013: qt5 --with-mysql fails to build on macOS: 10.13.5-x86_64
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/apaiva/f56698fc9eff0ba407829186d42a56f1

- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew gist-logs worked.

To help us debug your issue please explain:
- What you were trying to do (and why)

Reinstall qt5 with mysql support.   I've been using qt5 via pyqt for some time now and recently needed to add mysql support.  I've uninstalled qt5 and attempted to install again with "brew install -v qt5 --with-mysql"; however, the build fails.

- What happened (include command output)

Full output is in the gist, but here's the first error is:

qsql_mysql.cpp:235:9: error: unknown type name 'my_bool'
        my_bool nullIndicator;
        ^

- What you expected to happen

Clean build.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install -v --build-from-source qt5 --with-mysql

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #29013

The current Qt 5.11.0 seems to be targeting MySQL 5.7, and the new
MySQL 8 release is not compatible at the source level. `brew install qt --with-mysql` is currently broken.

This PR fixes it by pinning the mysql dependency to version 5.7.

No revision bump necessary, since this only affects non-default options. You can probably kill the CI build for it, too; it's a long build.

Audit is failing for me, but it appears to be a transient error with a mirror host.

```
$ brew audit --strict --online qt
qt:
  * Stable: The URL https://qt.mirror.constant.com/archive/qt/5.11/5.11.0/single/qt-everywhere-src-5.11.0.tar.xz is not reachable
Error: 1 problem in 1 formula
```

### CODE REVIEW

**Comment by ilovezfs** [comment]
Can we use `depends_on "mysql-client" => :optional` instead?

**Comment by apjanke** [comment]
Dunno; testing it now.

**Comment by apjanke** [comment]
Yes. Amended to use `mysql-client` instead.

File: Formula/qt.rb [hunk 1]
```diff
@@ -56,7 +58,7 @@ def install
 
     args << "-nomake" << "examples" if build.without? "examples"
 
-    if build.with? "mysql"
+    if build.with? "mysql@5.7"
```
Comment (ilovezfs) [inline Formula/qt.rb]: also here

**Comment by ilovezfs** [comment]
🚀
