### PR TITLE
ruby*: remove toolchain refs from `rbconfig.rb`

### LINKED ISSUE #206828: ruby: [linux] compiler toolchain version is hardcoded in `rbconfig`
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❱ brew config
HOMEBREW_VERSION: 4.4.20-75-g7619878
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76198789ae6693cd4fe28644d72299448374551c
Last commit: 6 hours ago
Branch: master
Core tap JSON: 06 Feb 22:08 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_INSTALL_BADGE: ☕
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_GITHUB_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.7/bin/ruby
CPU: 16-core 64-bit zen5
Clang: 19.1.7
Git: 2.48.1 => /bin/git
Curl: 8.9.1 => /bin/curl
Kernel: Linux 6.12.10-200.fc41.x86_64 x86_64 GNU/Linux
OS: Fedora Linux 41 (KDE Plasma)
Host glibc: 2.40
/usr/bin/gcc: 14.2.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A



❱ brew doctor
Your system is ready to brew.
```

### Verification

- [x] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Installing gem with extensions that use `mkmf`, which in turn uses `rbconfig`, will fail if the exact compiler version that was used to compile ruby itself is not installed.

### What happened (include all command output)?

<details>

<summary>Installing the `json` gem</summary>

```console
❱ "$HOMEBREW_PREFIX/opt/ruby/bin/gem" install json
Building native extensions. This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.4.0/gems/json-2.9.1/ext/json/ext/generator
/home/linuxbrew/.linuxbrew/opt/ruby/bin/ruby extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/bin/$(RUBY_BASE_NAME)
/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:528:in 'MakeMakefile#try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:655:in 'MakeMakefile#try_compile'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:737:in 'MakeMakefile#try_cflags'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:1110:in 'block (2 levels) in MakeMakefile#append_cflags'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:1070:in 'block in MakeMakefile#checking_for'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:370:in 'block (2 levels) in MakeMakefile::Logging.postpone'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:340:in 'MakeMakefile::Logging.open'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:370:in 'block in MakeMakefile::Logging.postpone'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:340:in 'MakeMakefile::Logging.open'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:366:in 'MakeMakefile::Logging.postpone'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:1069:in 'MakeMakefile#checking_for'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:1109:in 'block in MakeMakefile#append_cflags'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:1108:in 'Array#each'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/mkmf.rb:1108:in 'MakeMakefile#append_cflags'
	from extconf.rb:7:in '<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.4.0/extensions/x86_64-linux/3.4.0/json-2.9.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.4.0/gems/json-2.9.1 for inspection.
Results logged to /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.4.0/extensions/x86_64-linux/3.4.0/json-2.9.1/gem_make.out
```

</details>

<details>
<summary>mkmf.log</summary>

```
LD_LIBRARY_PATH=.:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib:/home/linuxbrew/.linuxbrew/lib ASAN_OPTIONS=detect_leaks=0 "gcc-11 -o conftest -I/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/include/ruby-3.4.0/x86_64-linux -I/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/include/ruby-3.4.0/ruby/backward -I/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/include/ruby-3.4.0 -I. -I/home/linuxbrew/.linuxbrew/opt/libyaml/include -I/home/linuxbrew/.linuxbrew/opt/openssl@3/include    -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdiv-by-zero -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wold-style-definition -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wmisleading-indentation -Wundef  -fPIC conftest.c -L. -L/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib -L/home/linuxbrew/.linuxbrew/opt/libyaml/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/libyaml/lib -L/home/linuxbrew/.linuxbrew/opt/openssl@3/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/openssl@3/lib -L. -fstack-protector-strong -L/home/linuxbrew/.linuxbrew/Cellar/libyaml/0.2.5/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/libyaml/0.2.5/lib -L/home/linuxbrew/.linuxbrew/Cellar/openssl@3/3.4.0/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/openssl@3/3.4.0/lib -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib -L/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1/lib -lruby  -lm -lpthread  -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```
</details>

Released `RbConfig`:

```console
❱ "$HOMEBREW_PREFIX/opt/ruby/bin/ruby" -e 'require "rbconfig"; puts(RbConfig::CONFIG["CC"])'
gcc-11
```

```console
❱ "$HOMEBREW_PREFIX/opt/ruby/bin/ruby" -e 'require "rbconfig"; pp(RbConfig::CONFIG.select { |k,v| v =~ /-11/ })'
{"configure_args" =>
  " '--prefix=/home/linuxbrew/.linuxbrew/Cellar/ruby/3.4.1' '--enable-shared' '--disable-silent-rules' '--with-sitedir=/home/linuxbrew/.linuxbrew/lib/ruby/site_ruby' '--with-vendordir=/home/linuxbrew/.linuxbrew/lib/ruby/vendor_ruby' '--with-opt-dir=/home/linuxbrew/.linuxbrew/opt/libyaml:/home/linuxbrew/.linuxbrew/opt/openssl@3' '--without-gmp' 'MJIT_CC=/usr/bin/gcc' 'CC=gcc-11' 'CXX=g++-11'",
 "DLDSHARED" => "gcc-11 -shared",
 "LDSHAREDXX" => "g++-11 -shared",
 "LDSHARED" => "gcc-11 -shared",
 "CC_VERSION_MESSAGE" =>
  "gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0\n" +
  "Copyright (C) 2021 Free Software Foundation, Inc.\n" +
  "This is free software; see the source for copying conditions.  There is NO\n" +
  "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.",
 "CC_VERSION" => "gcc-11 --version",
 "CPP" => "gcc-11 -E",
 "RANLIB" => "gcc-ranlib-11",
 "NM" => "gcc-nm-11",
 "CXX" => "g++-11",
 "AR" => "gcc-ar-11",
 "CC" => "gcc-11"}
```

### What did you expect to happen?

Ruby's `RbConfig` should not contain hardcoded versions.

This is similar, but NOT related to https://github.com/Homebrew/homebrew-core/issues/170978 and https://github.com/Homebrew/homebrew-core/issues/182739.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ruby

"$HOMEBREW_PREFIX/opt/ruby/bin/ruby" -e 'require "rbconfig"; puts(RbConfig::CONFIG["CC"])'
```

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is similar to what we do for Portable Ruby [^1].

Fixes #206828.

[^1]: https://github.com/Homebrew/homebrew-portable-ruby/blob/0f62a8a8d8fb23070e8ea41bb42c72714c86de4f/Formula/portable-ruby.rb#L133-L142

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
`licensed` failure doesn't look related as changes don't affect macOS at all.

```
  ==> Testing licensed (again)
  ==> /usr/local/Cellar/licensed/5.0.2/bin/licensed version
  ==> /usr/local/Cellar/licensed/5.0.2/bin/licensed cache
  Caching dependency records for test
  Error: licensed: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: 1
```

**Review by SMillerDev — APPROVED** [review]

File: Formula/r/ruby.rb [hunk 1]
```diff
@@ -119,6 +119,19 @@ def install
...
+      arch = Utils.safe_popen_read(
+        bin/"ruby", "-rrbconfig", "-e", 'print RbConfig::CONFIG["arch"]'
+      ).chomp
+      # Don't restrict to a specific GCC compiler binary we used (e.g. gcc-5).
+      inreplace lib/"ruby/#{api_version}/#{arch}/rbconfig.rb" do |s|
+        s.gsub! ENV.cxx, "c++"
+        s.gsub! ENV.cc, "cc"
+        # Change e.g. `CONFIG["AR"] = "gcc-ar-11"` to `CONFIG["AR"] = "ar"`
+        s.gsub!(/(CONFIG\[".+"\] = )"(?:gcc|g\+\+)-(.*)-\d+"/, '\\1"\\2"')
+      end
```
Comment (XuehaiPan) [inline Formula/r/ruby.rb:132]: `inreplace` may fail due to no replacement if the user passes `brew install ruby --cc gcc` or `brew install ruby --cc clang`.
